### ISSUE TITLE
Remove Orlando from Brazil

### ISSUE THREAD

**Issue by karakalpak** [flaghunters/Extra-Flags-for-4chan#101]
For some reason I've seen Brazilians posting under the flag of Orlando. It's not some Brazilian city named Orlando (Google tells you there aren't any), it's identical to the flag of Orlando in the US folder, and it matches the actual flag of Orlando, Florida. 

I'd appreciate it if you removed it and appease my autism, thanks.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks, has been removed.
