### ISSUE TITLE
Australian City Flags

### ISSUE THREAD

**Issue by fibre1** [flaghunters/Extra-Flags-for-4chan#102]
Aussies need city flags so outback Victorians don't look like degenerate Melbournians at a glance.
![adelaide](https://cloud.githubusercontent.com/assets/16143161/13370732/006cd4b2-dd65-11e5-99ad-6360343835b7.png) Adelaide
![alice](https://cloud.githubusercontent.com/assets/16143161/13355814/583be558-dcf6-11e5-85e8-7cd709f98853.png) Alice Springs
![brisbane](https://cloud.githubusercontent.com/assets/16143161/13355818/5f2a68c6-dcf6-11e5-9a3d-cac8cf4792b3.png) Brisbane
![cairns](https://cloud.githubusercontent.com/assets/16143161/13355836/6a9d35da-dcf6-11e5-857b-d250d694b4b3.png) Cairns
![darwin](https://cloud.githubusercontent.com/assets/16143161/13355840/6f9a46b8-dcf6-11e5-95f3-4e61b68f8760.png) Darwin
![hobart](https://cloud.githubusercontent.com/assets/16143161/13370734/0d3c691e-dd65-11e5-8d5a-20f63fd5976e.png) Hobart
![launceston](https://cloud.githubusercontent.com/assets/16143161/13356140/0bb3eb98-dcf8-11e5-87e7-eacd957793df.png) Launceston
![melbourne](https://cloud.githubusercontent.com/assets/16143161/13370736/159f4112-dd65-11e5-8c51-e098faa4782b.png) Melbourne
![perth](https://cloud.githubusercontent.com/assets/16143161/13370740/1f085bd0-dd65-11e5-8a94-c8a575cdde62.png) Perth
![sydney](https://cloud.githubusercontent.com/assets/16143161/13355869/8b90632a-dcf6-11e5-874c-1a3aab4a2686.png) Sydney
![townsville](https://cloud.githubusercontent.com/assets/16143161/13355888/a94bc850-dcf6-11e5-8807-ced424a60779.png) Townsville

These are the major towns and cities that appear on zoomed out maps, excluding Port Headand, Mackay, Newcastle and a few other areas that don't have either official or predominant flags.

There are more places like ![geelong](https://cloud.githubusercontent.com/assets/16143161/13370743/2c56fe2c-dd65-11e5-8979-faf9111b92a6.png) Geelong, Victoria's second largest city, but I dunno if they're really significant enough to be included.

You might also want the flags of the and the ![torres](https://cloud.githubusercontent.com/assets/16143161/13355881/9eda5ddc-dcf6-11e5-9fc1-105333110df3.png) Torres Strait Islands and ![abo](https://cloud.githubusercontent.com/assets/16143161/13355907/bf488c6a-dcf6-11e5-96b1-e41426c3e4e8.png) Indigenous Protected Areas for extra ebin and cultural diversity

![fnq](https://cloud.githubusercontent.com/assets/16143161/13355845/765180fc-dcf6-11e5-8a6f-303ac8a169c4.png) Far North Queensland could be worth adding. Separate rural area and pseudostate seeking autonomy.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Please zip and upload to mediafire or mega.
Getting a lot of new flags lately and it's a pain to save them and rename them individually.

Torres Strait Islands seems to be quite a legit flag for the territory. 
I'm not sure about the other two, do they have official recognition?

**Comment by fibre1** [comment]
http://www.mediafire.com/download/y7gu1tdn2a1hd05/Ausflags.zip

I didn't include the Indigenous or FNQ flag. The Indigenous one represents more of a collection of areas like the American Indian Reserves than a real state, and FNQ has no legal status anyway. I just felt like making more flags.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks for the zip fam they're in.
