### ISSUE TITLE
Indian 'flags'

### ISSUE THREAD

**Issue by u01hr4** [flaghunters/Extra-Flags-for-4chan#103]
Hello again, here's a fresh batch of Indian flags. Since only a couple of states (and union territories) have genuine flags, I've used the their official seals in their stead where applicable. Feel free to discard them, since they aren't true flags, but they might be the closest thing to real Indian regional flags. 

Andaman and Nicobar Islands
![andaman and nicobar islands](https://cloud.githubusercontent.com/assets/17348704/13356177/0e698c46-dc9c-11e5-8515-6d37b1ce9b6c.png)
Andhra Pradesh
![andhra pradesh](https://cloud.githubusercontent.com/assets/17348704/13356178/0e6d4fe8-dc9c-11e5-8557-a76ba87002ae.png)
Arunachal Pradesh
![arunachal pradesh](https://cloud.githubusercontent.com/assets/17348704/13356179/0e715354-dc9c-11e5-852a-408b180a9ea4.png)
Assam
![assam](https://cloud.githubusercontent.com/assets/17348704/13356180/0e737fa8-dc9c-11e5-95b8-f703ac501f02.png)
Chandigarh
![chandigarh](https://cloud.githubusercontent.com/assets/17348704/13356181/0e76657e-dc9c-11e5-9642-f7b5ce762008.png)
Chhattisgarh
![chhattisgarh](https://cloud.githubusercontent.com/assets/17348704/13356182/0e7851c2-dc9c-11e5-8c31-a0b42197a528.png)
Dadra and Nagar Haveli
![dadra and nagar haveli](https://cloud.githubusercontent.com/assets/17348704/13356183/0e83969a-dc9c-11e5-844f-197614905732.png)
Daman and Diu
![daman and diu](https://cloud.githubusercontent.com/assets/17348704/13356184/0e86430e-dc9c-11e5-833a-b5bd62d4ea4a.png)
Delhi
![delhi](https://cloud.githubusercontent.com/assets/17348704/13356185/0e8e10a2-dc9c-11e5-9f1b-d0592b085aca.png)
Goa
![goa](https://cloud.githubusercontent.com/assets/17348704/13356186/0e8fb09c-dc9c-11e5-9533-755ef48021aa.png)
Gujarat
![gujarat](https://cloud.githubusercontent.com/assets/17348704/13356187/0e933dc0-dc9c-11e5-9a2f-c0bd527256a7.png)
Hryana
![haryana](https://cloud.githubusercontent.com/assets/17348704/13356188/0e9468b2-dc9c-11e5-9123-ffd73134fe6e.png)
Himachal Pradesh
![himachal pradesh](https://cloud.githubusercontent.com/assets/17348704/13356189/0e9d6a34-dc9c-11e5-8caf-c08d9660b18c.png)
Jharkhand
![jharkhand](https://cloud.githubusercontent.com/assets/17348704/13356190/0e9fdfb2-dc9c-11e5-8fcf-084f5bb703c6.png)
Karnataka
![karnataka](https://cloud.githubusercontent.com/assets/17348704/13356191/0ea938aa-dc9c-11e5-86be-11b87cca3b84.png)
Kerala
![kerala](https://cloud.githubusercontent.com/assets/17348704/13356194/0eb169d0-dc9c-11e5-9a79-04fb9ad10cbc.png)
Lakshadweep
![lakshadweep](https://cloud.githubusercontent.com/assets/17348704/13356193/0eb0e654-dc9c-11e5-8dbc-27719aad4537.png)
Madhya Pradesh
![madhya pradesh](https://cloud.githubusercontent.com/assets/17348704/13356192/0eb096f4-dc9c-11e5-80fd-1e90e1d4f9b1.png)
Maharashtra
![maharashtra](https://cloud.githubusercontent.com/assets/17348704/13356195/0eb86ec4-dc9c-11e5-9b17-057b49a3a031.png)
Manipur
![manipur](https://cloud.githubusercontent.com/assets/17348704/13356196/0eb8aa1a-dc9c-11e5-8412-64500ead4497.png)
Meghalaya
![meghalaya](https://cloud.githubusercontent.com/assets/17348704/13356200/0ed1b5f0-dc9c-11e5-9dec-0ec0a7c80211.png)
Mizoram
![mizoram](https://cloud.githubusercontent.com/assets/17348704/13356197/0eccba46-dc9c-11e5-9e14-a96a253df11a.png)
Nagaland
![nagaland](https://cloud.githubusercontent.com/assets/17348704/13356198/0ecf66ce-dc9c-11e5-8c86-f50c7c2181ec.png)
Odisha
![odisha](https://cloud.githubusercontent.com/assets/17348704/13356199/0ed00912-dc9c-11e5-857a-3a7ee686914e.png)
Pudcherry
![pudcherry](https://cloud.githubusercontent.com/assets/17348704/13356201/0ed2ddc2-dc9c-11e5-9713-aeb87e2d3a3f.png)
Punjab
![punjab](https://cloud.githubusercontent.com/assets/17348704/13356202/0ed496bc-dc9c-11e5-8997-4127cc544fcb.png)
Rajasthan
![rajasthan](https://cloud.githubusercontent.com/assets/17348704/13356203/0ee9133a-dc9c-11e5-9920-fe6d1394f569.png)
Sikkim
![sikkim](https://cloud.githubusercontent.com/assets/17348704/13356204/0eea9304-dc9c-11e5-8ed1-6db6f377d634.png)
Tamil Nadu
![tamil nadu](https://cloud.githubusercontent.com/assets/17348704/13356205/0eebf0a0-dc9c-11e5-9432-a940df4add83.png)
Telengana
![telangana](https://cloud.githubusercontent.com/assets/17348704/13356206/0eee751e-dc9c-11e5-938b-4b9ebc229ca7.png)
Tripura
![tripura](https://cloud.githubusercontent.com/assets/17348704/13356207/0ef0daa2-dc9c-11e5-9f9b-504d92889f04.png)
Uttar Pradesh
![uttar pradesh](https://cloud.githubusercontent.com/assets/17348704/13356209/0ef31e7a-dc9c-11e5-9838-055dfd2f9a89.png)
Uttarakhand
![uttarakhand](https://cloud.githubusercontent.com/assets/17348704/13356210/0f044a06-dc9c-11e5-827e-e9b72435af42.png)
West Bengal
![west bengal](https://cloud.githubusercontent.com/assets/17348704/13356211/0f07efa8-dc9c-11e5-9666-830369e2b288.png)

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Please zip and upload to mediafire or mega.
Getting a lot of new flags lately and it's a pain to save them and rename them individually.

**Comment by fibre1** [comment]
http://www.mediafire.com/download/9pik43v4wa81370/indiaflags.zip

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks fam, replaced the Sikkim and Karnatanka flags with your seals because the ones we had were historic and the other unofficial.
