### ISSUE TITLE
Fix for Aussie City Flag Gloss

### ISSUE THREAD

**Issue by fibre1** [flaghunters/Extra-Flags-for-4chan#104]
![broblem](https://cloud.githubusercontent.com/assets/16143161/13377138/cb55f7b8-de22-11e5-81f4-3639860be53f.png)

The border/gloss on some of the Australian city flags I uploaded yesterday didn't apply right. I fixed the offending ones and upped them here if you wanna swap them out. They're all named correctly like last time and ready to go.

http://www.mediafire.com/download/ecsj2iv25ckveuq/AusflagsFixed.zip

Sorry for the fuckup. Pls no bully
***
_Edit:_ Turns out Newcastle does have a flag. I made a bunch more while I was at it. 

![gold coast](https://cloud.githubusercontent.com/assets/16143161/13378598/7d09d5ce-de5f-11e5-9543-12c0e68d6cfa.png) Gold Coast
![lord howe island](https://cloud.githubusercontent.com/assets/16143161/13378600/81d5cf36-de5f-11e5-95a2-1077f9299175.png) Lord Howe Island
![mildura](https://cloud.githubusercontent.com/assets/16143161/13378602/8a7b6952-de5f-11e5-9416-8bbd9b625f78.png) Mildura
![newcastle](https://cloud.githubusercontent.com/assets/16143161/13378603/8e8478b8-de5f-11e5-882a-27eda0170c23.png) Newcastle
![toowoomba](https://cloud.githubusercontent.com/assets/16143161/13378604/93942934-de5f-11e5-82d0-edbe0b6ba230.png) Toowoomba
![whitsunday islands](https://cloud.githubusercontent.com/assets/16143161/13378606/9a21649c-de5f-11e5-8fff-08d753666299.png) Whitsunday Islands
![wollongong](https://cloud.githubusercontent.com/assets/16143161/13378608/a0750bbe-de5f-11e5-8dd8-73435b97e237.png) Wollongong

http://www.mediafire.com/download/4oqtc7pcf3lufkt/AusflagsPlus.zip
Also all named correctly

**Comment by fibre1** [comment]
I just found out ![newcastle](https://cloud.githubusercontent.com/assets/16143161/13377882/5f110f14-de42-11e5-99de-75b159bb5b25.png)Newcastle has a flag. You want me to put it on Mediafire?

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
No problem and thanks for the new ones.
I updated and added them.
Some of those names though...
