### ISSUE TITLE
Flag Request

### ISSUE THREAD

**Issue by cakeguy** [flaghunters/Extra-Flags-for-4chan#107]
Wondering if you could add the flag of Riverside, CA
https://en.wikipedia.org/wiki/Riverside,_California#/media/File:Flag_of_Riverside,_California.svg

**Comment by LenticCatachresis** [comment]
![riverside](https://cloud.githubusercontent.com/assets/17322246/13469095/bc2a6dfa-e09d-11e5-936a-052c67cbe958.png)

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks, added.
