### ISSUE TITLE
Bulgaria

### ISSUE THREAD

**Issue by LenticCatachresis** [flaghunters/Extra-Flags-for-4chan#110]
https://mega.nz/#!KREBzRKY!sAodc2fIGmCICZxtGENZkDwZ-7X4eRnUH9a8On8vob8

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Since you seem to be on a roll, would you like to join the team?
With it you can put your flags directly into the repo.
Only requirement is that you are able to work with git.

**Comment by LenticCatachresis** [comment]
I don't know how to use Git, sorry m8

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Alright, too bad, these are added, thanks fam.
