### ISSUE TITLE
Kyrgyzstan

### ISSUE THREAD

**Issue by LenticCatachresis** [flaghunters/Extra-Flags-for-4chan#111]
Batken:
![batken](https://cloud.githubusercontent.com/assets/17322246/13547570/7ece4e42-e2d0-11e5-8beb-7c52363b953d.png)

Issyk Kul:
![issyk kul](https://cloud.githubusercontent.com/assets/17322246/13547572/85c76e04-e2d0-11e5-942d-d2a4b0c4f339.png)

Jalal-Abad:
![jalal-abad](https://cloud.githubusercontent.com/assets/17322246/13547576/9ad142c0-e2d0-11e5-925b-f3e007c28e58.png)

Naryn:
![naryn](https://cloud.githubusercontent.com/assets/17322246/13547577/a1abfedc-e2d0-11e5-9c30-25e9e57b88a4.png)

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks, added.
