### ISSUE TITLE
Australia

### ISSUE THREAD

**Issue by fibre1** [flaghunters/Extra-Flags-for-4chan#112]
This finishes flags for the the top 22 largest population centers, excluding those without a dominant flag. I also threw in popular tourist destinations and Botany Bay.

![albury-wodonga](https://cloud.githubusercontent.com/assets/16143161/13696842/4694fcc8-e7bd-11e5-88e1-208c4e3dd504.png) Albury-Wodonga
![ballarat](https://cloud.githubusercontent.com/assets/16143161/13665580/51cdaaca-e701-11e5-98d6-f22d36be5a32.png) Ballarat
![botany bay](https://cloud.githubusercontent.com/assets/16143161/13690294/5f0c5a60-e783-11e5-882c-cf85c9fb1a7d.png) Botany Bay
![broome](https://cloud.githubusercontent.com/assets/16143161/13700164/51688bb8-e7d3-11e5-86cb-5ae10e63aa65.png) Broome
![devonport](https://cloud.githubusercontent.com/assets/16143161/13695840/5ab984f0-e7b6-11e5-88b4-684f67bdfefb.png) Devonport
![fremantle](https://cloud.githubusercontent.com/assets/16143161/13700473/256e5766-e7d5-11e5-9a60-2b121d53a4cb.png) Fremantle
![greater melbourne](https://cloud.githubusercontent.com/assets/16143161/13665571/48354e50-e701-11e5-967f-d7961236fb45.png) Greater Melbourne
![greater sydney](https://cloud.githubusercontent.com/assets/16143161/13665574/4b72c89a-e701-11e5-8d27-0774ee26d4f4.png) Greater Sydney
![liverpool](https://cloud.githubusercontent.com/assets/16143161/13690311/7a171ebc-e783-11e5-9571-ff55b3ed36b9.png) Liverpool
![mackay](https://cloud.githubusercontent.com/assets/16143161/13698193/b23fe34e-e7c6-11e5-9ac5-a4004ef8e443.png) Mackay
![melbourne](https://cloud.githubusercontent.com/assets/16143161/13666231/94fb9110-e704-11e5-8b69-c0f82ca9b4f1.png) Melbourne (v2: less pixely and shitty looking, crown is more than one pixel now)
![mornington peninsula](https://cloud.githubusercontent.com/assets/16143161/13690340/947f1a48-e783-11e5-8418-495927686949.png) Mornington Peninsula
![mount gambier](https://cloud.githubusercontent.com/assets/16143161/13687140/b26e10e2-e76d-11e5-81ab-16bb6419f388.png) Mount Gambier
![parramatta](https://cloud.githubusercontent.com/assets/16143161/13696143/83f0324a-e7b8-11e5-876f-4c281ad181bd.png) Parramatta
![port hedland](https://cloud.githubusercontent.com/assets/16143161/13698439/317121ae-e7c8-11e5-9a1f-d62220bd51e4.png) Port Hedland
![rockhampton](https://cloud.githubusercontent.com/assets/16143161/13698201/bbc0c0c8-e7c6-11e5-8cb8-dc06788aa862.png) Rockhampton
![surf coast](https://cloud.githubusercontent.com/assets/16143161/13695915/033ecbb2-e7b7-11e5-8bea-98bd89042983.png) Surf Coast

Zipped and renamed here ([autismflags.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/168924/autismflags.zip))

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks, they're added.
