### ISSUE TITLE
United Kingdom 

### ISSUE THREAD

**Issue by LenticCatachresis** [flaghunters/Extra-Flags-for-4chan#113]
A bunch of regions and counties including the correct flags for Norfolk and Cambridgeshire:

https://mega.nz/#!DNtkiA4R!N0gSJ9i1gK7vUscndJLzoOva4wyqG4eHQIgc9w_ogGc

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks, they're added.
