### ISSUE TITLE
Washington State Flags

### ISSUE THREAD

**Issue by Abtolai** [flaghunters/Extra-Flags-for-4chan#114]
This is a grouping of some of the larger and more important cities of Washington, 
Puyallup ![puyallup](https://cloud.githubusercontent.com/assets/17794542/13721559/fefc67f2-e7df-11e5-8749-80108d9c7608.png)
Yakima ![yakima](https://cloud.githubusercontent.com/assets/17794542/13721560/091f8818-e7e0-11e5-82b1-aa39342824ed.png)
Bellevue ![bellevue](https://cloud.githubusercontent.com/assets/17794542/13721562/1263f116-e7e0-11e5-9472-f2e71a4e6537.png)
Vancouver ![vancouver](https://cloud.githubusercontent.com/assets/17794542/13721564/1c25d124-e7e0-11e5-95a5-f1b46050ca4b.png)
Spokane ![spokane](https://cloud.githubusercontent.com/assets/17794542/13721565/249238fc-e7e0-11e5-9bf6-a8924891d764.png)
Tacoma ![tacoma](https://cloud.githubusercontent.com/assets/17794542/13721566/2a3ccdc6-e7e0-11e5-95ef-3db908df155a.png)

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks they're in.
If you have multiple flags, could you zip them up and post them on mediafire or mega next time?
Saves me quite some time.
