### ISSUE TITLE
Schandleria Flag

### ISSUE THREAD

**Issue by Deilweid** [flaghunters/Extra-Flags-for-4chan#116]
Ayy, I was wondering if my """"autonomous"""" thing's flag could be put in?

It's in the United States, so I guess you could put it there.

![schandleria](https://cloud.githubusercontent.com/assets/17951336/13899906/c3041bdc-edcf-11e5-83ba-6f76e205ad32.png)

**Comment by Thsar999** [comment]
Nobody gives a shit about your micronation and you're not autonomous
autistic fuck

**Comment by Deilweid** [comment]
That's why I put four sets of quotation marks. :---DDDD

**Comment by LenticCatachresis** [comment]
ABSOLUTELY
SAVAGE

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Sorry lad, no meme flags.
