### ISSUE TITLE
North Dakota City Flags

### ISSUE THREAD

**Issue by Abtolai** [flaghunters/Extra-Flags-for-4chan#117]
Here are the two prominent North Dakota Cities Flags
Included are Bismarck and Grand Forks 
https://mega.nz/#!DIEX1bCL!BVC506TtbxFooX-qE1wBkcaU_Akl94jyb2CAu8kPzBE

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks, they're in.
