### ISSUE TITLE
Guernsey & Jersey

### ISSUE THREAD

**Issue by u01hr4** [flaghunters/Extra-Flags-for-4chan#118]
Hello hello, got some nice new regional flags for Guernsey & Jersey. Hopefully the link + RAR works.

https://mega.nz/#!WEpAxZSA!E3Mgu3J4Naf2ewAktbecjDeAjGmBoizBcvO-tgu5SFU

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Dats a lot of flags for those tiny islands.
Hope you're not memeing me.

They're in, thanks.
