### ISSUE TITLE
Preston, UK city flag

### ISSUE THREAD

**Issue by Anonymous7432** [flaghunters/Extra-Flags-for-4chan#122]
Please add

Preston city flag:

![preston](https://cloud.githubusercontent.com/assets/18105912/14068427/620597ea-f47b-11e5-8efb-2c8d56070acf.png)

**Comment by Anonymous7432** [comment]
Updated pic, added a gloss:

![preston2](https://cloud.githubusercontent.com/assets/18105912/14093147/b63436f0-f543-11e5-960c-eab1e5340426.png)

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks, it's in.
