### ISSUE TITLE
UK provincial flags

### ISSUE THREAD

**Issue by Anonymous7432** [flaghunters/Extra-Flags-for-4chan#123]
Provincial flags for United Kingdom. All registered recently by the UK Flag Institute

Wessex 
![wessex1](https://cloud.githubusercontent.com/assets/18105912/14093928/981e46aa-f549-11e5-99b2-b4a4d78c29b0.png)

Mercia
![mercia1](https://cloud.githubusercontent.com/assets/18105912/14093946/c3bc1d0a-f549-11e5-80d7-a78948023a7b.png)

Northumbria
![northumbria1](https://cloud.githubusercontent.com/assets/18105912/14093938/b723bf8a-f549-11e5-9177-65d4d9319718.png)

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks, they're in.
