### ISSUE TITLE
More Japanese flags

### ISSUE THREAD

**Issue by c933103** [flaghunters/Extra-Flags-for-4chan#124]
1. Go by the number of files appear under Japan directory, if I counted correctly, not all province-equivalent have their own flag in the list. List of flag can be found in: https://ja.wikipedia.org/wiki/都道府県旗 (It also have a Saharin flag when it was under Japan's rule)
2. Link to list of city/town flags http://www.crwflags.com/fotw/flags/jp-city.html

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Someone has to make them in 16x11 format.

**Comment by karakalpak** [comment]
I've made flags for all 47 prefectures and the 20 largest cities other than Tokyo in #231; I'll continue to make smaller cities when I have time.
