### ISSUE TITLE
[Suggestion] Use single-chinese-character abbreviation as image for different Chinese province 

### ISSUE THREAD

**Issue by c933103** [flaghunters/Extra-Flags-for-4chan#125]
As Chinese government seems to banned creation and usage of local flags

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
It's fine with me, China has some flags though.

**Comment by spurdo-sparde** [comment]
Given a limit of 11x11 px, it's pretty difficult.

**Comment by Grindviking** [comment]
Good luck with fitting Biangbiang into 11x16 pixels

**Comment by spurdo-sparde** [comment]
@Grindviking Pffft lol, probably would just be a giant hunk of differently shaded pixels.

**Comment by c933103** [comment]
Some older bitmap fonts would omit some strokes in lower resolution which should be helpful in this case

**Comment by karakalpak** [comment]
Need the Hainan flag (deleted the old one as it's the flag of the Li Miao). After that this can be closed

**Comment by karakalpak** [comment]
Many provinces of China have logos. I've made flags for what I can get but there are still a few that can be extracted from pictures.
