### ISSUE TITLE
flag almere

### ISSUE THREAD

**Issue by appelsapkoning** [flaghunters/Extra-Flags-for-4chan#126]
I noticed the flag of my city was not yet here so im requesting the flag to be added

![almere_vlag svg](https://cloud.githubusercontent.com/assets/18154708/14127939/359433ea-f61c-11e5-9672-45fa62f683be.png)

looks like pic related, thanks

**Comment by appelsapkoning** [comment]
![almere](https://cloud.githubusercontent.com/assets/18154708/14128029/2ae9bd60-f61d-11e5-9041-64e32e68b7b3.png)

I dont know if this is good for adding I just made the image 11x16 like all the other flags

**Comment by u01hr4** [comment]
Sorry to steal your thunder, but here's a version with the tempates added, too.

![almere](https://cloud.githubusercontent.com/assets/17348704/14128778/e3e240be-f61b-11e5-94ff-0efaaac0d527.png)

**Comment by appelsapkoning** [comment]
thanks that one looks nice,do u know when is it gonna be added in the script?

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks lads, it's in.
