### ISSUE TITLE
Balkan countries completed

### ISSUE THREAD

**Issue by u01hr4** [flaghunters/Extra-Flags-for-4chan#127]
Hello, thought I'd add the missing regions for Bulgaria, Croatia and Greece. Ta!

https://mega.nz/#!DBA22ZYL!rs81fQq6_4PEpgu67jCixeI3UDWEJBQSWPFeFVzd0xo

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks, they're in.
