### ISSUE TITLE
Oegstgeest (netherlands) flag

### ISSUE THREAD

**Issue by Minprez** [flaghunters/Extra-Flags-for-4chan#129]
I see a lot of cities having their own flag, So I was wondering if you would be so kind to add my city as well

tried to create the flag myself, not sure if I fucked up the gloss tho

Original:
![ogroot](https://cloud.githubusercontent.com/assets/18163421/14137898/6efa3028-f66a-11e5-89e2-05f402062b9e.png)

to 16x11 flag:
![oegstgeest](https://cloud.githubusercontent.com/assets/18163421/14137911/7dfbeae4-f66a-11e5-9362-cc31c349143d.png)

with gloss:
![oegstgeest](https://cloud.githubusercontent.com/assets/18163421/14137879/46e55cc0-f66a-11e5-8078-a268b4379d9c.png)

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks, it's in.
