### ISSUE TITLE
UK local flags

### ISSUE THREAD

**Issue by Anonymous7432** [flaghunters/Extra-Flags-for-4chan#130]
Selection of official borough-level flags from the UK Flag Registry:

Portland, Dorset
![portland dorset](https://cloud.githubusercontent.com/assets/18105912/14146928/6051f278-f691-11e5-9760-49c03b896bbf.png)

Wing, Buckinghamshire
![wing buckinghamshire](https://cloud.githubusercontent.com/assets/18105912/14146941/70b0d62a-f691-11e5-9b05-ed7a9ef02bc3.png)

St Anne's on the Sea, Lancashire
![st anne s on the sea lancashire](https://cloud.githubusercontent.com/assets/18105912/14146983/a1538714-f691-11e5-97ab-3ec03a6f8776.png)

Petersfield, Hampshire
![petersfield hampshire](https://cloud.githubusercontent.com/assets/18105912/14147001/b2ce3070-f691-11e5-8f13-826b20051383.png)

Hampton Poyle, Oxfordshire
![hampton poyle oxfordshire](https://cloud.githubusercontent.com/assets/18105912/14147034/c9d72ca4-f691-11e5-8e77-5b44c123a15c.png)

Horningsea, Cambridgeshire
![horningsea cambridgeshire](https://cloud.githubusercontent.com/assets/18105912/14147089/0a49b5cc-f692-11e5-8277-c1bb249f330c.png)

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Can you please zip and upload to a mediafire or mega?

**Comment by Anonymous7432** [comment]
sorry lad I dont know how

**Comment by Anonymous7432** [comment]
Could you add Wing and St Anne's on the Sea?
I have a few other local flags to add, and once I've figured out how to zip them I'll make new issue with the rest included

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Alright lad, Wing and St Anne are in.

**Comment by Anonymous7432** [comment]
Theres something wrong with the St Annes flag; it wont show when posting
Dont really know why; perhaps the apostrophe needs to be removed from the title?

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Renamed it to St Annes on the Sea, could you try again?

**Comment by Anonymous7432** [comment]
yep thanks thats fixed it
guess the issue can be closed now; ill make the new one when i have the rest of the flags sorted
