### ISSUE TITLE
add Hong Kong

### ISSUE THREAD

**Issue by WalrusThunder** [flaghunters/Extra-Flags-for-4chan#131]
Central and West District
![central_and_western_district](https://cloud.githubusercontent.com/assets/13814660/14161023/fd5ee2c4-f6a5-11e5-9a35-fe7c49833de7.png)
Eastern District
![eastern_dsitrict](https://cloud.githubusercontent.com/assets/13814660/14161027/052a8ee0-f6a6-11e5-87c2-2a2e16358972.png)
Islands District
![islands_district](https://cloud.githubusercontent.com/assets/13814660/14161031/0b37ca32-f6a6-11e5-8174-19f672a6c284.png)
Kwai Tsing District
![kwai_tsing_district](https://cloud.githubusercontent.com/assets/13814660/14161040/1569ae6c-f6a6-11e5-8e1c-19db0b4b1027.png)
Kwun Tong District
![kwun_tong_district](https://cloud.githubusercontent.com/assets/13814660/14161044/1bee5a26-f6a6-11e5-8bb4-ffdc8b13aa23.png)
Sai Kung District
![saikung_district](https://cloud.githubusercontent.com/assets/13814660/14161047/23cf0772-f6a6-11e5-8392-198778195aa7.png)
Sha Tin District
![sha_tin_district](https://cloud.githubusercontent.com/assets/13814660/14161093/bc48cdee-f6a6-11e5-9a4c-95234de1f128.png)
Sham Shui Po District
![sham_shui_po_district](https://cloud.githubusercontent.com/assets/13814660/14161101/c48aeb0e-f6a6-11e5-8b3d-aa9f9cb8dd47.png)
Tsue Wan District
![tsuenwan_district](https://cloud.githubusercontent.com/assets/13814660/14161106/ce8a3b64-f6a6-11e5-9b61-8e08358d59dd.png)
Tuen Mun District
![tuen_mun_district](https://cloud.githubusercontent.com/assets/13814660/14161109/d49746a0-f6a6-11e5-9483-25781daf3ad2.png)
Wan Chai District
![wan_chai_district](https://cloud.githubusercontent.com/assets/13814660/14161116/dba17ed4-f6a6-11e5-8997-4ac588c583bf.png)
Wong Tai Sin District
![wong_tai_sin_district](https://cloud.githubusercontent.com/assets/13814660/14161121/e42284f4-f6a6-11e5-99bc-d2a3c5bb9023.png)
Yau Tsim Mong District
![yau_tsim_mong_district](https://cloud.githubusercontent.com/assets/13814660/14161127/f0e7a728-f6a6-11e5-8acd-19716770d117.png)
Yuen Long District
![yuen_long_district](https://cloud.githubusercontent.com/assets/13814660/14161132/f9e08142-f6a6-11e5-80d7-210920b1e061.png)
Kowloon City District
![kowloon_city_district](https://cloud.githubusercontent.com/assets/13814660/14161141/07c80e42-f6a7-11e5-86e0-9c350fbef9a3.png)
Triad
![triad](https://cloud.githubusercontent.com/assets/13814660/14161145/0c03c866-f6a7-11e5-8cfa-1dfec2f488db.png)

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Can you please zip and upload to a mediafire or mega?

**Comment by WalrusThunder** [comment]
http://www.mediafire.com/download/6q32ubvswws4cny/Hong_Kong.zip

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks fam, they're in.
