### ISSUE TITLE
Add United Arab Emirates

### ISSUE THREAD

**Issue by WalrusThunder** [flaghunters/Extra-Flags-for-4chan#133]
Abu Dhabi
![abu_dhabi](https://cloud.githubusercontent.com/assets/13814660/14195037/69280d9e-f77a-11e5-9e55-5b5065f7d843.png)
Ajman
![ajman](https://cloud.githubusercontent.com/assets/13814660/14195038/6c04a7e8-f77a-11e5-8ff6-0c88a1827db9.png)
Dubai
![dubai](https://cloud.githubusercontent.com/assets/13814660/14195039/6f296580-f77a-11e5-99be-5c82f8a6529e.png)
Fijairah
![fujairah](https://cloud.githubusercontent.com/assets/13814660/14195042/75f7a912-f77a-11e5-96d2-a589db454ecc.png)
Ras Al-Khaimah
![ras_al-khaimah](https://cloud.githubusercontent.com/assets/13814660/14195050/8523d906-f77a-11e5-8f8d-2b7052493fdc.png)
Sharjah
![sharjah](https://cloud.githubusercontent.com/assets/13814660/14195053/88c44406-f77a-11e5-873f-0b5f58749f55.png)
Umm Al-Qaiwan
![umm_al-qaiwan](https://cloud.githubusercontent.com/assets/13814660/14195055/9020208a-f77a-11e5-86b0-6669e77581c2.png)
zip
http://www.mediafire.com/download/1mrcvh1w19xn1it/United_Arab_Emirates.zip

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks, they're in.
