### ISSUE TITLE
Add Flags of the Waddeneilanden

### ISSUE THREAD

**Issue by RadicalBean** [flaghunters/Extra-Flags-for-4chan#134]
Texel
![texel](https://cloud.githubusercontent.com/assets/18211468/14204782/df4af982-f806-11e5-8817-ac0a4e19a852.png)
Vlieland
![vlieland](https://cloud.githubusercontent.com/assets/18211468/14204815/01273714-f807-11e5-965e-323fa02b6ac2.png)
Terschelling
![terschelling](https://cloud.githubusercontent.com/assets/18211468/14204817/090e355e-f807-11e5-903c-eacb22189542.png)
Ameland
![ameland](https://cloud.githubusercontent.com/assets/18211468/14204825/1170a6e6-f807-11e5-8b36-39c63d0f63e4.png)
Schiermonnikoog
![schiermonnikoog](https://cloud.githubusercontent.com/assets/18211468/14204828/1b4494ca-f807-11e5-8759-d91b921c0459.png)

Link:
http://www.mediafire.com/download/650ht8cyn6g0fpn/Waddeneilanden.rar

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks, they're in.
