### ISSUE TITLE
Dortmund, Germany

### ISSUE THREAD

**Issue by rogan29** [flaghunters/Extra-Flags-for-4chan#135]
![dortmund](https://cloud.githubusercontent.com/assets/18214607/14209378/32ef46f2-f824-11e5-87cd-b94cd64751ee.png)

https://mega.nz/#!i0BkWLAS!FxFDBQGyUwZpkY3ZtzHoOfPZvd4NjqCmCP-VkfZnV7E

Dortmund, Germany (not done by me).

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks, it's in.
