### ISSUE TITLE
District flags of Czech Republic

### ISSUE THREAD

**Issue by Szominis** [flaghunters/Extra-Flags-for-4chan#144]
So far, there were only flags for 14 czech regions, I decided to make flags for 76 districts of Czech Republic. I only decided to ommit regions Praha-východ, Praha-západ, Brno-venkov, Plzeň-sever and Plzeň-jih, because they do not have any official flag, because their seat is their city (Praha, Brno and Plzeň respectively) so they basically share the same flag.
[Okresy.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/201478/Okresy.zip)

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks lad, they're in.
There were a couple of flags in the zip which were already in the flag folder, I did not replace them but some seemed to be different, could you maybe check which ones should be used?

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
No answer after 3 weeks, if something is not okay yet, open a new issue.
