### ISSUE TITLE
Add Urban/Rural Districts Germany

### ISSUE THREAD

**Issue by Malte-Soeren** [flaghunters/Extra-Flags-for-4chan#146]
http://www.mediafire.com/download/3gylpsz89qb33g1/Landkreise-Niederbayern.zip
http://www.mediafire.com/download/3jf6nhss5jqin3x/Landkreise-Oberpfalz.zip
More german districts. There are really much (402) of them, how often should I submit them? Or is it okay if I make a new Issue every day ?
Also the ä ö ü and ß characters in the added district names are replaced with a o u and a. ß is replaced with ss if necessary, could you please correct that? The following districts are affected:
Haßberge
Weißenburg-Gunzenhausen

**Comment by Malte-Soeren** [comment]
http://www.mediafire.com/download/zo14mih7djrs19g/Landkreise-Oberbayern.zip
last rural/urban districts of Bayern, now this federal state is finished

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks lad, they're in. You can submit as often as you want, although I prefer as much of them together so I don't have to add them too often.
I can leave this issue open for you if you want.

Have to rename special characters to make sure they are compatible with all browsers, scharfes s was probably renamed to a because my file browser does not understand it.

**Comment by Malte-Soeren** [comment]
I renamed a lot of the districts because of some urban and rural districts having the same name and me wanting to have a consistent nomenclature with the districts added by rogan29 (I used your glossed versions for that):
http://www.mediafire.com/download/k3hq3gwd5n3qv97/Landkreise-Bayern.zip
Also I made new flags for the neighbouring federal state:
http://www.mediafire.com/download/za6ibd5c9t6lzeo/Landkreise-Baden-Wurttemberg.zip
They're already glossed (template 3) and I did not use any ä ö ü ß

**Comment by Malte-Soeren** [comment]
Another federal state:
http://www.mediafire.com/download/mbeysp3d4xh581a/Landkreise-Sachsen-Anhalt.zip

**Comment by Malte-Soeren** [comment]
http://www.mediafire.com/download/g0go8ectt1ir5ze/Landkreise-Thuringen.zip

**Comment by Malte-Soeren** [comment]
One more federal state
http://www.mediafire.com/download/hzdg8vapvegdhvf/Landkreise-Sachsen.zip

It seems like you have forgotten my flags when adding all the other flags yesterday, can you please add them? Also the renaming three posts above affects all the districts that were lastly changed in the commit "gloss germany" and no others.

**Comment by sdjklag** [comment]
What exactly did you rename? I just added all your flags for now, should I remove some?

**Comment by Malte-Soeren** [comment]
I renamed all the flags of bavarian districts. (should be 96 if you didn't overwrite any)
Those were lastly changed with a commit named "gloss germany".
And yes, you should remove the old ones, as there are now nearly one hundred districts with two flags.
https://de.wikipedia.org/wiki/Liste_der_Landkreise_und_kreisfreien_St%C3%A4dte_in_Bayern
Here's a complete list of all. I basically just put "Landkreis" in to the rural districts and removed "Stadt" from the free cities to match the way rogan29 named the flags he made.
Also the district Lindau has been omitted because it does not have an official flag, so it really is 96 and not 97 flags.

**Comment by sdjklag** [comment]
I removed all the duplicate districts, the ones without Landkreis, and all the files starting with Stadt, but for some cities (Amberg Erlangen Ingolstadt Kaufberen Kempten Memmingen Nurnberg Schwabach Straubing Weiden) there were no Stadt duplicates, are you sure you actually renamed 96 flags?

**Comment by sdjklag** [comment]
Anyway I think it would be better if there was only one issue about Germany flags (there's currently this one and #150), maybe marked with a label, so that all the people working on them could keep themselves up to date, discuss about conventions, who is working on what, etc. The same goes for the other countries. What do you think @WhatIsThisImNotGoodWithComputers?

**Comment by Malte-Soeren** [comment]
No, I did not rename all 96 districts because I put Stadt only in front of those cities that shared their name with a rural districts, so you did good by not deleting those with no stadt duplicate.
On the other hand you deleted 15 files too much because they were actually meant to be duplicates (one for the city and one for the neighbouring district), which were those stadt ones
they should just have the stadt removed (Ansbach, Aschaffenburg, Augsburg, Bamberg, Bayreuth, Coburg, Furth, Hof, Landshut, Munchen, Passau, Regensburg, Rosenheim, Schweinfurt, Wurzburg)
Here are the files in case you don't have them anymore
![ansbach](https://cloud.githubusercontent.com/assets/18237244/14753966/e365ee0e-08d8-11e6-9caf-1b48f5dea003.png)
![aschaffenburg](https://cloud.githubusercontent.com/assets/18237244/14753967/e36fbeca-08d8-11e6-924d-5c8f0efa6a43.png)
![augsburg](https://cloud.githubusercontent.com/assets/18237244/14753968/e370b4ce-08d8-11e6-82ea-bc7d2cd0cfa6.png)
![bamberg](https://cloud.githubusercontent.com/assets/18237244/14753969/e370d422-08d8-11e6-8b86-bca07da2176a.png)
![bayreuth](https://cloud.githubusercontent.com/assets/18237244/14753970/e3745106-08d8-11e6-9634-c775f328a52d.png)
![coburg](https://cloud.githubusercontent.com/assets/18237244/14753971/e3766a04-08d8-11e6-84a7-3710b72d9474.png)
![furth](https://cloud.githubusercontent.com/assets/18237244/14753972/e3801bb2-08d8-11e6-847a-1e6730fff029.png)
![hof](https://cloud.githubusercontent.com/assets/18237244/14753973/e391c0ba-08d8-11e6-87a9-7853127e84d5.png)
![landshut](https://cloud.githubusercontent.com/assets/18237244/14753976/e394f852-08d8-11e6-8e41-80777a6efedf.png)
![munchen](https://cloud.githubusercontent.com/assets/18237244/14753974/e393a718-08d8-11e6-81fa-b0e1c60f8881.png)
![passau](https://cloud.githubusercontent.com/assets/18237244/14753975/e394de30-08d8-11e6-87e1-14c796f85b3d.png)
![regensburg](https://cloud.githubusercontent.com/assets/18237244/14753978/e39813a2-08d8-11e6-9bb0-1b361635896c.png)
![rosenheim](https://cloud.githubusercontent.com/assets/18237244/14753977/e396d9c4-08d8-11e6-9bb7-8ea9d1d6cbdc.png)
![schweinfurt](https://cloud.githubusercontent.com/assets/18237244/14753979/e3a95694-08d8-11e6-97d3-19c9aaeab9cb.png)
![wurzburg](https://cloud.githubusercontent.com/assets/18237244/14753980/e3aa93c4-08d8-11e6-85bb-d6d645bb4798.png)

I see München and Regensburg have now been added by twelvetwelve, don't replace them with mine, they look better.
And sure, I can move to #150 , just close this issue.

**Comment by sdjklag** [comment]
I recovered the flags, now it should be okay.
