### ISSUE TITLE
New Flag for Lageso in Germany

### ISSUE THREAD

**Issue by halfjewprussian** [flaghunters/Extra-Flags-for-4chan#148]
![heimat](https://cloud.githubusercontent.com/assets/18295710/14299769/a57a120e-fb8c-11e5-923d-f23c291b2b86.png)

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
I can only accept flags which are exactly 16x11 pixels, preferably glossed.

**Comment by halfjewprussian** [comment]
Apparently, Gimp won't let me do it. I'm not too experienced in those manners anyway, so I'll just scrap it. But thanks for your effort. You've done a great favour to /int/, /pol/ and /sp/

Weltrerusten

**Comment by Anonymous7432** [comment]
i can probably make the flag for you but where is Lageso?

searching it on google only leads to this
https://www.berlin.de/lageso/
