### ISSUE TITLE
German districts

### ISSUE THREAD

**Issue by rogan29** [flaghunters/Extra-Flags-for-4chan#150]
I made some for Nordrhein-Westfalen, Germany.

https://mega.nz/#!akxQWKyA!0VTpqdh-qNH9agrXkLCctrFOVskofAKBtTcF8qwrjw8

**Comment by rogan29** [comment]
Kreises Aachen is supposed to mean Kreis Aachen.

**Comment by Malte-Soeren** [comment]
Thanks lad for helping me with those districts. Are you planning to do more ? If so, please tell me which so I don't make the same ones and waste my time. I am currently making Baden-Württemberg.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks, they're in.

**Comment by rogan29** [comment]
>Thanks lad for helping me with those districts. Are you planning to do more ? If so, please tell me which so I don't make the same ones and waste my time. I am currently making Baden-Württemberg.
Yes, I will make every Landkreis which isn't properly glossed (I'll remake the previously submitted one).

**Comment by rogan29** [comment]
>I am currently making Baden-Württemberg.
From where do you get the flags that are not on Wikipedia?

**Comment by rogan29** [comment]
>Yes, I will make every district and independent city

Ok, that was stupid, but here are some.

https://mega.nz/#!C1QmVSaS!2DKC3GYy4yfgp9ytBcy80V8pjnFeV6tioo3StZ8pMQI

**Comment by sdjklag** [comment]
Added the new ones (no meme flags please)

**Comment by Malte-Soeren** [comment]
I noticed some mistakes after updating my master folder:
Rhein-Kreis Neuss is there two times because one of them is misspelled as Rhein-Kreises Neuss.
Frankfurt is also there two times one time as Frankfurt am Main (added now) and one time just as Frankfurt (added by someone else quite some time ago).

**Comment by sdjklag** [comment]
Fixed everything

**Comment by Malte-Soeren** [comment]
I'm sorry to annoy you again but I found two more mistakes:
Worm -> Worms
Zweibrucke -> Zweibrucken
This time I checked all flags so I think that's all.

**Comment by rogan29** [comment]
here are some municipalities, this time with extra less memes

https://mega.nz/#!74BiUIxa!d2X31XQVXKCw0V_bamLGbwItB0J4FjKWvcW_bLSATyM

**Comment by twelvetwelve** [comment]
Regensburg

https://mega.nz/#!vkln1I5Q

Munich

https://mega.nz/#!6hFgGa7K

**Comment by twelvetwelve** [comment]
Regensburg

https://mega.nz/#!vkln1I5Q!EGDbDSrGGcKn8g2VjCS2fSXOxBkCxS43LclSOJrPaMI

Munich

https://mega.nz/#!6hFgGa7K!OAZVdPUycoqmboRDSTFxg3frV3xGNXOTf63tH7xPtyc

**Comment by Malte-Soeren** [comment]
The ones you recovered were the wrong ones (you added the districts again but what you deleted were the cities)
look at my post in to see which ones i meant

**Comment by sdjklag** [comment]
Now?

**Comment by Malte-Soeren** [comment]
yes, thank you for your patience.

**Comment by rogan29** [comment]
There are two Munich flags now. One is called "Munchen" which is I think made of the vertical version of the flag. But this is inconsistent to the other flags, so I would only keep the "Munich" flag and rename it to Munchen.

http://www.flaggen-server.de/dland1/muenchen.php

**Comment by Malte-Soeren** [comment]
http://www.mediafire.com/download/d12hdzlag4pi4n4/Landkreise-Niedersachsen.zip
Made the districts of the last federal state completely missing. Finally switched to GIMP so they actually look good.
Now it's just a few left. 
Lads, do you think I should remake the ugly ones I made?

**Comment by Malte-Soeren** [comment]
Good news, I finally finished all the districts, these are the last ones:
http://www.mediafire.com/download/1a33xbra60fbqav/restliche-Landkreise.zip
However, I was not able to find a flag for five districts, so I just used the coat of arms:
http://www.mediafire.com/download/7vto5ao5be7dd44/Coats-background.zip
http://www.mediafire.com/download/ks9ao9yxzx1rrcm/Coats-transparent.zip
One time with a white background, the other time with a transparent one. Add which one is better in your opinion, or none if you don't allow coats of arms

**Comment by sdjklag** [comment]
I'll add the coats with the background for consistency, I've seen other flags like these

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
@Malte-Soeren 
>Good news, I finally finished all the districts, these are the last ones:
Can this issue be closed?

**Comment by Malte-Soeren** [comment]
> Can this issue be closed?

Not yet, I will remake some older district flags that don't look good.
http://www.mediafire.com/download/yc3e0xv9agputut/Landkreis-Sachsen-Anhalt.zip
First part (of five)
If any flag in this does not replace an older one, it has a typo in it.

**Comment by Malte-Soeren** [comment]
second part:
http://www.mediafire.com/download/2k7eo975wmldd3z/Landkreise-Baden-Wurttemberg.zip

**Comment by Malte-Soeren** [comment]
part 3&4:
http://www.mediafire.com/download/o4qcoa2n09ewohu/Sachsen.zip
http://www.mediafire.com/download/7g2gwkyuw9nz78s/Thuringen.zip

I will also make the folders for the german regionals once I finished this rework

**Comment by Malte-Soeren** [comment]
Last part of the rework, you can close this issue after you replaced these:
http://www.mediafire.com/download/j3kct8vmo471k5y/Bayern.zip
I will make cascading folders for the german flags tomorrow
