### ISSUE TITLE
Provincial flags UK removal

### ISSUE THREAD

**Issue by Anonymous7432** [flaghunters/Extra-Flags-for-4chan#153]
I noticed that three of the provincial flags for UK (Wessex, Mercia, Northumbria) have been removed for being "historical".

While 5 years ago this would be correct, that is no longer the case. All were recently registered by the UK Flag Institute (Wessex:2011, Mercia:2014, Northumbria:2015).

Before being added to the Flag Registry they were indeed no more than "historical" flags and not suited for use in an official capacity. However, since being registered they can now be formally used to represent their respective geographical regions. Hence their unique description as 'Provincial' flags, as seen on the Flag Institute catalogue: http://www.flaginstitute.org/wp/flag-registry/?flagtype=County+Flag

In light of this hopefully you can reconsider.
Wessex
![wessex1](https://cloud.githubusercontent.com/assets/18105912/14405800/1f6c4614-fe8e-11e5-882f-b64486d1fdd5.png)

Mercia
![mercia1](https://cloud.githubusercontent.com/assets/18105912/14405803/296e621e-fe8e-11e5-8c3f-5e7bc7fc6d29.png)

Northumbria
![northumbria1](https://cloud.githubusercontent.com/assets/18105912/14405805/31a81844-fe8e-11e5-86ec-bf1267c66261.png)

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
So I'm no flag expert, but someone said they were historic flags and it checked out with Wikipedia.
On the page you linked I'm not seeing they are current active or reactivated.
What does being registered by the UK Flag Institute mean?
Would any official institute within any of those three regions actually fly these flags?

**Comment by Anonymous7432** [comment]
The UK government doesn't keep a formal record of flags; thats the responsibility of the Flag Institute. Any flag that hasn't been registered by them is either historic or unofficial. All flags that have been registered are available for formal use, so they would certainly be considered 'active'.

Since these are new additions, they admittedly aren't in widespread use at present. However, local authorities do use them, for instance Tamworth for Mercia https://britishcountyflags.wordpress.com/2013/04/08/mercia-flag/, plus the Wessex flag is also increasingly being used in official functions https://britishcountyflags.wordpress.com/2013/09/20/wessex-flag/. I'm not at present aware of the Northumbria flag being in use yet, but that's hardly surprising considering it was only registered last year.

Now that they have been formally recognized inhabitants and local authorities of those geographic regions (which correspond roughly to Northumbria: Northern England, Mercia:West and Midlands, Wessex: South) can use them officially. As a result there's no reason why they shouldn't be added here. They used to be historic/non-active but that's no longer the case.

**Comment by Anonymous7432** [comment]
If you do reconsider I've updated the flags by adding the new gloss:

Northumbria
![northumbria](https://cloud.githubusercontent.com/assets/18105912/14407019/f2a1dd14-feb1-11e5-8493-3945662301b5.png)

Wessex
![wessex](https://cloud.githubusercontent.com/assets/18105912/14407021/fa083792-feb1-11e5-9c79-885aced95767.png)

Mercia
![mercia](https://cloud.githubusercontent.com/assets/18105912/14407025/02f7ac66-feb2-11e5-8108-dd76da00c526.png)

**Comment by rogan29** [comment]
it's not like any historical flag is less valid than regions like moon and outer space anyway.

**Comment by Anonymous7432** [comment]
Had a look at the thread; no they aren't official administrative divisions.

However, these flags are not "historical", not any more. Mercia, Northumbria and Wessex may not be NUTS 2 regions like East Anglia, but they are now formally recognised as geographical regions. 

To use the example of Wessex, before the flag was registered in 2011 you would not be allowed to fly it officially, and technically you would be obligated to remove it if asked. However, now if you live in one of the counties which comprises Wessex and you want to fly its flag, you're legally allowed to do so. This applies to Mercia and Northumbria also. To quote the 2012 flag-flying legislation:
“…..do not need planning permission to include the [registered] flag of any island, county, district, borough, burgh, parish, city, town or village within the UK, as well as the flags of the Black Country, East Anglia, Wessex, any part of Lincolnshire, any Riding of Yorkshire or any historic county..”

Its understandable why people may consider them "memeflags" as they're unfamiliar. But just because they've only been registered recently doesn't make them any less valid.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Will reinstate, this document backs up your claims.

https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/15438/flying_flags_guide.pdf

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks for your clarification and patience lad.
