### ISSUE TITLE
Looking for flag manager

### ISSUE THREAD

**Issue by WhatIsThisImNotGoodWithComputers** [flaghunters/Extra-Flags-for-4chan#161]
Requirements: 
- need to know how to use git

**Comment by sdjklag** [comment]
Here

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
@sdjklag Sent you an invite, please be gentle. You just need to add flags to the folders of countries and add the names to the flag list text file in php folder. If you're on Linux or OS X you can use the script generate_flags or something like that to generate the file for you.

Thanks for helping out.
