### ISSUE TITLE
West Yorkshire

### ISSUE THREAD

**Issue by u01hr4** [flaghunters/Extra-Flags-for-4chan#165]
Sorry for all these flags on your hols, adding West Yorkshire to the UK since it doesn't have a current flag yet, only some historical meme one.

![west yorkshire](https://cloud.githubusercontent.com/assets/17348704/14585132/063805d8-0461-11e6-9a60-38c39f2913d9.png)

**Comment by Anonymous7432** [comment]
Not trying to be a dick, but West Riding does have a registered flag; the one posted above isn't valid
http://www.flaginstitute.org/wp/flags/yorkshire_west-riding/
Was recently designed and added to the Registry in 2013

**Comment by u01hr4** [comment]
Don't worry, I knew about West Riding's flag. The trouble is, West Riding hasn't officially been in use for 40 odd years. The currently used county 'West Yorkshire' doesn't have a flag in the system. As it turns out, I found the proper flag they use now anyways, here it is:

![west yorkshire](https://cloud.githubusercontent.com/assets/17348704/14686148/7198dc96-072f-11e6-9a19-23186c552568.png)

**Comment by Anonymous7432** [comment]
Understood assumed you were referring to West Riding.
That being said, the flag you've posted there isn't correct; its a runner up from the competition to create a West Riding flag (which indeed was based upon the obsolete West Yorkshire county council coat of arms). 
https://yorkshireboundarysociety.wordpress.com/2013/03/27/west-riding-flag-finalists-voting-commences/
https://en.wikipedia.org/wiki/Coat_of_arms_of_West_Yorkshire
The West Yorkshire county doesn't currently have a flag, however, West Riding can be used for that purpose. It may no longer be an administrative division but its a formally recognised region; hence the presence of its flags in the Flag Registry

**Comment by u01hr4** [comment]
How could wikipedia lie to me :^)

**Comment by Anonymous7432** [comment]
Must admit its weird that a county doesnt even have a coat of arms
But if you want something specific to the region you could perhaps make some city flags, like maybe Leeds for example; up to you

**Comment by u01hr4** [comment]
Tried a 3rd flag based on the West Yorkshire Combined Authority (best equivalent to a proper council) seems to be the only thing remotely close to an official West Yorkshire flag/logo/crest/anything. Would be nice to have all of the 1st level regions of England represented, guess PK/Sicily can add a flag if they feel it's pertinent.

![west yorkshire](https://cloud.githubusercontent.com/assets/17348704/14727320/95f0d4b6-0821-11e6-89da-94876682025a.png)

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
What's the final verdict?

**Comment by u01hr4** [comment]
Not sure tbh. I'd say get rid of 'West Riding of Yorkshire' though, since it's not existed for 40 years. Since some of the other UK metropolitan counties (Merseyside, Greater Manchester etc) use unofficial (not in the flag registry), probably best to use West Yorkshire's unofficial one too.

Might not be mega official, but at least it'd be a similar situation to a lot of other flags in the system, plus it's based on the old West Yorkshire council CoA, so it's not as if it's some random design.

https://cloud.githubusercontent.com/assets/17348704/14686148/7198dc96-072f-11e6-9a19-23186c552568.png

**Comment by Anonymous7432** [comment]
Only thing I have to say is don't delete West Riding (see legislation from provincial flags issue)
Plus I've seen at least 2 posters using it on a daily basis so its not right to just take their flag. 
Especially as its official and "since it's not existed for 40 years" doesn't apply in this context.

Other than that dont have any real objection to above flag being added if it'll make folk happy, can have both and let posters choose between them; neither is doing any harm

**Comment by spurdo-sparde** [comment]
Committed in 03fee0b.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
There currently are three (four if you include West Riding of Yorkshire) flags for West Yorkshire
- West Yorkshire A
- West Yorkshire B
- West Yorkshire Combined Auth

Can we pick one out of the three listed and remove the other two?

**Comment by Anonymous7432** [comment]
In that case I'd say keep West Yorkshire A.
West Yorkshire B is just a crest version of A, so it can be deleted (plus A looks better).
West Yorkshire Combined Authority shouldnt be on there at all. I had a look at the website and it has nothing to do with flags/regional identity, its a government economic development initiative: http://www.westyorks-ca.gov.uk
