### ISSUE TITLE
Flag of Ticino

### ISSUE THREAD

**Issue by yanarai** [flaghunters/Extra-Flags-for-4chan#172]
The flag of Ticino, Switzerland is currently wrong
It should be flipped by 90°, like in:

https://de.wikipedia.org/wiki/Kanton_Tessin#/media/File:Wappen_Tessin_matt.svg

With red one the left and blue on the right

**Comment by Malte-Soeren** [comment]
https://en.wikipedia.org/wiki/Flags_and_arms_of_cantons_of_Switzerland
https://it.wikipedia.org/wiki/Armoriale_dei_cantoni_svizzeri

It actually is correct, what you're referring to is the coat of arms.
Sorry that I didn't respond in the thread so you had to complain here, but my ISP got blocked for whatever reason.
