### ISSUE TITLE
Flags needed to be added

### ISSUE THREAD

**Issue by OPLK** [flaghunters/Extra-Flags-for-4chan#189]
El Salvador is missing the regional flag of Sonsonate (In the future i will probalby be maing more Issuses like this)

**Comment by u01hr4** [comment]
Literally uploading it this second, as well as other ones!

**Comment by OPLK** [comment]
Also Ghana is missing Upper West, Upper East and Northen regional flags not sure if they exist tho

**Comment by OPLK** [comment]
Also Hong Kong i think is missing some regional flags not sure if flags exist for those districts
The New Territories:
North
Tai Po
Hong Kong Islands:
Easternt
Southern

**Comment by OPLK** [comment]
Nicaragua is missing a flag for the Chontales department.
