### ISSUE TITLE
Saint Vincent and the Grenadines

### ISSUE THREAD

**Issue by cummies** [flaghunters/Extra-Flags-for-4chan#193]
regional flag of grenadines parish
the other parishes dont have flags

![grenadines parish](https://cloud.githubusercontent.com/assets/18235923/14803148/1a09a0d8-0b25-11e6-9e3d-62dff21343dd.png)

**Comment by sdjklag** [comment]
Where did you find the flag? [Here](https://flagspot.net/flags/vc-bq.html) it says that the whale is the flag of Bequia

**Comment by cummies** [comment]
@sdjklag 
i found it here
http://1900.ethnia.org/polity.php?ASK_CODE=VC__&ASK_YY=2016&ASK_MM=04&ASK_DD=26&SL=en
