### ISSUE TITLE
Turkey and the Caucasus

### ISSUE THREAD

**Issue by karakalpak** [flaghunters/Extra-Flags-for-4chan#195]
More than 1,000 flags for Turkey, and several for Georgia and Armenia.
The current flags for Turkey are a mess and I'd suggest replacing them (I've ordered mine into provinces and municipalities); as for Georgia and Armenia I glossed them properly and added a couple extras

https://mega.nz/#!tQ10HQ5L!oPqYze06Yy-Cj9C6eZ2ILcsMaoAIyDWZB7SLOCu8PSM

**Comment by sdjklag** [comment]
Great job
