### ISSUE TITLE
Nepal + correction for Ticino, Switzerland

### ISSUE THREAD

**Issue by karakalpak** [flaghunters/Extra-Flags-for-4chan#205]
Glossed the two existing flags for Nepal and added a new one
Also, a Ticino anon was complaining that his flag was rotated wrongly so I fixed it
https://mega.nz/#!tENSAYSA!PcohBFn_n2mN9GqKWDqvIeR6VLwIJktq7n3xgDWHN6s

**Comment by sdjklag** [comment]
Are you sure it's wrong? https://flagspot.net/flags/ch-ti.html

**Comment by karakalpak** [comment]
Well he's said several times it is. Most Swiss flags are based off their shields, and Ticino's flag (the shield rotated by 90 degrees and made into a square) might be rarely used. 

Several other Swiss flags have slightly different flags to their shields too, so I guess if you're after accuracy I'll try to ask a Swiss poster about it.

**Comment by karakalpak** [comment]
>it is a lot more common here and sometimes even hung instead of the normal flag

https://boards.4chan.org/int/thread/58656537#p58676739

**Comment by sdjklag** [comment]
IMHO we should either use the coat of arms or the correct flag, not some fictional flag based on the coat

**Comment by karakalpak** [comment]
Fictional flag? The flag in the link is the coat of arms

**Comment by sdjklag** [comment]
Yeah, and it's not a flag

**Comment by karakalpak** [comment]
Quite a few countries (including mine) have "flags" that are actually logos and arms on a white background, but to be fair most if not all don't have official flags. So at the end of the day I guess it's your choice between the official flag and the more commonly used arms

**Comment by sdjklag** [comment]
> Quite a few countries (including mine) have "flags" that are actually logos and arms on a white background

The flag they want to insert is not the coat of arms on a white background, it's a flag based on it. Lombardia has a flag based on the coat of arms in the extension, but Lombardia doesn't have an official flag, while Ticino does and it's the one the extension already uses.

**Comment by karakalpak** [comment]
>The flag they want to insert is not the coat of arms on a white background, it's a flag based on it
Right, if that's what you mean. I'll tell him if I see him.

**Comment by sdjklag** [comment]
Since Swiss people themselves want the coat one, I changed it.
