### ISSUE TITLE
Problems with Reunion

### ISSUE THREAD

**Issue by WhatIsThisImNotGoodWithComputers** [flaghunters/Extra-Flags-for-4chan#207]
In 140b9d9 I'm seeing two flags with an é in the folder name and two (Saint-Denis and Saint-Paul) with a question mark in the folder name. Seeing this under Linux and Windows, perhaps an encoding issue with two of the files?

I can't push or pull anymore, so please fix or remove it temporarily.

**Comment by sdjklag** [comment]
>flegs/ $ ls R*union
>Saint-Benoit.png  Saint-Denis.png  Saint-Paul.png  Saint-Pierre.png
They're the same folder. I renamed it to "Reunion" for now, but 4chan shows "Réunion". I think the "é" was encoded with ISO 8859-1, which probably wouldn't have matched the 4chan name anyway

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
That's what I thought, I even checked my locales and drive settings. It was all UTF-8, so it's probably some ISO encoding that gave some trouble.
I renamed them back with an é and now the commit 248270c shows all flags with the é and no more questions marks.
Could you try to pull and check if it still works?

**Comment by sdjklag** [comment]
Yes, it works.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Great, thanks.
