### ISSUE TITLE
All Belgian Municipialtes

### ISSUE THREAD

**Issue by RadicalBean** [flaghunters/Extra-Flags-for-4chan#208]
I am very sleepy, any errors just tell me, keep this thread open after adding them as more parts will come soon
http://www.mediafire.com/download/e5e2abbbd1u99p6/BelgiunmPart1.rar

**Comment by Minprez** [comment]
hmm the seemingly random choice of french and dutch names is a bit confusing
for example in the Brussels-folder you choose Uccle over Ukkel, but Vorst over Forest?
maybe change the names to either all french names or dutch names?

list of names can be found here: https://fr.wikipedia.org/wiki/Liste_des_communes_de_la_R%C3%A9gion_de_Bruxelles-Capitale

**Comment by RadicalBean** [comment]
I'll ask PK after he added them

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
When we started we went with names as the regions had them. So Dutch for Dutch regions etc.
But then we got to regions with Slav runes and Asia runes, so we had to add those in English. Now some have regional names and some are English translated.

What is best? I don't know.

Two options:
- All in English
- All according to their most official language, if they are bilingual, pick the majority speakers

**Comment by RadicalBean** [comment]
Dutch for Flemish flags, French for Walloon ones 
And I guess French for brussels too

**Comment by RadicalBean** [comment]
Current status: don't have much time, almost finished with Flanders

**Comment by spurdo-sparde** [comment]
Thanks pham, noted

**Comment by RadicalBean** [comment]
Here's part 2. flanders is done
http://www.mediafire.com/download/ccfmq55sa6sqqgp/BelgiumPart2+%28Flanders+done%29.rar
Now time to start Wallonia where 60% doesn't have a flag, just a coat of arms

**Comment by RadicalBean** [comment]
I need someone from Wallonia to tell me if they use French or Walloon names for their flags

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
As far as I know Walloons speak French and names should be the same.
Is there a difference?

**Comment by RadicalBean** [comment]
Yes, I am fixing it now.
e.g. Charleroi in French, Tchålerwè in Walloon

**Comment by RadicalBean** [comment]
Wallonia is done, and with that all of Belgium, a total of 563 flags in total, it was a fun project
http://www.mediafire.com/download/lc3butscyvt3cat/Wallonie.rar

**Comment by flagzzzz** [comment]
Added through Ikhi's sorted Belgium and Netherlands flags
