### ISSUE TITLE
2 flags for Tunisia and a minor correction

### ISSUE THREAD

**Issue by karakalpak** [flaghunters/Extra-Flags-for-4chan#217]
Sousse
![sousse](https://cloud.githubusercontent.com/assets/17495420/15097667/49f2cbe6-1555-11e6-9057-1fe9553faead.png)
Tunis (removed border and glossed properly)
![tunis](https://cloud.githubusercontent.com/assets/17495420/15097669/5140ea54-1555-11e6-9a6c-22307757232c.png)

There's also two flags for North-West in South Africa, one should be removed. Thanks pham

**Comment by spurdo-sparde** [comment]
Commited in 81fd555 (check 'em) and 11d5cc99 (check 'em, holy fuck)
