### ISSUE TITLE
Latvia regions

### ISSUE THREAD

**Issue by u01hr4** [flaghunters/Extra-Flags-for-4chan#218]
Hi, here's flags for Latvia's regions. thanks.

https://mega.nz/#!jZYB0RbY!fQ_UvIqhZ5M1DI0RZtVIGFqMcPWxV9SmLxtxCx0c9ZY

**Comment by spurdo-sparde** [comment]
Committed in 8451b04.
In the future, please use .zip, .rar is kind of unconventional.
