### ISSUE TITLE
Signal flags as decoration

### ISSUE THREAD

**Issue by spurdo-sparde** [flaghunters/Extra-Flags-for-4chan#220]
For shits and giggles, I decided to make a set of the maritime signal flags (see 5b8a78f)  
I was wondering, because I can't do JS to save my life, if someone could insert a bit into the beta config section for selecting a decoration flag. The files in the folder correspond to the letter they represent.  
On the ground of formatting, I think it would looks something like this:  
`Anonymous` ![o](https://cloud.githubusercontent.com/assets/12941327/15159949/3ab9f7f0-16c5-11e6-8d04-e33de68b1956.png)` (ID: gjiw2WX) `![us](https://cloud.githubusercontent.com/assets/12941327/15159966/581286e6-16c5-11e6-98a4-0cf7be70fda7.gif) ![pennsylvania](https://cloud.githubusercontent.com/assets/12941327/15159974/63e7c1d4-16c5-11e6-8742-2d7836ade1a1.png) ![york](https://cloud.githubusercontent.com/assets/12941327/15159978/6cefdbc2-16c5-11e6-9b39-e533d184047b.png) `5/10/16 15:40:40`

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
For how the project is currently set up, this is quite impossible. 
There's dependencies on current flags (we copy the element and replace values with our own flags from github) and the backend is not ready for this at all.

In short, you'd need to redo the whole backend and most of the script.
If you're really interested in making this a thing, you would probably be better of making a new project with a new backend, than you can use parts from this script as a base.

**Comment by spurdo-sparde** [comment]
Yeah, I thought you would like the labels.  
Like I said, I can't do JS for my life, so I'm going to try and process what you said.  

>we copy the element and replace values with our own flags from github  

So, basically, 4chan sends out a header to the other people on the page showing them the flag, and then what the JS does is it rewrites the header to show the additional flags - the flags are contained in an element box or something of the like on the page.
If so, I would assume the thing that makes this have to need a new backend is the formatting where I wanted it. If this is true, I wouldn't really care where the flag was, maybe it's possible to add a few bits of whitespace before it shows the other flags?   
i.e  
`Anonymous (ID: gjiw2WX)`![o](https://cloud.githubusercontent.com/assets/12941327/15159949/3ab9f7f0-16c5-11e6-8d04-e33de68b1956.png)&nbsp;&nbsp;&nbsp;&nbsp;![us](https://cloud.githubusercontent.com/assets/12941327/15159966/581286e6-16c5-11e6-98a4-0cf7be70fda7.gif) ![pennsylvania](https://cloud.githubusercontent.com/assets/12941327/15159974/63e7c1d4-16c5-11e6-8742-2d7836ade1a1.png) ![york](https://cloud.githubusercontent.com/assets/12941327/15159978/6cefdbc2-16c5-11e6-9b39-e533d184047b.png) `5/10/16 15:40:40`

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
We copied the flag element and just put it to the right of it because it was easiest at that time.
I'm no JS dev either so luckily I got a lot of help from other collaborators, otherwise we wouldn't have what we have now.

For your version I'd say invest some more time in building up the element instead of copying the original flag, that way you can introduce flags to non-flag boards.

I'm willing to help out, but it should not be incorporated into this project.

**Comment by spurdo-sparde** [comment]
Alright, I'll just leave the directory there in case you have some use for it.
