### ISSUE TITLE
Migrate flags to region folders (cascading)

### ISSUE THREAD

**Issue by WhatIsThisImNotGoodWithComputers** [flaghunters/Extra-Flags-for-4chan#222]
We have two folders now, we will be moving from "flegs"  to "flags".

In flags we see a new structure. The top level folders are countries, quite the same as flegs.
What we need are cascading regions.

For example:
- United Kingdom (country folder)
- United States (country folder)
 - California (png flag)
 - California (folder)
   - Lancaster (png flag)
    - Los Angeles (png flag)
 - Delaware (png flag)

See flags folder for how the structure should be.

**Comment by Delftanon** [comment]
[Canada.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/260184/Canada.zip)

Here's Canada done. New Brunswick and Prince Edward Island do not have any flags as of yet, added the folders anyway. Iroquois is "a historically powerful and important northeast Native American confederacy" so I don't think it belongs in any province folder.

**Comment by karakalpak** [comment]
What if some provinces have flags but some don't? I created the flags for Turkey, and every province has city flags but half of the provinces themselvs don't have their own flags.

**Comment by Anonymous7432** [comment]
I have a question about this 

Will the cascading flags/extra regional flags (not sure of the correct term) be optional?

I appreciate the concept, but im not sure that every user will want to post with a list of potentially 4 flags all the time (eg. UK-England/Scotland/etc-County-City/Locality)

Please dont take this as me bashing the idea; I see why a lot of posters might want it, especially the flag collectors

All im saying is that it should be an optional feature. Maybe thats already the intention. Just wanted to voice my concerns.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
@karakalpak Best would be to add coa's or something comparable, if that's not possible, I'd say just put them in, not in folders, just as the top regions for Turkey. 

@Anonymous7432 for posting the user decides how many flags they send but they must start at the highest division. For showing flags there will be a self-filter to limit the flags to only 1, might have to make an exception for UK. Filter is yet to be implemented.

**Comment by yanarai** [comment]
[Flags 1.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/264066/Flags.1.zip)
This includes
-Austria
-Former Yugoslavia
-Italy
-Spain

**Comment by yanarai** [comment]
[Austria.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/264069/Austria.zip)
Fugg

**Comment by karakalpak** [comment]
Alri I'll do Turkey later today.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks, they're added

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
So we're still missing a few, anyone know which ones?

**Comment by karakalpak** [comment]
All of Oceania, Africa and Asia save for Turkey, SK, Japan, the Philippines, India and Sri Lanka are done. I habe Belarus ready (with new city flags) and I'll submit it this afternoon with remade Brazil, Philippines and some of the rest.

Europe still has a long way to go.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Oh shit, don't know how I could've missed that, added Canada now.
As lot of Europe is missing we'll have to wait for a bit longer.

**Comment by Malte-Soeren** [comment]
Just did all of germany, I added flags for the administrative divisions between Bundesländer and Landkreise, the Bezirke (for the four Bundesländer that have those), some didn't have any flag or coat of arms, so they got just a white, glossed 16x11px flag:
http://www.mediafire.com/download/uty42ngysi2385b/regionflags_germany.zip

**Comment by yanarai** [comment]
Apparently I forgot to add Macedonia
[Macedonia.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/268755/Macedonia.zip)

**Comment by yanarai** [comment]
[Switzerland.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/274982/Switzerland.zip)

**Comment by sdjklag** [comment]
Do I need to add the new flags to both flags/ and flegs/?

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Should be flags, flegs is optional now and will be deleted once we switch to v2.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Added Macedonia and Switzerland from this thread.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Also added Germany.

Please open new tickets for countries you submit instead of a comment, they're too easy to miss if they're not a separate issue.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Just moved Hong Kong from flegs to flags, this seemed to be the last one.
The only ones missing are Yemen and Unknown, but they are both meme flags.

Can anyone confirm whether we're done or not, because I think we're ready.

**Comment by flagzzzz** [comment]
Looks good here. One anon is sorting and renaming some flags right now but after that, I think we'll be ready

**Comment by flagzzzz** [comment]
Last update has been made, I think we're ready now

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Alright. I'll finalize tomorrow morning.
