### ISSUE TITLE
Charlotte's flag

### ISSUE THREAD

**Issue by MasterAutismo** [flaghunters/Extra-Flags-for-4chan#223]
![charlotte](https://cloud.githubusercontent.com/assets/18697669/15197677/c0eaec18-17a0-11e6-8a27-d34b3615cf11.png)

Requesting that Charlotte's flag be changed to the above flag. The current flag is technically the city's flag, however, it is defunct in usage since the adoption of the new flag in the 1980s and is not flown anywhere in the city, only being hung in the city council room. The above flag, in contrast, is flown in front of government buildings downtown. Pic related below.

![charlotte flag](https://cloud.githubusercontent.com/assets/18697669/15197747/2b141fec-17a1-11e6-8bbc-8818d13c962c.png)

If it is at all possible to keep both somehow, that's also acceptable, but the green crown flag is the newer and more used version.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Wikipedia has the blue one.
I think we should stick with the official one.
Any source which might suggest the green with crown is official?

**Comment by MasterAutismo** [comment]
https://web.archive.org/web/20030613193235/http://cmstory.org/govt/page6.asp

From the website of the Charlotte and Mecklenburg County public library. 
"It is unusual for a city to have two official flags, but Charlotte does."
"This flag was adopted in 1985 and is the one flown outside Government Center on 4th Street." 

While both of the flags are official, the blue one was adopted in 1929 and is literally just sitting up in the city council room. I've never seen it anywhere else - which is in stark contrast to the use of the green crown. It's official, better represents the city, and you can't go a block without seeing it.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Changed this one.
Don't think we can support dual flags, theoretically we might try a 32x11 px image with flags.
For Charlotte and that special snowflake state with a two sided flag.
