### ISSUE TITLE
New and organised flags for 59 countries

### ISSUE THREAD

**Issue by karakalpak** [flaghunters/Extra-Flags-for-4chan#224]
**[meant for the new 'flags' folder]**

Organised flags for 59 folders, though most don't really have a hierarchy to speak of.

There's also quite a few newly-created flags in here, especially for Australia (with several defunct/nonexistent flags removed), Kazakhstan, and some African countries.

(Additionally, I'm not certain what the folder names for Ivory Coast and Sao Tome and Principe (with or without the tilde and acute accent) should be, so change them if they're wrong. Thanks.)

https://mega.nz/#!AVFGxSbY!MGP8t0WjJuBVRKB7XenjO2chpO2vj2twh5X-npe5adA

- Algeria
- American Samoa
- Angola
- Armenia
- Australia
- Azerbaijan
- Barbados
- Belize
- Benin
- Bermuda
- Bonaire, Sint Eustatius and Saba
- Comoros
- Democratic Republic of the Congo
- Djibouti
- Equatorial Guinea
- Ethiopia
- Federated States of Micronesia
- Fiji
- French Guiana
- French Polynesia
- Georgia
- Ghana
- Greenland
- Iran
- Isle of Man
- Ivory Coast
- Kazakhstan
- Kenya
- Liechtenstein
- Luxembourg
- Madagascar
- Marshall Islands
- Mauritius
- Morocco
- Mozambique
- Namibia
- Nepal
- New Caledonia
- New Zealand
- Nigeria
- Oman
- Papua New Guinea
- Réunion
- Sao Tome and Principe
- Senegal
- Solomon Islands
- Somalia
- South Africa
- Sudan
- Svalbard and Jan Mayen
- Tajikistan
- Tanzania
- Tonga
- Tunisia
- United Arab Emirates
- Uzbekistan
- Vanuatu
- Vietnam
- Zimbabwe

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks fam, they're in.
