### ISSUE TITLE
More flags

### ISSUE THREAD

**Issue by karakalpak** [flaghunters/Extra-Flags-for-4chan#226]
Added tons of flags and sorted existing ones out

https://mega.nz/#!gM8RECKb!3aRcEYoiDFpZK93cL80AVheY_T7hwaRdZk6B8BTUXkU

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks fam.
In other issue I saw zip attached on github comment so apparently we can upload zips now here too.
