### ISSUE TITLE
Support for two flag and double sided flag regions 

### ISSUE THREAD

**Issue by WhatIsThisImNotGoodWithComputers** [flaghunters/Extra-Flags-for-4chan#227]
Like in #223 we have a region with two official flags.
We also have that special snowflake US state which has a two sided flag.
Maybe try a 32x11 px image with two flags in one.

**Comment by karakalpak** [comment]
There's more than you'd think 2bh

https://en.wikipedia.org/wiki/Flags_whose_reverse_differs_from_the_obverse

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
That's pretty interesting.
Don't think that's a lot though.
But there's also places with two official flags, wonder how much that will be.

**Comment by Thsar999** [comment]
Another region with two official flags is the state of Kansas (kind of)
The second flag is much less used (barely at all) and is known as the "State Banner" It's typically only flown vertically but can be flown just like any other flag
While it's less used, it's actually a much better flag design and has equally official status as the state flag.

Proof: http://www.crwflags.com/fotw/flags/us-ks.html#ban
