### ISSUE TITLE
New gloss (for flags with white borders) + glossed flags

### ISSUE THREAD

**Issue by karakalpak** [flaghunters/Extra-Flags-for-4chan#230]
So I made a new gloss for flags with a white background, you could add it to the folder:
![gloss template 4 for white backgrounds](https://cloud.githubusercontent.com/assets/17495420/15370581/3a34efdc-1d6a-11e6-8e75-8de1f0309e20.png)
It's based on the standard FAMFAMFAM flag backgrounds; as a demonstration here's the glossed flags of Minas Gerais and Tomsk Oblast in comparison to the vanilla flags for Cyprus and Japan on the Yotsuba B background colour.
![image](https://cloud.githubusercontent.com/assets/17495420/15370712/ba1231e2-1d6a-11e6-94ef-b2056daff53e.png)
_It only works well for flags with white backgrounds though, so it's not universal and Gloss Template 3 should continue to be used for most other flags._

Here's a folder of flags with white backgrounds (sorted of course) that have been remade with the new gloss.
[New gloss.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/271160/New.gloss.zip)

Besides that, for Chile, "Aisen Region" should be deleted (after adding the new folder) as it's a duplicate of Aysen Region (the correct spelling). Thanks

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks fam.
I've renamed the old one to Gloss Template (Generic) and yours to Gloss Template (White), removed the other two templates, they shouldn't be used anymore. 
Will remove these later to the new flags folder.
