### ISSUE TITLE
Supernational Flags

### ISSUE THREAD

**Issue by yanarai** [flaghunters/Extra-Flags-for-4chan#239]
Would it be possible to make supernational flags available? From a pure technical standpoint?

**Comment by flagzzzz** [comment]
If you're talking about flags for NATO, UN, GUAM, etc. yes it would be possible. But I don't think they should be added since that would take away from people using actual regional flags. Plus, you would already know which countries are a part of which organizations

**Comment by yanarai** [comment]
Alright
Maybe I'll suggest it to Kunanon when he returns

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
It would be possible but it won't be done in this project. 
Also because some exist already like EU and AP, although there's no flag for AP, it does exist.
