### ISSUE TITLE
Final touch of autism?

### ISSUE THREAD

**Issue by karakalpak** [flaghunters/Extra-Flags-for-4chan#251]
Requesting:
- Antwerp (City) changed to Antwerpen (stad) to be uniform with Groningen (stad) and Utrecht (stad) over in the Netherlands
- Rabat (Gozo) in Gozo Region, Malta changed to simply Rabat
- Bo i Telemark in Telemark, Norway renamed to simply Bo (as that's the municipality name)

Thanks

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Renamed these and a couple more in f7fd025 and 789c3f3
Stad isn't needed anymore.
