### ISSUE TITLE
Create new webms and screenshots

### ISSUE THREAD

**Issue by WhatIsThisImNotGoodWithComputers** [flaghunters/Extra-Flags-for-4chan#254]
Need some new tutorial webms of installing and modifying flag.

Also need some neat screenshots.

**Comment by karakalpak** [comment]
Screenshots for?

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
https://flaghunters.github.io/Extra-Flags-for-4chan/

**Comment by karakalpak** [comment]
My crappy attempt
![image](https://cloud.githubusercontent.com/assets/17495420/15634733/cbefc8c0-25fd-11e6-8535-6250f14ac006.png)

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Don't want to be a buzzkill but would prefer something with at least one USA in it.

**Comment by flagzzzz** [comment]
![sample](https://cloud.githubusercontent.com/assets/18647741/15635281/7a4b56e2-25a8-11e6-98cb-833ed214b7ac.png)

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Using this one for now, now we need webms.
Will make them later if noone else does it.

**Comment by 3Paracetamol** [comment]
I have made an instructional webm for Firefox if its still needed. Hope it is of sufficient quality.
[Firefox.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/297372/Firefox.zip)

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Yes, it's better because it includes the installation of GreaseMonkey as well.

Still to do:

- Chrom* install 
- Chrom* change flag
- Opera install
- Opera change flag
- Android Firefox install
- Android Firefox change flag

**Comment by 3Paracetamol** [comment]
Here is the instructional webm for chrome. There is a problem with the script for android firefox, any version above Firefox 43 will **not** allow any unsigned add-ons, even changing xpinstall.signatures.required to false wont work either now. There is no override, and the current version is 46 for mobile. I will make an instructional webm for firefox 43 as an obsolete guide
[Chrome.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/298753/Chrome.zip)

**Comment by 3Paracetamol** [comment]
Here is the instructional webm for Android Firefox 43
http://www.uloz.to/xp2nJFQo/flags4chan-zip password is "flag"
As said before this only works for android firefox versions 43 and under, also another critical thing that is needed, is the supplementary .html file included, which as shown in the video must be in the same directory as the "extra-flags-for-int-ffma.xpi" file when run in firefox. It is essential that this is noted in the text instructions and the extra steps shown in the video.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Application signing is not enforced yet
https://wiki.mozilla.org/Add-ons/Extension_Signing#Timeline

Did you flip the correct switch?
There's a couple with xpi in the name.

I actively use Firefox stable and beta on my device and they both have the extension installed.
With developing this v2 I used the latest version of nightly (built yesterday), clean install, and I could still install the extension.

The removal of the override is has been pushed from version 46 to version 48 for desktop and even later for Firefox for Android according to the source above.

I'll look into signing it, as I wasn't aware the override was scheduled to be removed, seems like a hassle to sign.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Signing is not going to happen, the only organisation issueing free certificates to open source projects requires proof of identity.
So the unsigned one will have to make due until there's a non-shit alternative for userscripts on Android Firefox (or another non-shit mobile browser); this one is in alpha but might be good: https://addons.mozilla.org/en-uS/android/addon/userunified-script-injector/

**Comment by 3Paracetamol** [comment]
[Test2.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/298794/Test2.zip)
This is what I get if I try to install the script on any version other then 43 and lower. Clean install btw

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Can you try browsing to /sdcard in Firefox and installing from there?
That's how I did it.

It will also say blocked there, but here I can choose Dismiss and Allow.

**Comment by 3Paracetamol** [comment]
It is working here

**Comment by 3Paracetamol** [comment]
I should make an instructional webm for this

**Comment by 3Paracetamol** [comment]
Here are the final instructional webms for Android firefox and opera
http://www.uloz.to/xQsSa4u4/video-tutorials-zip
password is "flag"

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks lad, forgot all about this.
All install webms are finished and on the front page

I'll create the last two webms about changing flag sometime later and then we can close this.

**Comment by 3Paracetamol** [comment]
I think this is now done, I will close this issue.
