### ISSUE TITLE
Bath, Somerset, England, UK

### ISSUE THREAD

**Issue by Anonymous7432** [flaghunters/Extra-Flags-for-4chan#263]
![bath](https://cloud.githubusercontent.com/assets/18105912/15660560/18fe3a74-26d6-11e6-9f1a-a40066cb4330.png)

**Comment by Anonymous7432** [comment]
Updated version

![bath2](https://cloud.githubusercontent.com/assets/18105912/15660576/51144958-26d6-11e6-928e-9090a1f0b094.png)

**Comment by flagzzzz** [comment]
Added
