### ISSUE TITLE
Valle de Cauca, Colombia Municipalities

### ISSUE THREAD

**Issue by AvidFlagHunter** [flaghunters/Extra-Flags-for-4chan#264]
[Valle de Cauca Municipalities.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/290265/Valle.de.Cauca.Municipalities.zip)
While some may be the similar or near the same, they were taken from CRW flags which has proven to be highly reliable.

**Comment by flagzzzz** [comment]
Thank lad, they're added. In the future, if you could gloss the flags you submit I would greatly appreciate it. Just add a new layer on top of the 16x11 flag and paste [this image](https://raw.githubusercontent.com/flaghunters/Extra-Flags-for-4chan/master/flags/Gloss%20Template%20%28Generic%29.png) if you're not making a flag with a white background or [this one](https://raw.githubusercontent.com/flaghunters/Extra-Flags-for-4chan/master/flags/Gloss%20Template%20%28White%29.png) if you're making a flag with a white background
