### ISSUE TITLE
Accents

### ISSUE THREAD

**Issue by karakalpak** [flaghunters/Extra-Flags-for-4chan#272]
Since accents are available now is it advisable that I rename the relevant countries and resubmit their flags with the accents this time? There's not too many and I can do it quickly but it'd affect anyone using a flag that's supposed to have accents.

**Comment by flagzzzz** [comment]
I started doing that with France and another anon did it with Germany. I say yes, or at least new submissions should include accents

**Comment by karakalpak** [comment]
Alri. I'll work on it
