### ISSUE TITLE
Township flags for US states 

### ISSUE THREAD

**Issue by nyli1** [flaghunters/Extra-Flags-for-4chan#275]
There was discussion of adding township flags for the US states that have them, if this project is already in the works I just wanted to add one here early 
![town of oyster bay flag1](https://cloud.githubusercontent.com/assets/19680730/15699662/a6b9a12a-279c-11e6-9728-fe45b6e1ab13.png)

**Comment by flagzzzz** [comment]
What township is this for?

**Comment by nyli1** [comment]
It's for the "Town of Oyster Bay"

**Comment by nyli1** [comment]
I should also add that it is a Township in Nassau county, New York
