### ISSUE TITLE
India Regional City Flags

### ISSUE THREAD

**Issue by Designated** [flaghunters/Extra-Flags-for-4chan#276]
Mumbai, Maharashtra : 
![mumbai](https://cloud.githubusercontent.com/assets/19663668/15714837/ca1cfcb4-2839-11e6-8861-07998e1b8fcc.gif)

Kolhapur, Maharashtra : 
![kolhapur](https://cloud.githubusercontent.com/assets/19663668/15714850/df532c8e-2839-11e6-9287-db2e2fb43cb3.gif)

Pune, Maharashtra : 
![pune](https://cloud.githubusercontent.com/assets/19663668/15714857/ebc9f7fe-2839-11e6-8c27-e344db102bcc.gif)

Thane, Maharashtra : 
![thane](https://cloud.githubusercontent.com/assets/19663668/15714869/f5658968-2839-11e6-9ce4-3926b4d48ba8.gif)

Panaji, Goa : 
![panaji](https://cloud.githubusercontent.com/assets/19663668/15714881/00cfe686-283a-11e6-9b63-c705ebb22a83.gif)

South Delhi, Delhi : 
![south delhi](https://cloud.githubusercontent.com/assets/19663668/15714890/0a66bf76-283a-11e6-86fd-288955d0375b.gif)

North Delhi, Delhi : 
![north delhi](https://cloud.githubusercontent.com/assets/19663668/15714901/14cbb322-283a-11e6-88fc-acc4a18e53c3.gif)

Bangalore, Karnataka : 
![bangalore](https://cloud.githubusercontent.com/assets/19663668/15714913/1fe713dc-283a-11e6-855d-6e8564339b4d.gif)

Mangalore, Karnataka : 
![mangalore](https://cloud.githubusercontent.com/assets/19663668/15714922/2b7e8068-283a-11e6-9b4f-ec05d354e8c2.gif)

Vishakapatanam, Andhra Pradesh : 
![vishakapatanam](https://cloud.githubusercontent.com/assets/19663668/15714941/3be44b18-283a-11e6-910b-d0ad9ba39436.gif)

Hyderabad, Telangana : 
![hyderabad](https://cloud.githubusercontent.com/assets/19663668/15714976/648a27f4-283a-11e6-9516-041990fdcdc5.gif)

**Comment by karakalpak** [comment]
Hyderabad is physically located in Telangana so I'd suggest only including it in that folder. It's similar to how Kiev is the capital of Kiev Oblast or Prague the capital of the Central Bohemian Region.

**Comment by Designated** [comment]
Yeah I thought so too, but I thought I'd add that part nevertheless considering that its Andhra Pradesh's De Jure capital 
I'll edit it right now
