### ISSUE TITLE
Georgia and Nepal

### ISSUE THREAD

**Issue by karakalpak** [flaghunters/Extra-Flags-for-4chan#287]
I suggest South Ossetia be deleted from Georgia and Abkhazia replaced with the one in this update as South Ossetia is an unrecognised separatist region that's not already a region of Georgia while the official region of Abkhazia has a different flag from the breakaway state of Abkhazia.

[Georgia and Nepal.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/295591/Georgia.and.Nepal.zip)

EDIT: Also here's a better flag for Baarn, Utrecht, Netherlands. Seems to be the only Dutch flag not made in the standard method.
![image](https://cloud.githubusercontent.com/assets/17495420/15745381/2043c97c-2904-11e6-977a-e7950a284bca.png)
and Amsterdam (Noord-Holland). Not letting one of my favourite city flags have a shit gloss.
![image](https://cloud.githubusercontent.com/assets/17495420/15745533/dcd9393c-2904-11e6-86f0-448a4d1c09ed.png)

**Comment by Thsar999** [comment]
>unrecognised separatist region
Correction, Russia recognizes tham and they both recognize each other

Just putting my two cents in, I see no reason not to include both the flag's of the separatist governments and the flags of the official regions. This way everybody has available to them what they would like to use and the script isn't politically biased towards any one side of the conflict.

**Comment by karakalpak** [comment]
There's not been flags that are non-official (or at least represent non-official regions) since the last update. ISIS and Houthis were both considered meme flags. I don't see how this is any different.
