### ISSUE TITLE
Misaligned flags on Chrome graphical bug

### ISSUE THREAD

**Issue by GTAnon** [flaghunters/Extra-Flags-for-4chan#288]
Let C be the country flag of any post. ie the flag that shows up even without the extension.
Let R in general refer to the entire block of regional flags that follow a poster's country flag where R<sub>1</sub> is the first regional flag, R<sub>2</sub> is the one to the right of R<sub>1</sub> and so on.

There's a graphical bug at least on Chrome, though an anon has pointed out that it might not be there on Firefox that involves the R flags being misaligned from the C flag.

More specifically, The entire R block is offset from C vertically by 1 pixel down.
Additionally, while the spacing between R<sub>n</sub>  and R<sub>n+1</sub> is 5 pixels, the spacing between C and R<sub>1</sub> is 10 pixels.

After looking at the script via the tampermonkey dashboard, the vertical offset is caused by this line
`newFlag.style = "padding: 0px 0px 0px 5px; vertical-align:;display: inline-block; width: 16px; height: 11px; position: relative; top: 1px;";`

Changing 1px to 0px gets rid of the vertical misalignment, but the spacing is still somewhat buggy. 

When a thread's page is loaded, the posts that were already there all have their flags perfectly spaced. However, when the page is updated via the inline extension, any new posts have a 10 pixel spacing between C and R<sub>1</sub> where refreshing the page gets rid of it. I'm not exactly sure what causes that.

t. incredibly new to JavaScript

Old posts showing correct spacing but vertical offset of 1 pixel:
![offset regionals](https://cloud.githubusercontent.com/assets/18518257/15754503/6f84e824-28c6-11e6-91eb-8d8a1d9bdcdd.png)

A mix of old posts and new updated posts showing the difference in spacing between old posts and posts generated after updating, with the vertical offset fixed:
![offset regionals 2](https://cloud.githubusercontent.com/assets/18518257/15754574/b1d080ee-28c6-11e6-8666-3c454a211b9d.png)

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
There were issues with chrome in the past as well, think those were about new flags having no padding between them at all. Might have to do something with resolution as well, not sure though.

**Comment by karakalpak** [comment]
@flagzzzz has fixed it
