### ISSUE TITLE
Delete beta branch

### ISSUE THREAD

**Issue by WhatIsThisImNotGoodWithComputers** [flaghunters/Extra-Flags-for-4chan#296]
Beta branch is 3 commits ahead of master, can it be safely deleted?

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
I didn't bother to check what the changes were btw.

**Comment by flagzzzz** [comment]
It's safe to delete. The 3 commits were adding some regions which are in the v2 folder, an automated flag_list script, and creating the branch itself
