### ISSUE TITLE
Gloss flag template + Extra Syrian flags 

### ISSUE THREAD

**Issue by mt117** [flaghunters/Extra-Flags-for-4chan#31]
![islamic front](https://cloud.githubusercontent.com/assets/11844752/7104062/65a01d7c-e094-11e4-8dd5-9321c6c5a0bf.png)
![gloss template](https://cloud.githubusercontent.com/assets/11844752/7103891/ffa31b1e-e089-11e4-9a0c-4499990fe87d.png)
![jabhat al nusra](https://cloud.githubusercontent.com/assets/11844752/7103913/3e326b54-e08b-11e4-8e0f-6ad7d8d76fb6.png)
![syrian kurdistan](https://cloud.githubusercontent.com/assets/11844752/7103914/413f5186-e08b-11e4-8b05-feeef3c21c7c.png)
![syrian rebels](https://cloud.githubusercontent.com/assets/11844752/7103915/46da3232-e08b-11e4-83a4-bfdcdc138ccf.png)
![hezbollah](https://cloud.githubusercontent.com/assets/11844752/7103921/df220e34-e08b-11e4-94bf-9ff910d0ccd9.png)
![better template](https://cloud.githubusercontent.com/assets/11844752/7103923/e2e04a4a-e08b-11e4-8e8b-3c49bdf01efe.png)

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Do you maybe have the names for these?

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Also, template twice or is there an actual white flag there?

**Comment by mt117** [comment]
First one - Islamic front
second- Gloss template
third - Jabhat al Nusra
Fourth - Syrian Kurdistan
Fifth - Syrian Rebels
Sixth - Hezbollah
Seventh - Another gloss template


I made 2 different gloss templates the second one is better

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
I'm not 100% sure about these flags as they might turn Syria into a meme country regarding extra flags. (Moreso than it already was.)
We added ISIL because https://en.wikipedia.org/wiki/Ar-Raqqah_Governorate but I guess we can add these because they actually are de facto in control https://en.wikipedia.org/wiki/Syrian_Civil_War

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Only renamed Syrian Kurdistan to Rojava

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Added these.
