### ISSUE TITLE
More flags for Cyprus 

### ISSUE THREAD

**Issue by mt117** [flaghunters/Extra-Flags-for-4chan#32]
Cyprus

Famagusta
![famagusta](https://cloud.githubusercontent.com/assets/11844752/7103956/91ddea6e-e08e-11e4-8ad5-772e71d38e6f.png)

Northern cyprus
![northern cyprus](https://cloud.githubusercontent.com/assets/11844752/7103965/20aa0c0a-e08f-11e4-96ff-d145ca64d75e.png)

Akrotiri and Dhekelia
![akrotiri and dhekelia](https://cloud.githubusercontent.com/assets/11844752/7103990/f3f5318e-e08f-11e4-8ae6-7eaa6d0eff23.png)

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks!
