### ISSUE TITLE
Some diacritics don't work - fix needed

### ISSUE THREAD

**Issue by karakalpak** [flaghunters/Extra-Flags-for-4chan#321]
Certain diacritics don't work.
**Working languages**: Icelandic, Norwegian, Swedish, Danish, Finnish, Estonian, German, Dutch, English, French, Italian, Spanish/Castillian, Catalan, Galician, Portuguese, Basque, Albanian, Greenlandic, Malay (incl. Indonesian)
**Nearly completely working languages**: Slovene, Serbo-Croatian (incl. Bosnian and Montenegrin), Macedonian

Will be following this system for now for the remaining languages with Latin alphabets:
**Romanian (incl. Moldovan)**: Â and Î will be kept; Ă, Ș and Ț will be replaced with A, S and T respectively
**Hungarian**: Acute and grave accents will be omitted; Ő will be replaced with Ö and Ű will be replaced with Ü (since Ő and Ű are Ö and Ü with acute accents applied)
Diacritics will be completely ignored for Polish, Czech, Slovak, Latvian, Lithuanian, Vietnamese and Japanese romanisation

**Comment by flagzzzz** [comment]
š and ž work, but ş and ţ don't. I'll look through available regions and see if I can find out which ones do and don't work by trial and error

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Hate to say I told you so but this is what I expected.

Also it's quite a bother for people to keep swapping their flags in their settings.
But I guess there is no way back now anymore.

**Comment by karakalpak** [comment]
>š and ž work
Tested with Slovene and Croatian regions and they don't seem to

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
https://en.wikipedia.org/wiki/ISO/IEC_8859-1
