### ISSUE TITLE
Victoria, Australia Regional Flags 

### ISSUE THREAD

**Issue by Designated** [flaghunters/Extra-Flags-for-4chan#327]
https://mega.nz/#!d5U2maZS!_b-wlhSF3gK73stlKy2BykUR9YfWfIdlWPQgwFh_brg

**Comment by 3Paracetamol** [comment]
For any regions that start with "City of" Can you rename that to just the name of the city it self.
For example change 'City of Botany Bay' to just 'Botany Bay'
All other regions that start with Shire or council or anything else its fine and just leave it.

**Comment by Designated** [comment]
Alright lad, I saw that it was named that way on wikipedia, so I thought I'd rather not change it to avoid any confusion

**Comment by 3Paracetamol** [comment]
You did good, only need it that way because currently any cities on Extra-Flags-for-4chan are just the city name like the Botany bay example above. Also it makes sense on another level as a shire is made of many towns and each town may have its own flag, thus a new sub folder is born. But a city, is a single body with no extra flags under there.
Sorta the same as US counties, the County has the name and 'County' written after it. Then the city name only, as an extra flag.

**Comment by flagzzzz** [comment]
Cities cannot share the same name as the region they are in with this add on, it's with how I wrote some of the code for the menu selection

**Comment by 3Paracetamol** [comment]
Technically official regions
https://en.wikipedia.org/wiki/Local_government_areas_of_Victoria#Northeast
However they are unincorporated, so I dont know

**Comment by 3Paracetamol** [comment]
[Victoria Regionals.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/310781/Victoria.Regionals.zip)
Fixed naming inconsistencies.
Can be uploaded now

**Comment by Designated** [comment]
>Also, I see there are a few flags for alpine resorts. Are these official administrative divisions or meme flags?
The alpine resort thingies are official, not meme flags
Only made the flags for the LGA's that were mentioned on Wikipedia 

>Fixed naming inconsistencies.
>Can be uploaded now

Thanks anon

**Comment by Designated** [comment]
>Also, I see there are a few flags for alpine resorts. Are these official administrative divisions or meme flags?

The alpine resort thingies are official, not meme flags
Only made the flags for the LGA's that were mentioned on Wikipedia

>Fixed naming inconsistencies.
Can be uploaded now

**Comment by karakalpak** [comment]
Convert to .png format please

**Comment by Designated** [comment]
>Convert to .png format please

Alright fam, I gotchu

**Comment by Designated** [comment]
Uploaded to pomf

https://u.pomf.is/vgcjsx.zip

**Comment by karakalpak** [comment]
Can you just upload it here
![image](https://cloud.githubusercontent.com/assets/17495420/16038686/c120c3ba-3258-11e6-9092-6156d6c8b427.png)

**Comment by 3Paracetamol** [comment]
[Victoria Regionals.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/313648/Victoria.Regionals.zip)

**Comment by karakalpak** [comment]
Thanks
