### ISSUE TITLE
Looking for another flag manager

### ISSUE THREAD

**Issue by WhatIsThisImNotGoodWithComputers** [flaghunters/Extra-Flags-for-4chan#328]
Quite some issues are open for quite a while.
That's why I'd like to add someone else to the project to organize the flags.

Requirements:
- Know how to use git

For GUI applications I recommend Sourcetree for Windows and git-cola for Linux. They are quite easy to use.

**Comment by karakalpak** [comment]
I guess I could be of help with my eternally flaming autism though I'm slightly busy at the moment and I'm quite the beginner to git. According to @flagzzzz it's pretty simple to use so I'll try to get the hang of it once I can.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
That's no problem, I'm moving to a new place so I don't have any time, at all.
Sending you an invite.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Need someone to help out.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Opening a new one so it gets on top.
