### ISSUE TITLE
More flags

### ISSUE THREAD

**Issue by mt117** [flaghunters/Extra-Flags-for-4chan#33]
Lebanon ------------

North
![north](https://cloud.githubusercontent.com/assets/11844752/7106028/4da90dd2-e102-11e4-96b8-2b41d0a42b8b.png)
South
![south](https://cloud.githubusercontent.com/assets/11844752/7106031/54dd9b7c-e102-11e4-8bc8-240121b9a876.png)
Bekaa
![bekaa](https://cloud.githubusercontent.com/assets/11844752/7106032/5abb26b8-e102-11e4-91e8-d285756f997a.png)
Mount Lebanon
![mount lebanon](https://cloud.githubusercontent.com/assets/11844752/7106040/6cb3332e-e102-11e4-81df-4e3d830f0b7d.png)

Italy-----------------
Rome (I know its not a subdivision but a lot of Italians were requesting it)
![rome](https://cloud.githubusercontent.com/assets/11844752/7106089/628e4314-e104-11e4-8167-74c0df102a1a.png)
Georgia-------------
South Ossetia
![south ossetia](https://cloud.githubusercontent.com/assets/11844752/7106129/b608358a-e105-11e4-8182-cdbee3455ebe.png)
United States--------------

New York City (Was requested, not sure if it should be used though)
![new york city](https://cloud.githubusercontent.com/assets/11844752/7106140/3d0d9a20-e106-11e4-9006-0de37a1a34d5.png)
Turkey--------------
Sinop
![sinop](https://cloud.githubusercontent.com/assets/11844752/7106183/3a5ddd98-e107-11e4-8ea1-cf37cb30c6be.png)
Batman
![batman](https://cloud.githubusercontent.com/assets/11844752/7106195/8bd34726-e107-11e4-8646-373a6f58e8d8.png)

Edirne
![edirne](https://cloud.githubusercontent.com/assets/11844752/7106221/d0b2c9ca-e107-11e4-9ae2-ce17c15ca3fc.png)

Karaman
![karaman](https://cloud.githubusercontent.com/assets/11844752/7106234/17907fb8-e108-11e4-99a3-486e579624dc.png)

Van
![van](https://cloud.githubusercontent.com/assets/11844752/7106239/4d3f7a9c-e108-11e4-9474-af33373f6419.png)
Sakarya
![sakarya](https://cloud.githubusercontent.com/assets/11844752/7106252/cb6138d4-e108-11e4-8107-4b2c92cddbe7.png)
Yalova
![yalova](https://cloud.githubusercontent.com/assets/11844752/7106259/1df1e1fc-e109-11e4-9d8f-72abf5312d24.png)

Iraq------------
Erbil
![erbil](https://cloud.githubusercontent.com/assets/11844752/7106291/8a36ce2c-e109-11e4-8746-d7f831d9a895.png)
Dohuk
![dohuk](https://cloud.githubusercontent.com/assets/11844752/7106299/b01844ae-e109-11e4-87b3-3f2ee6f629ed.png)
Sulaymaniyah
![al-sulaymaniyah](https://cloud.githubusercontent.com/assets/11844752/7106309/d840db76-e109-11e4-84e4-16b8d8330b68.png)
netherlands--------
Amsterdam
![ampsterdam](https://cloud.githubusercontent.com/assets/11844752/7106336/bce9bc20-e10a-11e4-87b6-5c512e0f753d.png)
Ukraine--------
Donetsk Peoples Republic
![donetsk](https://cloud.githubusercontent.com/assets/11844752/7106382/8b1fb058-e10c-11e4-9e6c-6aaf29e8b7ca.png)
Luhans'k Peoples Republic
![luhansk](https://cloud.githubusercontent.com/assets/11844752/7106395/f350335a-e10c-11e4-8acc-8a8458b721f5.png)
Yemen--------
Houthis 
![houthis](https://cloud.githubusercontent.com/assets/11844752/7106406/4e69033e-e10d-11e4-8480-20c411969b31.png)
Cyprus----------------
Buffer Zone
![buffer zone](https://cloud.githubusercontent.com/assets/11844752/7106435/b47a871e-e10e-11e4-8ec5-003411180036.png)

**Comment by mt117** [comment]
Also crwflags.com is a good place to find hard to find regional flags

**Comment by mt117** [comment]
Here's  map of ISIS's flags they give to provinces 
![qfb0su6](https://cloud.githubusercontent.com/assets/11844752/7106326/5c7c31ba-e10a-11e4-9b36-e897ffaf41db.jpg)
Could they be used? They're not official of course

**Comment by mt117** [comment]
World map for collecting 
![1428449128789](https://cloud.githubusercontent.com/assets/11844752/7106458/9ec5c93c-e10f-11e4-8cbd-77b49f50c859.png)

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
We first only used first level divisions, but I don't think it's a big problem to use other flags if people prefer to use those. But I'm not a fan of using memeflags or historical flags like nazi or dixie. 
Flags used by actual occupants like Sealand or Syria forces is the limit.

Sorry to be a bother again but could you zip them and upload to pomf.se? Possibly by country? It saves me the hassle of individually downloading and renaming them as they are so much.

ISIS occupational provinces goes a bit far I think.

**Comment by mt117** [comment]
I don't know how to zip files srry

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks, I added these.
You can easily zip with winrar or another program like that.
That would be a big help because I'm suffering of a bit of RSI symptoms lately.
