### ISSUE TITLE
Slovakia regional flag

### ISSUE THREAD

**Issue by KottiCheese** [flaghunters/Extra-Flags-for-4chan#330]
could you add this flag under the Banska Bystrica region?
![ziar nad hronom](https://cloud.githubusercontent.com/assets/17087200/15930516/b4964114-2e53-11e6-8626-768cf9a8e30a.png)
it's for town called Ziar nad Hronom

**Comment by karakalpak** [comment]
![image](https://cloud.githubusercontent.com/assets/17495420/15931025/674789a6-2e88-11e6-9662-21357427e538.png)
As per CRW this is the flag of said city, can't find any source at all for your flag.

Nonetheless I'm doing the lowest administrative divisions of both ex-yu and v4 so 99% of Eastern Europe should have flags soon.

**Comment by KottiCheese** [comment]
the flag i posted is flown at the town hall, it's the official one
[http://ziar.dnes24.sk/images/photoarchive/sized/700/2016/05/20/ziar-nad-hronom-mestsky-urad-msu-2-.JPG]()

looking forward to all of those flags, thanks

**Comment by karakalpak** [comment]
Yeah just got it from ziar.sk. Edited my comment with the glossed flag you want. Admins should add it soon though they've been rather inactive lately.

**Comment by KottiCheese** [comment]
Okay thanks, looking forward to all of those flags, you are doing a great job
