### ISSUE TITLE
Switzerland Part 1

### ISSUE THREAD

**Issue by yanarai** [flaghunters/Extra-Flags-for-4chan#331]
Included are about 1200 flags. This is about 50% of all Swiss municipality flags.
They are sorted according to subdivisions
- Canton
- Region (Bezirk, Amt...)
- Municipality 

I decided to upload this uncompleted as I wont have a lot of time to work on the project due to exams/moving and am not sure when will have time return to complete it.

[Switzerland Part 1.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/307663/Switzerland.Part.1.zip)

**Comment by yanarai** [comment]
Also please remove the Gemeinde Biel and Bezirk Biel flag. I will remake them later

**Comment by flagzzzz** [comment]
Sorry for the late response, but could you resubmit the zip on mega. The git submission does not like most diacritics so I get weird symbols in their place

**Comment by yanarai** [comment]
hoping this works
https://mega.nz/#!NZgQhADT

**Comment by yanarai** [comment]
this is the key for it 
!I_N1YANh5ktO8nP_DHdNAl8cRtAjOuRB7HsL9l-0WoE

i'll disable it next time

**Comment by flagzzzz** [comment]
Still getting this ![capture](https://cloud.githubusercontent.com/assets/18647741/15986758/59401150-2fde-11e6-8359-3e6eae25be39.PNG). I might just need to fix all the diacritics on my end

**Comment by yanarai** [comment]
When I download it all the umlauts show so I'm guessing it's a problem on your end

**Comment by karakalpak** [comment]
Think it's a github problem. Upload it as a .rar file on mega, that works

**Comment by yanarai** [comment]
https://mega.nz/#!tNgDFT6L
Rar

**Comment by karakalpak** [comment]
Can you:
- Remove the weird .ds files from each folder (leaving flags only)
- Fix all folders with no flags matching their names (e.g. those in Appenzell Ausserrhoden
- Rename files like this:
![image](https://cloud.githubusercontent.com/assets/17495420/16069883/652ef610-3304-11e6-8b5b-424c535801f9.png)
Since differentiation between places with the same name in different divisions is no longer needed

**Comment by yanarai** [comment]
Would you mind posting a screenshot of these .ds files? When I download the .rar the only thing I get are the flags.

The version with correct names and folders:
https://mega.nz/#!4Jxh3CRK
!aGzZSShYSyxu-iLlGCRmTYOEtB4Ci98fUdFw_SWDJmI

**Comment by karakalpak** [comment]
They're named DS_Store and they're in nearly every folder.
![image](https://cloud.githubusercontent.com/assets/17495420/16085658/503f6f8c-334f-11e6-9dac-dfdb33a441d2.png)


Besides that what's Zürich Quartiere? Is it the same as Stadt Zürich? Its folder doesn't have a flag.

**Comment by yanarai** [comment]
Weird. Are you using windows? It might have something to do with the fact that I'm uploading them from a mac. 
![bildschirmfoto 2016-06-15 um 17 44 35](https://cloud.githubusercontent.com/assets/18600936/16086742/e102ff7c-3320-11e6-8be5-292458660c28.png)

Quartiere are city districts. The flag Stadt Zürich corresponds to that folder. 
https://en.wikipedia.org/wiki/Subdivisions_of_Z%C3%BCrich

**Comment by karakalpak** [comment]
Yeah I'm using windows

>Quartiere are city districts. The flag Stadt Zürich corresponds to that folder. 
Each folder must correspond to a filename, so just name the folder the city name next time.

**Comment by yanarai** [comment]
So should I change that and upload it again?

**Comment by karakalpak** [comment]
Change all instances of that happening I guess

**Comment by yanarai** [comment]
Alright this should be it. I cant help you with the .ds problem sorry about that
https://mega.nz/#!cBpzQbKC!8rhy3vJAhtMBMZk2UbpbICwrbvhzUpWVxXiJXVUa3iA

**Comment by MasterAutismo** [comment]
I'm willing to work on this issue if OP is still around. There are a lot of flags, so it's down there on the to-do list, but I can get it done at some point.

**Comment by yanarai** [comment]
I'm still around in a physical way, probably wont start working on this again though tbh
Would love to see this done anyways

**Comment by MasterAutismo** [comment]
I'll take it under my wing once I get other issues closed, thanks for letting me know!

**Comment by MasterAutismo** [comment]
Out of curiosity, would you be able to tell me which folders are 100% complete? I notice Bezirk Zurzach in Aargau needs to be done (which I'm doing), but any other helpful points in the right direction would be nice since I'm unfamiliar with Switzerland.

**Comment by MasterAutismo** [comment]
Never mind, I checked all of the current cantons you uploaded and all are correct. I'll have to make the remaining ones.

**Comment by MasterAutismo** [comment]
This issue is finished, will be closed shortly.
