### ISSUE TITLE
Add more city flags for Texas cities?

### ISSUE THREAD

**Issue by mraper3** [flaghunters/Extra-Flags-for-4chan#332]
This is a good add-on, thanks for working on it!  I'm in College Station, Texas, and was wondering if y'all had plans to add more city flags (such as CS) like you have for Houston, Lubbock, and a few others in Texas.

**Comment by yanarai** [comment]
I think someone is currently making county flags, maybe he will do city flags next.

If you can't wait you could make the flag yourself and submit it here by opening another issue and stating in what county it lies.

**Comment by karakalpak** [comment]
What @yanarai said. @MasterAutismo is trying to cover the US with flags at the moment but you'll have to wait a while for a city flag if you're not making it yourself

**Comment by mraper3** [comment]
Hmm, what format/resolution/etc would I need to make it if I submit it here?

**Comment by yanarai** [comment]
They should all be 16x11 and have this gloss applied.
![16x11 2](https://cloud.githubusercontent.com/assets/18600936/15984245/b04ab546-2fc4-11e6-9f9e-d1db832e4474.png)

If their background is mostly white use this one
![16x11 white](https://cloud.githubusercontent.com/assets/18600936/15984248/c1a8477c-2fc4-11e6-8131-7402b4d68de7.png)

**Comment by mraper3** [comment]
Hmm, what program could I use to apply the gloss?

Also, should the file be a .png? .jpg? .gif? Something else?

**Comment by yanarai** [comment]
You can use any program that has a layer function like photoshop, gimp or paint
It should be saved as a .png

**Comment by karakalpak** [comment]
Is this fine? Used the seal found on Wikipedia.

![image](https://cloud.githubusercontent.com/assets/17495420/15985468/c44e738c-3020-11e6-8628-b03c5aa6e235.png)

**Comment by mraper3** [comment]
Yes, that looks like what I have.  I don't know if CS actually has a flag of its own, but I guess the seal will work.  That works for me.

**Comment by mraper3** [comment]
Oh yeah, I forgot: College Station is in Brazos County, Texas.

**Comment by karakalpak** [comment]
what the fuck am i doing

**Comment by karakalpak** [comment]
Added. Babby's first day using Git
