### ISSUE TITLE
Northern Territory, Australia

### ISSUE THREAD

**Issue by 3Paracetamol** [flaghunters/Extra-Flags-for-4chan#334]
[Australia.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/309999/Australia.zip)

Here are the regional flags for Northern Territory.

Also another change that must be implemented is that under the root folder Australia, Murray River.png and the folder Murray River must be moved (while keeping the file structure) Into the New south wales folder.

**Comment by karakalpak** [comment]
>Murray River.png and the folder Murray River must be moved (while keeping the file structure) Into the New south wales folder.

The reason why I found the Murray flag was because of Albury-Wodonga, and since its left bank is in Victoria and its delta is in South Australia I think it should be a separate entity. Granted I don't know much about what the flag represents in the first place so feel free to correct me if it turns out to be that of a NSW region or something of the sort.

http://www.murrayriver.com.au/about-the-murray/murray-river-flag/

**Comment by 3Paracetamol** [comment]
Thats true, however under official government logistics, Murray is a region that technically belongs to NSW
https://en.wikipedia.org/wiki/Local_government_areas_of_New_South_Wales#Murray
Notice, NSW has a murray region and Albury is under it.

https://en.wikipedia.org/wiki/Local_government_areas_of_Victoria#Northeast
Notice, Wodonga is under Victorias Northeast division, and does not contain Murray.

https://en.wikipedia.org/wiki/Local_government_areas_of_South_Australia#Murray_Mallee_region
However South Australia does contain a Murray Region. 
So I suggest copying the Murray folder into both NSW and SA along with the Murray River.png and only the LM flag into SA and UM flag into NSW so the folder hierarchy goes like this. 
Australia -> New South Wales -> Murray -> Upper Murray -> 'Regions under NSW Murray'
               -> South Australia    -> Murray -> Lower Murray -> 'Regions under SA Murray'
Australia will have 5 flags now in a post

**Comment by karakalpak** [comment]
Oh that's a good idea, I agree.

**Comment by flagzzzz** [comment]
Submitted. Close this issue if I did the Murray organization right

**Comment by karakalpak** [comment]
The folders are there but I don't think the flags themselves are moved around yet

**Comment by flagzzzz** [comment]
Fixed

**Comment by 3Paracetamol** [comment]
I checked, everything is in order. However just before closing make another folder within the respective Lower and Upper Murray sub folders so the hierarchy goes like this
Australia -> NSW/SA -> Murray -> Upper/Lower Murray -> 'Regions under NSW/SA Murray'
When designated and I finish Aus regional flags it will be easier to put them in the bottom most folder.
