### ISSUE TITLE
Queensland, Tasmania and New South Wales Regionals

### ISSUE THREAD

**Issue by Designated** [flaghunters/Extra-Flags-for-4chan#337]
Queensland
https://u.pomf.is/tqalrc.rar

Tasmania
https://u.pomf.is/ejfiin.rar

New South Wales 
https://u.pomf.is/azevpp.rar

**Comment by 3Paracetamol** [comment]
[New South Wales.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/312991/New.South.Wales.zip)
Here are the sorted New South Wales flags in the correct folder structure along with some name fixes
eg (Tumur to Tumut) and moves eg ( Tumut Murray to Tumut Canberra Region)

From the master flag folder there are some moves that must be done.
Kiama and Wollongong   -> Illawara Folder
Wagga Wagga                 -> Murrumbidgee Folder
Queanbeyan                   -> Canberra Region Folder
Maitland and Newcastle -> Northern Tablelands, New England and Hunter Folder
Grafton        -> Mid North Coast -> Clarence Valley Folder     (This will be another 5 flag region)
Lake Macquarie.png and Lake Macquarie folder     -> Northern Tablelands, New England and Hunter Folder. (Windale under the Lake Macquarie folder will now be another 5 flag region.)

Another note is that folder structure is important for the Murray Sub folders.

**Comment by karakalpak** [comment]
Adding Tassie first, will sort out the rest later

**Comment by Designated** [comment]
> Here are the sorted New South Wales flags in the correct folder structure along with some name fixes
eg (Tumur to Tumut) and moves eg ( Tumut Murray to Tumut Canberra Region)

From the master flag folder there are some moves that must be done.
Kiama and Wollongong -> Illawara Folder
Wagga Wagga -> Murrumbidgee Folder
Queanbeyan -> Canberra Region Folder
Maitland and Newcastle -> Northern Tablelands, New England and Hunter Folder
Grafton -> Mid North Coast -> Clarence Valley Folder (This will be another 5 flag region)
Lake Macquarie.png and Lake Macquarie folder -> Northern Tablelands, New England and Hunter Folder. (Windale under the Lake Macquarie folder will now be another 5 flag region.)

Another note is that folder structure is important for the Murray Sub folders.


Thanks lad, I forgot about the existing ones and that I had to categorize them in the folders as well

**Comment by karakalpak** [comment]
RDA regional flags are ready for NSW. Waiting for the sorted LGAs

**Comment by karakalpak** [comment]
Still waiting 2bh

**Comment by 3Paracetamol** [comment]
Ill just do the QLD regionals for him

**Comment by 3Paracetamol** [comment]
The QLD regionals are sorted, however the naming is a mess. Ill have to rename them, which ill do tomorrow. Ill post an update.
The TAS regionals fall under a single region in Australia, so they can be added.
The NSW Regionals are already sorted, unless you want me to rename them so that all shire suffixes are removed?

**Comment by 3Paracetamol** [comment]
I can also remove the Shire suffixes for WA aswell if you want.

**Comment by karakalpak** [comment]
Tas is added mate. As for the rest sure thanks

**Comment by karakalpak** [comment]
As for the NSW regionals I mean sorted into their respective LGAs instead of regions like "Canberra Region" or "Murrumbigee" which I can't find a an official source for

**Comment by Designated** [comment]
Updated
https://u.pomf.is/dtkgzs.rar

**Comment by karakalpak** [comment]
Kind of like pomf 2bh

**Comment by Designated** [comment]
Who doesn't? 
Easy to use and gets the job done

**Comment by karakalpak** [comment]
rar files a shit though

**Comment by 3Paracetamol** [comment]
[Queensland Regionals.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/320115/Queensland.Regionals.zip)
Here are the Sorted QLD regionals sorted according to the RDA and all City/Region/Shire Suffixes are also removed.
There are also some moves from the master folder that must take place;
Noosa -> Sunshine Coast
McKinlay -> Townsville and North West
Logan -> Logan and Redlands
Ipswich -> Ipswich and West Moreton
Gold Coast -> Gold Coast
Croydon -> Far North Queensland and Torres Strait
Cloncurry -> Townsville and North West
Cairns -> Far North Queensland and Torres Strait
Brisbane -> Brisbane
Toowoomba -> Darling Downs and South West
Townsville -> Townsville and North West
The Folder structure is correct, however the Regions still need their parent flags.

**Comment by karakalpak** [comment]
Thanks everyone
