### ISSUE TITLE
Chile's communes (Ordered)

### ISSUE THREAD

**Issue by RadicalBean** [flaghunters/Extra-Flags-for-4chan#339]
Here are Chile Communes, I remade a bunch of flags for my own orders sake
http://www.mediafire.com/download/pzct3smas3f1be4/Chile.rar

**Comment by karakalpak** [comment]
Why do the provinces all have the same blue-and-red flag?

**Comment by RadicalBean** [comment]
They all have a basic red blue stamp, with the only difference being the text
E.g. https://en.m.wikipedia.org/wiki/File:Logotipo_de_la_Gobernaci%C3%B3n_de_Parinacota.svg

https://en.m.wikipedia.org/wiki/File:Logotipo_de_la_Gobernaci%C3%B3n_de_Arica.svg
