### ISSUE TITLE
Flag for Greater London.

### ISSUE THREAD

**Issue by sersh** [flaghunters/Extra-Flags-for-4chan#34]
Greater London needs a flag.

**Comment by mt117** [comment]
![greater london](https://cloud.githubusercontent.com/assets/11844752/7107972/9a893724-e145-11e4-8315-e26aaf3ec6a7.png)

Is this good?

**Comment by sersh** [comment]
It looks great, thanks!

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks, added!
