### ISSUE TITLE
Kano State flag fix

### ISSUE THREAD

**Issue by GTAnon** [flaghunters/Extra-Flags-for-4chan#341]
Flag used for Kano State, Nigeria is seal on white background instead of their actual flag on Wikipedia, as pointed out by Nigerian anon. Here is fixed flag to add in:

![kano state](https://cloud.githubusercontent.com/assets/18518257/16066400/e2c2d45e-3280-11e6-9040-0abcf3f5ac9f.png)

**Comment by karakalpak** [comment]
Added as the city flag for Kano, instead of the state flag
