### ISSUE TITLE
Vitcoria Regions

### ISSUE THREAD

**Issue by Designated** [flaghunters/Extra-Flags-for-4chan#344]
For Karakalpak 

https://u.pomf.is/ugifcc.rar

**Comment by Designated** [comment]
They all look a bit similar but oh well
Also, since we're going according to this article : https://en.wikipedia.org/wiki/Local_government_areas_of_Victoria

Southwest comes under Barwon South West Region
File : 
![barwon south west](https://cloud.githubusercontent.com/assets/19663668/16072340/00e39784-32fe-11e6-9e23-d22166e622d1.png)


Central Highlands and Goldfields comes under Grampians

Goulburn Valley comes under Hume

Northeast comes under Hume

Western District comes under Western Melbourne 
File : ![western melbourne](https://cloud.githubusercontent.com/assets/19663668/16072352/0c6fa3d6-32fe-11e6-916a-d0389693d404.png)

Wimmera comes under Grampians

The Mallee comes under London Mallee

**Comment by karakalpak** [comment]
Thanks for the help. I'll organise them into their official regions with duplicate flags for Hume and Grampians
