### ISSUE TITLE
Western Australia, Australia + Cocos

### ISSUE THREAD

**Issue by 3Paracetamol** [flaghunters/Extra-Flags-for-4chan#346]
Here are the LGA Flags for Western Australia
Contains 137 Flags
[Western Australia.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/315881/Western.Australia.zip)

I also Found 1 Shire for Cocos (Keeling) Islands 
[Cocos (Keeling) Islands.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/315883/Cocos.Keeling.Islands.zip)

**Comment by karakalpak** [comment]
Added Cocos, will sort Western Australia when RDA regions are ready

**Comment by 3Paracetamol** [comment]
[Western Australia.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/318882/Western.Australia.zip)
Here are the sorted WA regionals by Region according to the RDA

**Comment by 3Paracetamol** [comment]
[Western Australia.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/320408/Western.Australia.zip)
Here is the final version of WA 
Correct Regions and suffixes removed
