### ISSUE TITLE
Ashgabat - Turkmenistan

### ISSUE THREAD

**Issue by MarkoTulska** [flaghunters/Extra-Flags-for-4chan#356]
As far as I can tell this is the only one of Turkmenistan's main six administrative divisions to have a seal or a flag.
![ashgabat](https://cloud.githubusercontent.com/assets/19914312/16091545/0fd15492-332c-11e6-82a4-4ecc137b6e7f.png)

**Comment by karakalpak** [comment]
Made it myself when I saw your comment, closing this issue
