### ISSUE TITLE
North Somerset flag incorrect

### ISSUE THREAD

**Issue by jwginge** [flaghunters/Extra-Flags-for-4chan#370]
the flag for north somerset is essentially the same as the one for somerset except the dragon is yellow and the background is a dark, grassy green. I've only seen the flag flown above the local council building but will try to get a picture of it for proof for you guys.

**Comment by karakalpak** [comment]
Any proof that says that's the flag of North Somerset, though?

**Comment by jwginge** [comment]
Well, we don't really have an official flag. But it's the flag that flies above our council building so its as official as you'll get. At the moment you guys are using the North Somerset logo, not the flag.

**Comment by karakalpak** [comment]
I'd say logo's more official than a flag that's just there 2bh

**Comment by jwginge** [comment]
I wouldn't. It's above the council building so like I said, it's as official as you'll get. The logo looks awful when it's shrunk down to the size used for the flags on /int/, /pol/ etc anyway.

**Comment by Storm-Ryder** [comment]
a logo is not a flag fam,

**Comment by karakalpak** [comment]
@Storm-Ryder Quite a lot of flags in the extension (maybe half, or even more) are logos, simply because they're official and the regions they represent lack a flag.

**Comment by karakalpak** [comment]
Any updates?
![image](https://cloud.githubusercontent.com/assets/17495420/16334930/789f9176-3a36-11e6-8a88-7705238e2600.png)

**Comment by karakalpak** [comment]
Closing this for now, please create a new issue if there's any updates
