### ISSUE TITLE
Support for other browsers

### ISSUE THREAD

**Issue by mt117** [flaghunters/Extra-Flags-for-4chan#38]
https://crossrider.com/developers
This can be used to import Greasemonkey / Tampermonkey scripts to major browsers like Internet Explorer

I can test it when i get home 

Another 

http://kangoextensions.com/

**Comment by mt117** [comment]
I can test it when i get home
there is also one for Yandex
https://greasyfork.org/en/scripts/by-site/yandex.ru

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Good busy. I'm on Linux so I can't test it on IE.

**Comment by mt117** [comment]
Wasn't able to test it 
IE wont download for some reason


I will make a thread later and have someone else test it

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Seems to be no more progress. Won't fix.
