### ISSUE TITLE
Australian Capital Territory, Australia

### ISSUE THREAD

**Issue by 3Paracetamol** [flaghunters/Extra-Flags-for-4chan#380]
[ACT.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/323472/ACT.zip)
Here are the LGA equivalent regional flags for Canberra, as shown by here
https://rda.gov.au/files/rda_map_act.pdf
and here
https://www.accesscanberra.act.gov.au/app/answers/detail/a_id/246/~/act-community-councils
Note that Mitchell is paired with Gungahlin so there isnt a regional for this

Also for Karakalpak, these regionals belong in the Australian Capital territory region so folder structure should go like this
Aus -> Australian Capital Territory -> Australian Capital Territory Region -> etc
http://www.rdaact.org.au/

This is optional as along with TAS and NT they only have 1 region, and looks kinda funny with the repetitious phrases.

Another thing, under NT the folder MacDonnell should be deleted and under NSW->Sydney Region the Sydney folder should be deleted also.

I will be doing New Zealand's LGA equivalent regionals next.

**Comment by karakalpak** [comment]
Will do tomorrow I guess
