### ISSUE TITLE
UK flags incorrect

### ISSUE THREAD

**Issue by Anonymous7432** [flaghunters/Extra-Flags-for-4chan#381]
A large number of flags from the UK (Northern Ireland in particular) have been deleted and replaced with completely irrelevant government logos. Logos are simply that and no more. They are not flags, and they are not intended to be used for that purpose. Using council logos in place of officially recognised regional flags is absurd.

The changes in this commit need to be completely reviewed (https://github.com/flaghunters/Extra-Flags-for-4chan/commit/2b150a740fe5d922eac504951406692a3b233fe5). Not only has it wrongly replaced flags but it has also deleted them in a seemingly arbitrary fashion; even the flag of Yorkshire has been deleted.

There are so many errors that I would strongly suggest undoing that entire commit and taking each item issue by issue, its quite severely damaged the current UK flag list.

**Comment by karakalpak** [comment]
What would you suggest? (government regions will remain and I can add the deleted UK regions back - specifically kept a folder open for restoration purposes.).

**Comment by karakalpak** [comment]
>Logos are simply that and no more. They are not flags, and they are not intended to be used for that purpose. Using council logos in place of officially recognised regional flags is absurd.
Council logos are used when there's no other option (i.e. arms or a flag). As long as they're legit administrative divisions they won't be removed

**Comment by karakalpak** [comment]
>Northern Ireland in particular

>their governmental features were abolished and replaced with twenty-six unitary authorities

I feel that for the purpose of organisation and sorting using the flags/coats of arms/logos of modern administrative divisions is optimal. Same goes for Scotland and Wales.

**Comment by Anonymous7432** [comment]
As you say, the most important thing is to re-add the deleted flags. That will resolve mostly resolve the issue. 

I don't personally see the need for district council logos. You will never see them being used for the purposes of regional representation in the UK. However, if you really want them added to the list then I suppose there isn't any particular harm having them there (unless of course other flags are being deleted, which was one of the main problems with this commit). So by all means keep them, but make sure the deleted flags are present also.

**Comment by karakalpak** [comment]
How do you suggest they be sorted?

**Comment by Anonymous7432** [comment]
This is why I originally suggested that the commit should be undone in its entirety. Once the flag list is back to its original state pre-commit then the new flags can be added in an orderly process.

**Comment by karakalpak** [comment]
![image](https://cloud.githubusercontent.com/assets/17495420/16200393/ba06c002-373f-11e6-9711-684a12de0027.png)
I have the flags here and I know exactly which folders they were in before the commit. Do you suggest any changes to that however? (e.g. lumping the ridings in Yorkshire, or even the modern ceremonial counties)

**Comment by karakalpak** [comment]
>You will never see them being used for the purposes of regional representation in the UK.

There's quite a few posters who used the council logos from the start. Borders anon for example.

**Comment by Anonymous7432** [comment]
Can't think of any particular changes, as far as I am aware they were correctly organised before the commit.

Ridings should be in Yorkshire's folder. Provincial flags (eg Wessex, Mercia, East Anglia etc) dont fit so easily into the new system, however they are all valid flags. I think before they werent in any descending lists (if thats the right term), they were simply UK-England-Wessex for example. That should be kept the same if it wasnt already

**Comment by karakalpak** [comment]
>Ridings should be in Yorkshire's folder

What about the East Riding? And the ceremonial counties?

**Comment by Anonymous7432** [comment]
But those arent the only ones; all of Northern Ireland's need to be re-added. Deleting the NI county flags is like removing any other county from the UK list

**Comment by karakalpak** [comment]
>But those arent the only ones; all of Northern Ireland's need to be re-added. Deleting the NI county flags is like removing any other county from the UK list

I am aware, they need to be remade because they had a shitty gloss. Same goes for everything outside of England.

UK and Sweden are reminders that there's no official flag policy so I will be making an issue for that.

**Comment by Anonymous7432** [comment]
You'll have to explain further as to why East Riding is a problem, as far as I'm aware its no different to any of the other Riding's. 

Ceremonial counties is a similar situation to provincials; theyre all valid and official but dont fit well into the extension's system. Re-add them as they were and they can be addressed in other issues in the event that complaints/problems arise. Case-by-case basis is best because each is different. For instance Cumberland is within Cumbria, Sussex is recognised but includes East+West Sussex and so on

**Comment by karakalpak** [comment]
>You'll have to explain further as to why East Riding is a problem, as far as I'm aware its no different to any of the other Riding's.

It's both a ceremonial county and a riding of the historical county of Yorkshire. The best solution at the moment as I see it will be to include it in both the England folder and the Yorkshire folder.

**Comment by Anonymous7432** [comment]
Understood. However, I disagree with including it in the England folder. It should be placed solely in the Yorkshire folder; it wouldnt be correct to have it outside the Yorkshire category.

**Comment by karakalpak** [comment]
For the moment I'll include all ceremonial counties and historical counties one step below England

**Comment by Anonymous7432** [comment]
In case there's any confusion, dont let the fact Yorkshire is described as a 'historic' county make you think it any less valid. Its historic in name only and is fully recognised as a region.

This applies to most of the 'historic' regions in the UK. That title can be very misleading.

**Comment by karakalpak** [comment]
I'm very much aware of that. For the purpose of tidyness I figured that the ideal solution would be to use the regions used primarily in administration.

**Comment by Anonymous7432** [comment]
All well and good, but when assembling this list it must be remembered that removing or avoiding flags which dont fit easily into the system does not achieve the original purpose of this extension. The deletion of Yorkshire was a prime example of removing a very valid and important flag (Yorkshire being one of the main regions of the UK) for the sake of this tidyness. I completely agree that the extension needs order, but in future commits need to be more careful.

**Comment by Anonymous7432** [comment]
As for Northern Ireland and so on I understand now; I didnt know they were being reglossed so just assumed theyd been deleted permanently

**Comment by karakalpak** [comment]
Only Caernarfonshire and Meirionnydd have been added back for Wales and Caithness and Ayrshire for Scotland for the main reason that other shire flags weren't there in the first place. Depending on the verdict I'll make them if I have time.
