### ISSUE TITLE
Austrian Municipal Flags are Vertical 

### ISSUE THREAD

**Issue by AvidFlagHunter** [flaghunters/Extra-Flags-for-4chan#382]
I've looked at Austian municipal flags only to discover that most of them are vertical. Should the flags be made in the same 16x11 format or should they be in 11x16 so that they look like the actual flags?

**Comment by karakalpak** [comment]
They're similar to the Slovene municipality flags then. I usually use Photoshop to alter them.

**Comment by AvidFlagHunter** [comment]
Ok thanks. I'll do that then.
