### ISSUE TITLE
Bath UK

### ISSUE THREAD

**Issue by Anonymous7432** [flaghunters/Extra-Flags-for-4chan#388]
The correct Bath, Somerset, UK flag
![bath](https://cloud.githubusercontent.com/assets/18105912/16338700/3ce082aa-3a16-11e6-9657-df7c5f950585.png)
has been deleted and replaced with the flag for Bath, Maine, USA please revert

**Comment by karakalpak** [comment]
Whoops

**Comment by LenticCatachresis** [comment]
JUST

**Comment by karakalpak** [comment]
honest mistake :^)
