### ISSUE TITLE
Boxford, MA flag

### ISSUE THREAD

**Issue by JerryTheOctopus** [flaghunters/Extra-Flags-for-4chan#389]
![boxford](https://cloud.githubusercontent.com/assets/20131190/16345004/9cc76e76-3a0d-11e6-8990-79806f0ff04f.png)
I would like to request a Boxford, MA regional flag. I have already made the 16x11 flag, all it needs is a gloss layer, because I do not have Photoshop on my computer.

**Comment by JerryTheOctopus** [comment]
![boxford](https://cloud.githubusercontent.com/assets/20131190/16345446/eb2bd578-3a0f-11e6-806e-cceb3eb7f32f.png)
Just made a minor edit.

**Comment by JerryTheOctopus** [comment]
![boxford v2](https://cloud.githubusercontent.com/assets/20131190/16349926/7521f262-3a29-11e6-9bf5-ab2e4a6c05ef.png)
Now with gloss.

**Comment by karakalpak** [comment]
Made my own anti-aliased version
