### ISSUE TITLE
Quebec city flag doesn't work

### ISSUE THREAD

**Issue by xk-chan** [flaghunters/Extra-Flags-for-4chan#390]
Now I don't know about you, but the flag for the city of Québec doesn't work with the extension. Maybe it has to do with both the provincial and the city flag sharing the same name?

**Comment by xk-chan** [comment]
^Sharing the same filename of course.

**Comment by karakalpak** [comment]
It does, I was waiting to sort it into a region. Will add a (city) label until the regions get flags
