### ISSUE TITLE
No Libyan Flag

### ISSUE THREAD

**Issue by zatareater** [flaghunters/Extra-Flags-for-4chan#391]
Hey I just got this script and it asked me to pick my country but there is no Libya

Thanks

**Comment by karakalpak** [comment]
Libya doesn't seem to have official flags or arms. Are there any?

**Comment by zatareater** [comment]
there are

Fezzan
https://en.wikipedia.org/wiki/Fezzan
https://upload.wikimedia.org/wikipedia/commons/e/e9/Flag_of_Fezzan-Ghadames.svg

Cyrenaica
https://en.wikipedia.org/wiki/Cyrenaica
https://upload.wikimedia.org/wikipedia/commons/8/87/Flag_of_Cyrenaica.svg

Tripolitania
https://en.wikipedia.org/wiki/Tripolitania
https://upload.wikimedia.org/wikipedia/commons/a/af/Flag_of_Tripoli_18th_century.svg

and our coat of arms
https://en.wikipedia.org/wiki/Coat_of_arms_of_Libya

**Comment by karakalpak** [comment]
The flags of Fezzan and Tripolitania are historical, and Cyrenaica's flag is self-declared. Are there any official flags or seals of the cities or districts?

**Comment by zatareater** [comment]
I don't think the districts have any official flags currently 

those are the districts tho i don't know of any flags/seals for them
https://en.wikipedia.org/wiki/Districts_of_Libya

Thanks for your time anyways

**Comment by karakalpak** [comment]
There isn't a way to add it to the list without it having any flags mate.

**Comment by karakalpak** [comment]
I used the seal from http://www.tripoli.gov.ly/demo/ftb/ for Tripoli. Wikipedia says the green on the sails of the old seal represented Gaddafi's green book and it seems to have been recoloured, so I'll trust this for now.
