### ISSUE TITLE
Flag of the city of Lloydminster, Canada

### ISSUE THREAD

**Issue by GTAnon** [flaghunters/Extra-Flags-for-4chan#392]
Tbh I mostly did this to see how it would be filed, from Wikipedia:

> Lloydminster is a Canadian city which has the unusual geographic distinction of straddling the provincial border between Alberta and Saskatchewan. Unlike most such cases (such as Texarkana and Kansas City), Lloydminster is not a pair of twin cities on opposite sides of a border which merely share the same name, but is actually incorporated by both provinces as a single city with a single municipal administration.

tl;dr - It's a single city that is incorporated in both Alberta and Saskatchewan at the exact same time.

The most obvious way of going about it is just filing it under both provinces and setting your provincial level flag differently depending on which side of the provincial border you're at, but that ignores the fact that you're also in a city incorporated by the other province so rip

![lloydminster](https://cloud.githubusercontent.com/assets/18518257/16360044/a7156dd4-3b1a-11e6-8bf7-9c1ef00167fd.png)

**Comment by karakalpak** [comment]
I'll put it under both provinces, no problem with that. Plenty of American cities already exist in different county folders
