### ISSUE TITLE
no more logos in place of flags

### ISSUE THREAD

**Issue by nomorelogos** [flaghunters/Extra-Flags-for-4chan#393]
using logos in place of actual flags was a foolish idea. first of all it doesn't make any damn sense, and secondly it's extra FLAGS for 4chan, not a few flags but primarily solid-colour backgrounds with logos or text on them for 4chan. what happened to the no meme flag rule? none of the logo flags actually exist in real life. a prime example of this is [this](https://github.com/flaghunters/Extra-Flags-for-4chan/blob/master/flags/Canada/British%20Columbia/Greater%20Vancouver%20Regional%20District/Electoral%20Area%20A/University%20Endowment%20Lands.png) in place of [this](http://www.universityendowmentlands.gov.bc.ca) (the "UEL" in the top left.)

i already know what karakalpak thinks about this, but i want to hear what pk thinks. pk, apparently you approved of this stupid thing months ago. i urge you to rethink that.

also, i know it might take a bit of time to remove every single non-flag. however i know there are people with enough time and autism to do so.

**Comment by karakalpak** [comment]
For fuck's sake

**Comment by karakalpak** [comment]
>none of the logo flags actually exist in real life
Nice try, but that's not true

**Comment by karakalpak** [comment]
>i know it might take a bit of time to remove every single non-flag

You are aware of how the flags are organised, yes?
