### ISSUE TITLE
Kamchatka Krai Districts + Koryak Okrug Districts + Yelizovo

### ISSUE THREAD

**Issue by AvidFlagHunter** [flaghunters/Extra-Flags-for-4chan#395]
[Kamchatka Krai Districts.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/333868/Kamchatka.Krai.Districts.zip)
The Kamchatka Krai is divided into these districts.
![koryak okrug](https://cloud.githubusercontent.com/assets/16618633/16365395/7292cc82-3bc4-11e6-9828-523187b651df.png)
And into the Koryak Okrug
[Koryak Okrug Districts.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/333870/Koryak.Okrug.Districts.zip)
And the Koryak Okrug is divided into these districts.
![yelizovo](https://cloud.githubusercontent.com/assets/16618633/16365400/903793bc-3bc4-11e6-9467-501e7f5bda80.png)
Yelizovo is a city that has an adminstrative status equal to that of districts.

**Comment by karakalpak** [comment]
Already have my own flags for Russia mate
