### ISSUE TITLE
Proposal for better flag selection system (so people don't have to use icon flags if they don't want to)

### ISSUE THREAD

**Issue by karakalpak** [flaghunters/Extra-Flags-for-4chan#412]
This is a proposal for revamping the flag selection system, based on a problem that some users have with the English flag hierarchies.

Pretty sure icon flags have been allowed since forever. I know I used them even before I started making flags. But two UK posters are upset about the inclusion of flags of CoAs on a white background and are blaming me for this (requesting my ousting) and saying that Brits don't want my changes. 

While I can understand their sentiment I must say that the first UK flag made with a council icon was by Surrey anon for himself, and that Guildford anon along with Olathe anon were the ones who tried to fill up the counties of England. It was Brits themselves who came up with the idea; I just redid many of the flags, and counties that I started on without prior flags being added by them number few. 

Pics related:
![image](https://cloud.githubusercontent.com/assets/17495420/16551076/53290e74-41e6-11e6-8e5f-a1cfa9cec7dd.png)
![image](https://cloud.githubusercontent.com/assets/17495420/16551117/b0bb182a-41e6-11e6-83aa-204f8c69665d.png)

Post on /brit/ and opinions:

![tmp_20508-2016-07-04 14 01 161342428897](https://cloud.githubusercontent.com/assets/17495420/16551964/3713d45a-41f8-11e6-9b36-4a1a65d7f5b2.png)
![tmp_20508-2016-07-04 14 03 14-474975346](https://cloud.githubusercontent.com/assets/17495420/16551993/754c4afe-41f8-11e6-9d49-11a390205d1d.png)
![tmp_20508-2016-07-04 14 02 59212746372](https://cloud.githubusercontent.com/assets/17495420/16552033/80fae306-41f8-11e6-8841-3865024aa65f.png)

And here's the opinions in /flag/ which is how I've come to know of this:

![tmp_20508-2016-07-04 14 05 09-1560238103](https://cloud.githubusercontent.com/assets/17495420/16552076/eb940e36-41f8-11e6-80ce-667fff723c6d.png)
![tmp_20508-2016-07-04 14 04 441873744623](https://cloud.githubusercontent.com/assets/17495420/16552079/f7d497ba-41f8-11e6-9f72-6a5ee6b85c97.png)

On the other hand:

![image](https://cloud.githubusercontent.com/assets/17495420/16553701/ad92dc94-41fc-11e6-96a0-1fe3ee2cdb75.png)
![image](https://cloud.githubusercontent.com/assets/17495420/16553752/fb7cd162-41fc-11e6-8b68-abce901370f8.png)

Now I think quite some Brits want to use the council logos and coats of arms. But obviously some don't. So I'd like to turn this into an opportunity to request a change to the flag selection system that I think will solve all these problems.

After the selection of regional flags with the current UI I think users should be allowed to choose which ones that they can show. Ergo, if someone selects the flags England>Lancashire>Fylde>Lytham St Annes>St Annes-on-the-Sea, they can choose to show just England, Lancashire, and St Annes instead of all five regional flags. 

So yeah I can't see any downsides to such a system; Brits who don't want to show their icon flags don't have to and those who do are allowed to. Same of course goes for those from other countries.

**Comment by MarkoTulska** [comment]
Agree with this tbqh

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
At this point that is impossible, the script doesn't know what flags are non-flags.
Or do you mean alternative paths for flags (duplications)?

**Comment by karakalpak** [comment]
I mean just checkbox selection after selecting your flags. So you can manually select which ones to display after using the current selection system

**Comment by karakalpak** [comment]
I mean checkbox selection for which flags a user would like to display. Say you're done selecting your flags through the current dropdown menu system; you'd then be presented with a new menu displaying the flags you've selected, and you can choose which ones to display manually. 

Duplications are a no-no IMO since it would just massively mess things up especially for countries like Portugal and the US.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Just your own?

**Comment by karakalpak** [comment]
Yeah, the ones you selected

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
But you'd still see others.

**Comment by karakalpak** [comment]
Think the problem is people not wanting to display icon flags as their own flags, not having to see other people's icon flags

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
tbh I don't think that would satisfy anyone, do we have confirmation anyone really even wants that?
