### ISSUE TITLE
Northern Ireland.png is wrong

### ISSUE THREAD

**Issue by FS1NG** [flaghunters/Extra-Flags-for-4chan#42]
Northern Ireland.png in the UK is Saint Patricks flag instead of the Ulster Banner
![northern ireland](https://cloud.githubusercontent.com/assets/10171329/8813024/e66876c2-2ff7-11e5-8620-c08834414ca6.png)

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Not sure which one should be used, but I updated it, thanks.

**Comment by FS1NG** [comment]
Northern Ireland.png is the Ulster Banner, the areas only ever official flag. Ulster.png is the areas Irish county flag as an alternative, it makes sense to keep both especially when the red hand is hard to see in Northern ireland.png

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
How should I call them if we use both?

**Comment by FS1NG** [comment]
Theyre fine as they are as long as you replace Northern Ireland.png with the one I uploaded.
