### ISSUE TITLE
Punta del Este, Maldonado Department, Uruguay

### ISSUE THREAD

**Issue by WhatIsThisImNotGoodWithComputers** [flaghunters/Extra-Flags-for-4chan#423]
Someone requested this flag through mail.
But I cannot confirm the flag anywhere.
Can anyone do this or point me in the right direction?
![punta del este](https://cloud.githubusercontent.com/assets/2182943/16714597/9faa6c98-46c8-11e6-9cad-94f017da99b4.png)

**Comment by karakalpak** [comment]
It's based on the icon from http://todopuntadeleste.com.uy/el-municipio-de-punta-del-este-continua-apostando-a-la-capacitacion-por-y-para-el-turismo/

Seems legit, I'll add it
