### ISSUE TITLE
Change "Jakarta" to "Jakarta Raya"

### ISSUE THREAD

**Issue by volcbs** [flaghunters/Extra-Flags-for-4chan#43]
Since ipinfo use "Jakarta Raya" instead "Jakarta", Jakarta region should use "Jakarta Raya" instead "Jakarta" so people wont confuse with it.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Wikipedia says the province is called Jakarta, what is the official one? I'd prefer to use official (local or international). If it should be Raya, should more of them be renamed to X Raya?

**Comment by volcbs** [comment]
Well actually it's called "DKI Jakarta" (Daerah Khusus Ibukota Jakarta/Special Capital Region of Jakarta).
Also we have 2 special provinces include Jakarta, it's Daerah Istimewa Yogyakarta (DIY) ("Special Region of Yogyakarta").


The problem seems like not only happens to us tho. France-anon also had the same problem (at that 2 days ago thread)

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
So, what do we do with this?

**Comment by volcbs** [comment]
Change it to DKI Jakarta and Daerah Istimewa Yogyakarta (DIY) would be nice tbh.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Terribly sorry, can't believe I forgot about this.
Updated them.
