### ISSUE TITLE
Michigan Flags

### ISSUE THREAD

**Issue by CryHarder** [flaghunters/Extra-Flags-for-4chan#436]
I should be able to set 5 flags.I'm only able to set flags in the following order United States-Michigan-Kent County-Wyoming.The flags for this county should be set-up as the following:United States-Michigan-Kent County-Wyoming Township-Grand Rapids.If this can be resolved,it'd be much appreciative.
Wyoming is a township-city with in Grand Rapids Metro area.

**Comment by karakalpak** [comment]
Won't be changed, city limits are used.
