### ISSUE TITLE
Adding Scottish flags

### ISSUE THREAD

**Issue by FS1NG** [flaghunters/Extra-Flags-for-4chan#44]
Two Scottish flags

Edinburgh

I was going to add the Outer Hebrides but I just realised that Western Isles should be named Outer Hebrides

**Comment by FS1NG** [comment]
![426px-flag_of_edinburgh svg](https://cloud.githubusercontent.com/assets/10171329/8948023/3454af0c-359a-11e5-8029-0d99000f3e6a.png)

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Added Edinburgh, thanks.
What should I do with Western Isles, rename or duplicate? Wikipedia lists both as correct, do you know which one is official, is it Outer Hebrides?

**Comment by FS1NG** [comment]
"In the past the Outer Hebrides were often referred to as the Long Isle (Scottish Gaelic: An t-Eilean Fada). Today, they are also known as the Western Isles although this phrase can also be used to refer to the Hebrides in general."

Thats what wikipedia says and how Ive heard it been used, I guess either two different entries with the same flag or just the Outer Hebrides would make sense. Outer Hebrides is the official name though and is specific to the region the flag represents.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Fixed.
