### ISSUE TITLE
Saguenay, Quebec Boroughs

### ISSUE THREAD

**Issue by AvidFlagHunter** [flaghunters/Extra-Flags-for-4chan#443]
[Saguenay Boroughs.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/420256/Saguenay.Boroughs.zip)

**Comment by karakalpak** [comment]
Can you provide a source for these?

**Comment by karakalpak** [comment]
I have added Chicoutimi made from a logo different from yours. What are the sources for the other two? So I can redo them.

**Comment by AvidFlagHunter** [comment]
I found them through their old websites that were taken down. I can send the links when I'm home.

**Comment by AvidFlagHunter** [comment]
http://wayback.archive.org/web/20011202181301/http://ville.labaie.qc.ca/
This is La Baie's source.

**Comment by karakalpak** [comment]
Added with the logo isolated from the background.
