### ISSUE TITLE
Richland County, South Carolina Flag

### ISSUE THREAD

**Issue by MasterAutismo** [flaghunters/Extra-Flags-for-4chan#445]
![richland county](https://cloud.githubusercontent.com/assets/18697669/17752925/094ca5d0-649c-11e6-93ab-77a8f999dfe4.png)

Based on seal at Richland County's official website: http://www.richlandonline.com/

Also Columbia should be moved to Richland County's folder as it is the county seat of said county.

**Comment by karakalpak** [comment]
Added with proper aspect ratio
