### ISSUE TITLE
delete this

### ISSUE THREAD

**Issue by RadicalBean** [flaghunters/Extra-Flags-for-4chan#446]
Uploading here what I've made until, I have very little time these days so It will be a while to finish these, so instead I'm uploading what I've done already so another anon can pick up the cord
http://www.mediafire.com/download/9t984sgdlqut5xz/Japan+%28Undone%29.rar

**Comment by karakalpak** [comment]
>suffixes

Too lazy to rename them tbh, will do when I get to Japan

**Comment by RadicalBean** [comment]
Whta suffixes m8

**Comment by karakalpak** [comment]
"Town", "City", etc

**Comment by RadicalBean** [comment]
Shouldnt it have those?
Wasnt it decided to anglicize the suffixes?

**Comment by karakalpak** [comment]
On second thought reopening this and will close when either I get around to doing it or someone else does

**Comment by RadicalBean** [comment]
Oh wait
I get it nevermind

**Comment by karakalpak** [comment]
Suffixes are Anglicised but most lowest-level divisions (and all divisions composed solely of one settlement) use none

**Comment by RadicalBean** [comment]
I blindly copied what was on crwflags (whoops)

**Comment by karakalpak** [comment]
I have made and added all municipalities of Tokyo, Saitama Prefecture, Chiba Prefecture, and Kanagawa Prefecture. Will finish the remainder of Kanto next.

**Comment by 3Paracetamol** [comment]
Mediafire link is broken and Kar is gone.
Will you reupload what you've made?
Will you finish what you have started so I can add it?
Ill close the issue otherwise.

**Comment by RadicalBean** [comment]
The link works fam, dont know what youre talking a bout

**Comment by MasterAutismo** [comment]
I can't delete this, do you just want it closed?

**Comment by MasterAutismo** [comment]
moved to #499
