### ISSUE TITLE
Adding Welsh flags

### ISSUE THREAD

**Issue by dd673** [flaghunters/Extra-Flags-for-4chan#45]
Hopefully you could add these in :)

Anglesey
![anglesey](https://cloud.githubusercontent.com/assets/13989476/9509457/a2137360-4c57-11e5-807e-58bf86d04d49.png)

Flintshire
![flintshire](https://cloud.githubusercontent.com/assets/13989476/9509481/f34e6bf4-4c57-11e5-86dc-474e55e0b636.png)

Glamorgan
![glamorgan](https://cloud.githubusercontent.com/assets/13989476/9509483/fc90ab96-4c57-11e5-9ebc-21278bc288ef.png)

Gwynedd
![gwynedd](https://cloud.githubusercontent.com/assets/13989476/9509484/07f63ef6-4c58-11e5-82a1-1e2be88684c4.png)

Meirionnydd
![meirionnydd](https://cloud.githubusercontent.com/assets/13989476/9509485/0e31ffda-4c58-11e5-8fab-91e5a369f093.png)

Monmouthshire
![monmouthshire](https://cloud.githubusercontent.com/assets/13989476/9509488/164dcb68-4c58-11e5-85e2-941e2ca9705c.png)

Pembrokeshire
![pembrokeshire](https://cloud.githubusercontent.com/assets/13989476/9509491/1ff4cb12-4c58-11e5-9965-6ac0eb62769e.png)

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks for the flags, they look awesome.
I've renamed Anglesey to Isle of Anglesey, Monmouthshire was in there already.
