### ISSUE TITLE
Adlersky City District, Russia

### ISSUE THREAD

**Issue by 3Paracetamol** [flaghunters/Extra-Flags-for-4chan#455]
Here is the flag for Adlersky, Which is a City district in Sochi, in Krasnodar Krai.
![aldersky](https://cloud.githubusercontent.com/assets/19728169/18436556/5cdc6f82-793c-11e6-9d4e-3159aedf0d38.png)
Proof https://ru.wikipedia.org/wiki/%D0%90%D0%B4%D0%BB%D0%B5%D1%80%D1%81%D0%BA%D0%B8%D0%B9_%D1%80%D0%B0%D0%B9%D0%BE%D0%BD
If maybe you can find a way to add me as a collaborator to extra flags, that would be very helpful.
I can start adding in the odd flag here and there of my own. 
Based karakalpak

**Comment by 3Paracetamol** [comment]
![aldersky](https://cloud.githubusercontent.com/assets/19728169/18436689/f83c477c-793c-11e6-80ce-44190fe4f0b8.png)
Here is a better version I feel

**Comment by karakalpak** [comment]
There is no accurate English source for Russian flags

**Comment by karakalpak** [comment]
(There is no accurate English source for Russian administrative divisions beyond the 84 federal subjects either)

**Comment by 3Paracetamol** [comment]
I assume you sometimes lurk secretly ;)
But the russian in the thread just called it "Adler"
See http://boards.4chan.org/int/thread/64763737/flagtism-wayside-edition#p64785241

**Comment by karakalpak** [comment]
I don't lurk, I've left 4chan

**Comment by karakalpak** [comment]
You can find me on Yli :^)

**Comment by karakalpak** [comment]
Also Russian Wikipedia says "rayon" and Geraldika uses the -sky form so I'm leaving it as is

**Comment by 3Paracetamol** [comment]
Alright buddy, enjoy your 4chan free life I guess :(

**Comment by karakalpak** [comment]
Alri lad

**Comment by 3Paracetamol** [comment]
Sorry to annoy with autistic shit. But you have become sort of a phantom legend since you left. OPLK has made these shitty 'commandments' 
![1473723470753](https://cloud.githubusercontent.com/assets/19728169/18456857/cec770d2-7997-11e6-86ee-2d153cdb5cae.png)
and he got the regulars to sign, its kinda gay, I know. But people want you to sign. Not your real signature of course just anything really.
![1473723561761](https://cloud.githubusercontent.com/assets/19728169/18456891/03690e86-7998-11e6-83cf-bc00fd4eb6b0.png)
Thanks again. Totally up to you.

**Comment by karakalpak** [comment]
Don't care 

Leave it blank or something.

**Comment by 3Paracetamol** [comment]
Alri, sounds good
