### ISSUE TITLE
New showcase image for the frontpage.

### ISSUE THREAD

**Issue by 3Paracetamol** [flaghunters/Extra-Flags-for-4chan#458]
The current image on the front page to showcase the extension is atrocious and ugly.
So I made a new one
For PK
![untitled1](https://cloud.githubusercontent.com/assets/19728169/19017853/17b9caa2-8897-11e6-8b1c-3ff5d008af07.png)

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks, good change.
Will take some time to update I think.
