### ISSUE TITLE
The future of Extra Flags

### ISSUE THREAD

**Issue by WhatIsThisImNotGoodWithComputers** [flaghunters/Extra-Flags-for-4chan#459]
For new ventures coming for me, I won't be able to keep the backend of extra flags up any more in the near future.

I'm not quite sure about the current userbase of Extra Flags, about how many people use it. The flag threads on /int/ seem to be non-stop shitposting so that's why I'm asking here;
Is there anyone who wants this thing to keep going? If so, we'll need to talk about possible ways to keep it alive.

**Comment by Malte-Soeren** [comment]
By saying you wont be able to keep the backend of extra flags up do you mean the database that stores flags and post numbers? (I dont know too much that about that stuff).

If you have a solution I would help (but I dont have much time as I just started getting my bachelors degree) because I like seeing and collecting extra flags.
But if it's too much of a hassle I surely won't cry after those flag threads and I have downloaded all flag Icons so the only loss would be not seeing them on 4chan anymore.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
For fun projects I rented a dedicated server and one of the projects running on it is Extra Flags, but I'm working on some new things which cannot coexist with other things on the same server and I'm not going to rent another server just to keep old projects or Extra Flags in the air.

There's a few things we can do but the best option would probably be to make it not dependent on an external server. To do this we could append tags to the end of the username instead of selecting a flag, so one would have to post with "Anonymous [NB]" to get the Noord-Brabant Extra Flag for example, or "Anonymous [NB|BR]" to get Noord-Brabant and Breda. The downside of this would be that you'd have an identifier at the end of your name for people who do not use the script.

Another way would be to beg Hiroyuki for an extra field for input to be used by scripts which does not show to users, but I don't think he'd be too willing to implement it.

**Comment by RadicalBean** [comment]
Maybe you could set up a patreon/donating thing to pay for an extra server, I don't know the costs but I have some money I could give you

**Comment by 3Paracetamol** [comment]
Even though the /flag/tism threads are filled with shitposting, its an effort to keep the thread Bumped. It became a full time general in February, and the amount of people on /int/ alone who use extra flags has increased to around 200 people every week with the peak usage at 260 unique people, with that number being larger on /pol/. Besides the low quality of posts on the thread. We still try to help and be welcoming to any new flag users by helping with installation, troubleshooting and addition of new flags to the database. 
The database's size and accompanied website with helpful graphics took a lot of time and is a community achievement that will be a shame, if lost.
How much interest will it take to keep this project in existence? and will you also scrap the flaghunter site as well?

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
First of all, I really don't mind shitposting, personally, I don't do anything else. But the thread doesn't always seems to to flags. That's why I thought it would be better to ask here.
As for amount of users, I have virtually no insights into that, so you probably know more about that than me, I assume with usage of the regional flag hunter script.

All projects related to 4chan which require hosting would be dropped, the flaghunter, flagratio, int archive, /ref/, carib bumper and of course extra flags. The Jenkins job which did the FlagSlave pushes to GitHub is already shut down.

Extra flags itself isn't actually very heavy at all, and not big either.
![2016-10-16--1476632704_984x115_scrot](https://cloud.githubusercontent.com/assets/2182943/19418669/cf902770-93c8-11e6-9534-abbdaa9e0c29.png)

For my new projects (eCommerce) I need to turn logging on so that's why it's not unifiable with Extra flags. I could easily slap Extra Flags and the Flaghunter on the cheapest VPS https://www.ovh.nl/vps/vps-ssd.xml €3,62 if we could get it funded. Looking at Patreon for the possibilities.
FlagRatio depends on my int archive (https://archive.whatisthisimnotgoodwithcomputers.com/int/statistics/countries/) because the archive counts the posts from my int archive and sp and pol from 4plebs (4plebs admin made the counting page).
So to include FlagRatio, would mean to include the int archive, that means the 6 euro or 12 euro dedi from here https://www.kimsufi.com/nl/servers.xml

**Comment by 3Paracetamol** [comment]
Yes, I did get that number from the regional flag hunting script. If /int/ archive, /ref/ and flagratio went and only flaghunter and extra flags remained im sure people can live with that. But if you need funding for a small rental server for those 2 things only for €3.62 (5.21 AUD) per month. I can donate for 2 months until something else is figured out.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks for your offer, but going to do it in another way. On nginx there seems to be a way to separate the logging.
So when my new project goes up I'll take the archive (and flagratio) down first - that should free up enough resources.
Before I'll take down extra flags and the flaghunter I'll reopen this issue and then I'll hope your offer still stands at that time.
