### ISSUE TITLE
LA flag

### ISSUE THREAD

**Issue by sapporo1** [flaghunters/Extra-Flags-for-4chan#46]
if NYC has a flag, you should make one for LA, for california shitposting

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
I don't make the flags (I can't tbh), if you can make it, I'll add it.

**Comment by sapporo1** [comment]
sure, I can do that

**Comment by sapporo1** [comment]
![1436817954177](https://cloud.githubusercontent.com/assets/14283126/9921245/681b67dc-5c90-11e5-930d-77300db4c4a3.png)

this should be it

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Los Angeles is in, thanks for making it.
