### ISSUE TITLE
More flags for Finland

### ISSUE THREAD

**Issue by SavoBro** [flaghunters/Extra-Flags-for-4chan#460]
(I am new here, i think this project is almost dead but requesting anyways)

I want to request flags for the biggest cities in Northern Savonia, Kuopio,Iisalmi and Varkaus. Thank you

**Comment by Malte-Soeren** [comment]
I made them for you, but I cant add any flags, you need to wait until someone comes back that has the rights to change files
![iisalmi](https://cloud.githubusercontent.com/assets/18237244/19410005/63c5bd4e-92e1-11e6-8558-6d4f9c0f898a.png)
![kuopio](https://cloud.githubusercontent.com/assets/18237244/19410006/63c5e4cc-92e1-11e6-9672-6a7cf887fbfc.png)
![varkaus](https://cloud.githubusercontent.com/assets/18237244/19410007/63cf3b6c-92e1-11e6-8dd3-0252be92feac.png)
as theres just three files i didnt bother putting them into a zip folder

**Comment by SavoBro** [comment]
Thank you very much! I really like them, even though almost all finnish city flags look similiar

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Before I add them wrong, which is which?

**Comment by SavoBro** [comment]
The first one Malte-Soeren listed is: Iisalmi, then Kuopio and the last one is Varkaus
