### ISSUE TITLE
Municipalities of Sonora, Mexico

### ISSUE THREAD

**Issue by MasterAutismo** [flaghunters/Extra-Flags-for-4chan#463]
[Municipalities of Sonora.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/551908/Municipalities.of.Sonora.zip)

Contains 71/72 flags for the municipalities of the Mexican state of Sonora minus the municipality of Nacori Chico which does not have a flag/seal/COA.

Also contains two new city flags for Nogales and San Luis Rio Colorado - these should be filed under their respective municipalities.

**Comment by 3Paracetamol** [comment]
They have been added.
