### ISSUE TITLE
Sweden

### ISSUE THREAD

**Issue by shadilay1996** [flaghunters/Extra-Flags-for-4chan#465]
done (so far)

Blekinge county
Gotland county
Halland county
Jamtland county
Jonkoping county
Kalmar county
Kronoberg county
Ostergotland county
Skane county
Sodermanland county
Stockholm county
Uppsala county
Vasternorrland county
Vastra Gotaland county
[sweden.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/560436/sweden.zip)

**Comment by shadilay1996** [comment]
finished the municipalities, this one contains
Dalarna county
Gavleborg county
Norrbotten county
Orebro county
Varmland county
Vasterbotten county
Vastmanland county
[sweden p2.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/560805/sweden.p2.zip)

**Comment by 3Paracetamol** [comment]
All Municipalities have been added. Thanks For the help.
