### ISSUE TITLE
Czechia

### ISSUE THREAD

**Issue by shadilay1996** [flaghunters/Extra-Flags-for-4chan#467]
This has the regions of Hlavni mesto (Prague - 88 flags) and Jihocesky (South Bohemia - 360 flags)
[Hlavni mesto region + Jihocesky region.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/563661/Hlavni.mesto.region.Jihocesky.region.zip)

**Comment by shadilay1996** [comment]
Jihomoravsky region (South Moravia - 622 flags)

[jihomoravsky region.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/570720/jihomoravsky.region.zip)

**Comment by shadilay1996** [comment]
Karlovarsky Region (Karlovy Vary - 130 flags)
[karlovarsky region.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/573120/karlovarsky.region.zip)

**Comment by shadilay1996** [comment]
Liberecky Region (Liberec - 179 flags)
[liberecky region.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/573653/liberecky.region.zip)

**Comment by shadilay1996** [comment]
Kralovehradecky Region (Hradec Kralove - 323 flags)
[kralovehradecky region.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/574717/kralovehradecky.region.zip)

**Comment by shadilay1996** [comment]
Vysocina Region (459 flags)
[vysocina.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/584876/vysocina.zip)

**Comment by shadilay1996** [comment]
Pardubicky Region (Pardubice - 375 flags)
[pardubice.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/588168/pardubice.zip)

**Comment by MasterAutismo** [comment]
I've taken note of this issue and I'll work to get this closed as soon as possible.

**Comment by shadilay1996** [comment]
Zlinsky Region
[Zlinsky Region.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/786687/Zlinsky.Region.zip)

**Comment by shadilay1996** [comment]
Moravskoslezsky Region
[Moravskoslezsky Region.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/787233/Moravskoslezsky.Region.zip)

**Comment by shadilay1996** [comment]
Ustecky Region
[Ustecky Region.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/788800/Ustecky.Region.zip)

**Comment by MasterAutismo** [comment]
I'm about to add the regions you provided. If you have the Plzensky, Stredocesky, or Olomoucky regions, please submit them and I will include them.

**Comment by MasterAutismo** [comment]
Added your regions. I'll leave this open until you let me know about the aforementioned regions.
