### ISSUE TITLE
Ottawa County, Michigan

### ISSUE THREAD

**Issue by shadilay1996** [flaghunters/Extra-Flags-for-4chan#468]
Flags for ---
-Coopersville
-Ferrysburg
-Grand Haven
-Holland
-Hudsonville
-Zeeland
-Spring Lake
-Allendale Township
-Georgetown Township
-Park Township
-Robinson Township

[Ottawa County, MI.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/587568/Ottawa.County.MI.zip)

**Comment by 3Paracetamol** [comment]
Added, Thanks for the flags.
