### ISSUE TITLE
Filtering posts with certain flags

### ISSUE THREAD

**Issue by sersh** [flaghunters/Extra-Flags-for-4chan#47]
I asked the 4chan-x developer to possibly add this in but he said no so I'm asking here. There's a person who I see posting ISIS videos and he uses a flag from this script so I would like to filter him.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Should be possible with some custom css. I'm on vacation so I can't do it atm.

**Comment by sersh** [comment]
Tried it with CSS but couldn't manage to get it to work.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Sorry, I can't do it, I'll leave the issue open for someone else to take it up (don't get you're hopes up though).
