### ISSUE TITLE
Ukraine

### ISSUE THREAD

**Issue by shadilay1996** [flaghunters/Extra-Flags-for-4chan#470]
Added flags to a district/city level for all the regions (oblasts), as well as the city of Sevastopol and the Republic of Crimea
Total- 987 flags

[Ukraine.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/587630/Ukraine.zip)

**Comment by MasterAutismo** [comment]
I've taken note of this issue and I'll work to get this closed as soon as possible.
