### ISSUE TITLE
Towns/Cities of Massachusetts

### ISSUE THREAD

**Issue by MasterAutismo** [flaghunters/Extra-Flags-for-4chan#472]
Includes flags for towns/cities numerous counties in Massachusetts. Massive credit to BedfordAnon for most of the flags in Barnstable, Berkshire, Dukes, Franklin, Hampden, Hampshire, and Worcester Counties.

[Middlesex County.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/598427/Middlesex.County.zip)
[Norfolk County.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/600721/Norfolk.County.zip)
[Suffolk County.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/600722/Suffolk.County.zip)
[Plymouth County.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/608704/Plymouth.County.zip)
[Barnstable County.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/612928/Barnstable.County.zip)
[Berkshire County.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/612927/Berkshire.County.zip)
[Dukes County.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/612932/Dukes.County.zip)
[Franklin County.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/612929/Franklin.County.zip)
[Hampden County.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/612931/Hampden.County.zip)
[Hampshire County.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/612930/Hampshire.County.zip)
[Worcester County.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/677181/Worcester.County.zip)
[Essex County.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/677596/Essex.County.zip)
[Bristol County.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/678128/Bristol.County.zip)

Requesting that the issue be closed, all counties are complete.

**Comment by whatthefugmane** [comment]
[Berkshire County.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/600577/Berkshire.County.zip)

[Hampshire County.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/600580/Hampshire.County.zip)

[Franklin County.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/600582/Franklin.County.zip)

**Comment by whatthefugmane** [comment]
:^)

**Comment by MasterAutismo** [comment]
Appreciate the effort, Bedford. However, anti-aliased flags are standard for addition to the system. If you are going to remake the flags, please let me know so I don't make them later. Essex, Plymouth, and Bristol are next on my list.

**Comment by BedfordAnon** [comment]
[berkshire county.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/602247/berkshire.county.zip)
[hampshire county.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/602248/hampshire.county.zip)
[franklin county.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/602249/franklin.county.zip)
anti aliased and glossed :^)

**Comment by BedfordAnon** [comment]
[barnstable County.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/602260/barnstable.County.zip)

**Comment by BedfordAnon** [comment]
[barnstable county.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/602261/barnstable.county.zip)

**Comment by BedfordAnon** [comment]
Complete Counties :^)
[Barnstable County.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/602316/Barnstable.County.zip)
[berkshire county.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/602318/berkshire.county.zip)
[dukes county.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/602319/dukes.county.zip)
[franklin county.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/602320/franklin.county.zip)
[hampden county.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/602321/hampden.county.zip)
[hampshire county.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/602322/hampshire.county.zip)
anti-aliased and glossed :DDDD

**Comment by MasterAutismo** [comment]
Absolutely fantastic, BedfordAnon. They look great. I'll double check the flags and mark them on my map, makes Massachusetts much, much closer to completion!

**Comment by BedfordAnon** [comment]
[Barnstable County.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/612278/Barnstable.County.zip)
[berkshire county.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/612279/berkshire.county.zip)
[dukes county.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/612280/dukes.county.zip)
[franklin county.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/612281/franklin.county.zip)
[Hampden County.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/612282/Hampden.County.zip)
[hampshire county.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/612283/hampshire.county.zip)
all .png :^)

**Comment by MasterAutismo** [comment]
Thanks Bedford, I already converted any .jpgs and .gifs you had in the old file to .pngs as well as adding in any towns/cities you missed! Remaining counties are Worcester, Essex, and Bristol. If you'd like to work on any of the remaining three, please let me know which ones so we don't end up working on the same counties!

**Comment by BedfordAnon** [comment]
ill get worcester

**Comment by BedfordAnon** [comment]
[Worcester County.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/613495/Worcester.County.zip)

saved, resized, renamed, antialiased, glossed, uploaded, under 45 minutes. noice :^)

**Comment by MasterAutismo** [comment]
Thanks for Worcester, BedfordAnon. I added it to the main issue - edited two of the flags. Excellent job, only Essex and Bristol remain. Hopefully I can wrap this up at some point.

**Comment by MasterAutismo** [comment]
The issue has been resolved.

**Comment by MasterAutismo** [comment]
There appears to be an issue displaying in /flag/. Getting the "region empty, no flag yet, or you did not set" when attempting to use town/seal flags.

Would appreciate some insight into what the issue seems to be.
