### ISSUE TITLE
Austria

### ISSUE THREAD

**Issue by shadilay1996** [flaghunters/Extra-Flags-for-4chan#473]
Because it only had state flags... 
This is only part one, still have three states to do (Oberösterreich, Salzburg, Tyrol)

Burgenland - 174 flags
Kärnten (Carinthia) - 140 flags
Niederösterreich - 585 flags
Steiermark (Styria) - 277 flags
Vorarlberg - 100 flags
Wien (Vienna) - 128 flags

[Austria p1.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/598461/Austria.p1.zip)

**Comment by shadilay1996** [comment]
The rest of Austria

Oberösterreich - 458 flags
Salzburg - 124 flags
Tyrol - 287 flags

[Austria p2.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/599348/Austria.p2.zip)

**Comment by MasterAutismo** [comment]
I've taken note of this issue and I'll work to get this closed as soon as possible.
