### ISSUE TITLE
Urban agglomeration of Montreal's flags

### ISSUE THREAD

**Issue by ARandomQuebecois** [flaghunters/Extra-Flags-for-4chan#474]
[Flagtism.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/602401/Flagtism.zip)

I didn't find flags for Montreal-West by the way.

WARNING:These cities aren't a neighbourhood of Montreal, they are just in the same region.

EDIT: I resized the flags I hope it's better now
[Flagtism.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/676385/Flagtism.zip)

**Comment by 3Paracetamol** [comment]
I cant add them yet, make sure they are anti-aliased. You can do this by when resizing in paint.net, set the parameter from 'nearest neighbor' to 'best quality'. Once done I can add them.

**Comment by MasterAutismo** [comment]
I won't be able to add these flags due to aliasing issues, although considering how few there are, I'll remake them soon and try to add them.
