### ISSUE TITLE
Poland

### ISSUE THREAD

**Issue by shadilay1996** [flaghunters/Extra-Flags-for-4chan#475]
part 1

Dolnoslaskie voivodeship - 193 flags
Kujawsko-Pomorskie voivodeship - 157 flags
Lodzkie voivodeship - 176 flags
Lubelskie voivodeship - 208 flags
[poland p1.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/602463/poland.p1.zip)

**Comment by shadilay1996** [comment]
Lubuskie voivodeship - 95 flags
Mazowieckie voivodeship - 315 flags

[poland p2.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/613992/poland.p2.zip)

**Comment by MasterAutismo** [comment]
I've taken note of this issue and I'll work to get this closed as soon as possible.

**Comment by shadilay1996** [comment]
Zachodniopomorskie Voivodeship - 123 flags
[Zachodniopomorskie Voivodeship.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/786801/Zachodniopomorskie.Voivodeship.zip)

**Comment by MasterAutismo** [comment]
All flags here will be added shortly. If there are any flags for the remaining Voivodeships, start a new issue and upload them there. Will close this issue.
