### ISSUE TITLE
missing indiana flags

### ISSUE THREAD

**Issue by BedfordAnon** [flaghunters/Extra-Flags-for-4chan#476]
[missing flags.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/604913/missing.flags.zip)

**Comment by 3Paracetamol** [comment]
They are all in .gif, I need them in .png from now on.

**Comment by BedfordAnon** [comment]
[missing flags.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/612298/missing.flags.zip)
got it

**Comment by 3Paracetamol** [comment]
Added, Thanks.
