### ISSUE TITLE
a couple of New Zealand town flags

### ISSUE THREAD

**Issue by shadilay1996** [flaghunters/Extra-Flags-for-4chan#477]
Porirua in Wellington Region, currently only a logo and not the flag [source](http://www.pcc.govt.nz/About-Porirua/Porirua-s-heritage/Porirua-s-natural--cultural-and-historic-heritage/Civic-History/Porirua-City-Flags)
![porirua](https://cloud.githubusercontent.com/assets/23149926/20551112/4abdf418-b1a1-11e6-9de1-ad7912c1646a.png)

Eltham in South Taranaki District, Taranaki Region [source 1](http://www.crwflags.com/fotw/flags/nz-tk.html#eltham) [source 2](http://www.nzherald.co.nz/stratford-press/news/article.cfm?c_id=1503390&objectid=10991313)
![eltham](https://cloud.githubusercontent.com/assets/23149926/20551018/62f81dc0-b1a0-11e6-80f2-c22248da9a70.png)

Manaia in South Taranaki District, Taranaki Region [source 1](http://www.stuff.co.nz/taranaki-daily-news/news/5088925/Flag-still-flying-for-Manaia) [source 2](http://www.crwflags.com/FOTW/images/n/nz-manaia.jpg)
![manaia](https://cloud.githubusercontent.com/assets/23149926/20551019/64a1dabc-b1a0-11e6-8930-a8f7a33e5ed1.png)

Riverton in Southland District, Southland Region [source 1](http://www.stuff.co.nz/southland-times/news/754690) [source 2](http://web.archive.org/web/20100521101940/http://ns1.southlanddc.govt.nz/assets/NewFolder/riverton-flag-pic.JPG)
![riverton](https://cloud.githubusercontent.com/assets/23149926/20551022/67261e6a-b1a0-11e6-97b3-61f79fb78b4d.png)

**Comment by 3Paracetamol** [comment]
Alright, Thanks, Added.
