### ISSUE TITLE
Uruguayan flag / Paso de los Toros

### ISSUE THREAD

**Issue by Kurohisui** [flaghunters/Extra-Flags-for-4chan#478]
I made the flag of "Paso de los Toros", it's situated within the Tacuarembó Department, I'd be pleased if you add it.

[I'm not really sure if this is the section for requests, sorry if it isn't.]
![paso de los toros - tacuarembo - uruguay](https://cloud.githubusercontent.com/assets/20346785/20735864/a5edc130-b681-11e6-8602-66c89e4cbb65.png)

**Comment by 3Paracetamol** [comment]
This is the correct place for this. Added and closed.
