### ISSUE TITLE
Running the add flags script

### ISSUE THREAD

**Issue by WhatIsThisImNotGoodWithComputers** [flaghunters/Extra-Flags-for-4chan#479]
@3Paracetamol what OS are you on familia?
Windows?

**Comment by 3Paracetamol** [comment]
I run  Fedora 21, Ubuntu, openSUSE 12.1 and Windows 10.
![screenshot from 2016-12-01 21-54-17](https://cloud.githubusercontent.com/assets/19728169/20791563/b25ddf86-b811-11e6-837f-4d7a568e98fb.png)
For simplicity I used Ubuntu to run the script, I just don't know how to prepare the script. And use the script to add lines in the master txt file either. Help much appreciated. I don't want extra flags to die especially when all these new additions are being made.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Regular shell (sh) probably won't be able to run it.
Assuming you're using Bash on Ubuntu you can just "./generate_flag_list_api2.sh" from the same directory to run it with Bash.
It's required to execute it from the same directory and to not have moved any folders or files around (paths are relative).
