### ISSUE TITLE
Everybody has the same flag

### ISSUE THREAD

**Issue by sersh** [flaghunters/Extra-Flags-for-4chan#48]
https://i.gyazo.com/bac56343f550af72c8ac097736e64ae8.png

I've seen this happen before. It gives everybody the same flag, in this case it's Cornwall but I've seen it do other flags before. I think a user can make it happen but I'm not sure how.

Even the Netherlands and American poster have it and it's not just showing as Cornwall for me, everybody can see it too.

**Comment by FS1NG** [comment]
Im getting Devon now but yeah its fucked up

**Comment by revvel** [comment]
It's possible to spam regions for posts. There needs to be some sort of verification that the submitted region/postnumber belongs to a legit user or that the postnumber actually exists on the board (and just happened)

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
I'm aware of the abuse and I'm working on it, although I'm on vacation and I have limited resources at the moment.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
*Might* have been fixed.
Please comment or reopen if it happens again.
