### ISSUE TITLE
Canada Fraser Valley Regional District missing multiple cities.

### ISSUE THREAD

**Issue by WilliamRG** [flaghunters/Extra-Flags-for-4chan#480]
Mission, and Chilliwack as well as Deroche are missing, can someone fix this?

**Comment by BedfordAnon** [comment]
[Canada - British Colombia - Fraser Vally Regional District.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/657158/Canada.-.British.Colombia.-.Fraser.Vally.Regional.District.zip)
:^)

**Comment by BedfordAnon** [comment]
[Canada - British Colombia - Fraser Vally Regional District.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/657172/Canada.-.British.Colombia.-.Fraser.Vally.Regional.District.zip)

:^) deroche unfortunately does not have a flag or a coat of arms to use

**Comment by 3Paracetamol** [comment]
Added, Thanks.
