### ISSUE TITLE
A few requested flags from /deutsch/

### ISSUE THREAD

**Issue by Malte-Soeren** [flaghunters/Extra-Flags-for-4chan#481]
Austria:
![braunau am inn](https://cloud.githubusercontent.com/assets/18237244/21473321/77c8e3b8-cb06-11e6-948a-006886f1f098.png)
Braunau am Inn, located in Oberösterreich
![judenburg](https://cloud.githubusercontent.com/assets/18237244/21473330/c4e30886-cb06-11e6-845a-5e28a34fa9ae.png)
Judenburg, located in Steiermark (yes this is an actual city)
Germany:
![moers](https://cloud.githubusercontent.com/assets/18237244/21473286/1a97b918-cb05-11e6-8fb4-69692f731440.png)
Moers, located in Wesel District, NRW
Switzerland:
![aarau](https://cloud.githubusercontent.com/assets/18237244/21473287/371e9e3a-cb05-11e6-97ac-2243e7c7366d.png)
![wettingen](https://cloud.githubusercontent.com/assets/18237244/21473288/3911a5fc-cb05-11e6-8072-b7790aa442e8.png)
first Aarau and second Wettingen, both in Canton of Aargau

**Comment by 3Paracetamol** [comment]
Added, Thanks.
