### ISSUE TITLE
Canton of Basel-Stadt

### ISSUE THREAD

**Issue by Malte-Soeren** [flaghunters/Extra-Flags-for-4chan#482]
All three Municipalities of Basel-Stadt
![basel](https://cloud.githubusercontent.com/assets/18237244/21549164/b66efa70-cdf0-11e6-969d-dd388d3c7fc0.png)
![bettingen](https://cloud.githubusercontent.com/assets/18237244/21549165/b670d444-cdf0-11e6-80ac-81304d734809.png)
![riehen](https://cloud.githubusercontent.com/assets/18237244/21549166/b67644c4-cdf0-11e6-9d0a-37b2102be623.png)
From top to Bottom: Basel,Bettingen, Riehen

**Comment by yanarai** [comment]
If you're working on Switzerland you should check out the flags I already made and suggested here: https://github.com/flaghunters/Extra-Flags-for-4chan/issues/331

Just so we don't do the same work twice

If you need some help researching the proper flags I'd be glad to help

**Comment by Malte-Soeren** [comment]
Im not working on switzerland, just got a request from the basler in /deutsch/ to add his city and because i thought adding only basel into the canton of basel-stadt would be ridiculous i made all three

**Comment by 3Paracetamol** [comment]
Added, Thanks.
