### ISSUE TITLE
Alabama Expansion and Update

### ISSUE THREAD

**Issue by MasterAutismo** [flaghunters/Extra-Flags-for-4chan#484]
Adding flags for the counties of Alabama. 

Any current flags are anti-alised and should be replaced. Also requesting that the current Madison County, Alabama be removed (it's a Florida flag that mistakenly ended up there). 

[Alabama.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/679550/Alabama.zip)

**Comment by 3Paracetamol** [comment]
Added and fixed, Thanks.
