### ISSUE TITLE
Pennsylvania Fix

### ISSUE THREAD

**Issue by MasterAutismo** [flaghunters/Extra-Flags-for-4chan#485]
Currently, there are 5 incorrect flags in the database for Pennsylvania, these being: 

- McKean County
- Monroe County
- Montour County
- Susquehanna County
- Tioga County

All five are represented by a blank, white flag. Two of these counties, Montour and Tioga, _do_ have seals and their flags are included below and should be replaced.

![montour county](https://cloud.githubusercontent.com/assets/18697669/21604566/d80414de-d171-11e6-8608-64adb2edbcf4.png)
![tioga county](https://cloud.githubusercontent.com/assets/18697669/21604565/d803b08e-d171-11e6-9300-c894cd8b972e.png)

The remaining three have no seal or flag and, therefore, should be removed from the database as keeping them sets the precedent that unrepresented areas can simply be represented with a blank flag as a substitute. This defeats the entire purpose of flag collecting. If there is disagreement with my request for the aforementioned flags to be removed, please discuss in the comments and I will reply as quickly as possible.

**Comment by 3Paracetamol** [comment]
Completed, Thanks.
