### ISSUE TITLE
Oregon Update 

### ISSUE THREAD

**Issue by MasterAutismo** [flaghunters/Extra-Flags-for-4chan#487]
Included are the county flags for most Oregon counties, these being ones where the seal or flag is known for that county. Numerous flags have had aliasing issues fixed. Also included is the flag of Albany, Oregon which should be filed under Linn County, Oregon.

This completes the state of Oregon, any counties not included have no seal to represent them and should be left blank.

[Oregon.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/688192/Oregon.zip)

**Comment by OPLK** [comment]
Give me your Benis

**Comment by 3Paracetamol** [comment]
Added, Thanks.
