### ISSUE TITLE
Ohio County Fix

### ISSUE THREAD

**Issue by BedfordAnon** [flaghunters/Extra-Flags-for-4chan#488]
[Ohio.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/694975/Ohio.zip)
:^)

**Comment by 3Paracetamol** [comment]
Bedford, They are all aliased, can you remake them all anti-aliased so I can add them.

**Comment by MasterAutismo** [comment]
Redid the flags anti-aliased, closing issue shortly.
