### ISSUE TITLE
Western Counties Fix (CO, MT, WY)

### ISSUE THREAD

**Issue by MasterAutismo** [flaghunters/Extra-Flags-for-4chan#489]
The following update includes flags for the counties of three states: Montana, Wyoming, and Colorado. 

Any counties already in the database should have their flags be replaced due to aliasing issues being fixed. Any counties which are absent do not have any logo, seal, or flag and should be left blank.

[Wyoming.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/697340/Wyoming.zip)
[Colorado.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/697339/Colorado.zip)
[Montana.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/697341/Montana.zip)

**Comment by 3Paracetamol** [comment]
Added, Thanks.
