### ISSUE TITLE
Implement HTTPS

### ISSUE THREAD

**Issue by aCarbon** [flaghunters/Extra-Flags-for-4chan#49]
Currently all requests are sent to your server in plain-text. This includes the board, region, and post number. Someone listening on the network, or even intelligence agencies (worst case I guess) could use this to build up a profile of your posts.

You can get a free SSL certificate for the first year from [StartSSL](https://www.startssl.com), and by the time that expires, the [LetsEncrypt](https://letsencrypt.org/) should be fully up and running so adding this would be of no additional cost to you, just a small amount of time to initially set it up on your server.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
I remember checking StartSSL, but I think I did not take it because I had to provide all sorts of data.
Currently I'm on vacation so I have limited resources, when I'm back I will certainly take a look at LetsEncrypt, it looks great.

**Comment by aCarbon** [comment]
@WhatIsThisImNotGoodWithComputers the LetsEncrpt beta is now out. https://letsencrypt.readthedocs.org/en/latest/using.html

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks for reminding. I switched hosts last week and I signed up with cloudflare.
Https is working, I will update the script this weekend.
Currently it's a CF certificate + my self signed one.
When I sign up here this weekend I'll make sure the script bypasses CF.

**Comment by aCarbon** [comment]
No problem. Just a tip as I was trying out LetsEncrypt earlier today with a domain behind Cloudflare and was having an issue. It appears you have to temporarily disable Cloudflare on the domain (click the cloud on your A and www CNAME in the DNS section) so that you can complete the domain verification step.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Kinda bummed out by
>Let’s Encrypt CA issues short lived certificates (90 days). Make sure you renew the certificates at least once in 3 months.
Thinking about just leaving it at CF + self signed

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Leaving it at this.
