### ISSUE TITLE
Virginia County Fix

### ISSUE THREAD

**Issue by BedfordAnon** [flaghunters/Extra-Flags-for-4chan#490]
[Virginia.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/697654/Virginia.zip)

**Comment by MasterAutismo** [comment]
Great job, Bedford!

I've gone ahead and completed the rest of the counties as well as Virginia's independent cities. With the following file, the state of Virginia is 100% complete. 

[Virginia.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/698136/Virginia.zip)
