### ISSUE TITLE
New Dutch flags

### ISSUE THREAD

**Issue by RadicalBean** [flaghunters/Extra-Flags-for-4chan#494]
New flag for Gooise Meren as they updated their website with a logo, should go in Noord-Holland
![gooise meren](https://cloud.githubusercontent.com/assets/18211468/22479721/1c68fc46-e7ef-11e6-8483-2ba6888f623d.png)

**Comment by RadicalBean** [comment]
whoops

**Comment by 3Paracetamol** [comment]
Added, Thanks.
