### ISSUE TITLE
Guaynabo, Puerto Rico flags

### ISSUE THREAD

**Issue by shadilay1996** [flaghunters/Extra-Flags-for-4chan#497]
Flags of the barrios of Guaynabo, Puerto Rico from http://www.guaynabocity.gov.pr/
[Guaynabo.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/786684/Guaynabo.zip)

**Comment by MasterAutismo** [comment]
Appreciate the issue, but please make sure to include the proper diacritics in the future. Río was missing its diacritic. 

Issue closed.
