### ISSUE TITLE
Japan Attempt 2

### ISSUE THREAD

**Issue by RadicalBean** [flaghunters/Extra-Flags-for-4chan#499]
Second try at doing japan, working on fukushima now.
Folders that already exist seem to be correct, so just add the missing ones

http://www83.zippyshare.com/v/YmHYJ6Uk/file.html

Will post updates in this issue thread, please keep open
EDIT: check these sick issue dubs

**Comment by MasterAutismo** [comment]
Will keep an eye on this issue.

**Comment by MasterAutismo** [comment]
I've managed to get the repository up and running. Still keeping an eye out on this issue.

**Comment by MasterAutismo** [comment]
I've managed to close numerous issues. Still awaiting a response on this issue, is this still being worked on?

**Comment by MasterAutismo** [comment]
It's been about two months at this point and I'm still awaiting a response. I need the flags or I can't close this issue. I'd appreciate a comment ASAP.

**Comment by MasterAutismo** [comment]
I'm giving you until 24th July 2017 to give me some sort of notification before I consider this issue abandoned.

**Comment by MasterAutismo** [comment]
At this point, I'm going to assume you quit /flag/ for whatever reason. I am taking full control of this issue and will make the Japan regionals myself.

**Comment by MasterAutismo** [comment]
I've seen you around /flag/ yesterday and today. As of posting this, this is the _only_ unsolved issue on github.

I'm more than willing to add your flags in provided you just upload them here in a .zip, or you can send them to masterautismo@hotmail.com (some people have issues with uploading here, including Madrid anon). If you're unable to add them because you're away or there's some other reason you can't provide flags, please let me know ASAP here or on the /flag/ thread.

I've been more than patient (two and a half months and counting), so I hope to see a response soon.

**Comment by RadicalBean** [comment]
http://www68.zippyshare.com/v/qj439rny/file.html

**Comment by MasterAutismo** [comment]
[Japan (Undone).zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/1234680/Japan.Undone.zip)
Here is the fixed Japan with duplicates removed. Notice the proper usage of suffixes for identically named towns (Fuchu the town and Fuchu the city in the Hiroshima Prefecture). Please replace your files with the ones included in the zip and add your new Hiroshima municipality flags to the Hiroshima file. 

I'll be starting at the Yamanashi Prefecture.

**Comment by MasterAutismo** [comment]
Got all Japan flags done except Hokkaido (1000 flags exactly in 12 hours, try that on for size). 

Leaving you what I did of Hokkaido so you can add them if you haven't done them already. 
[Hokkaido.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/1236070/Hokkaido.zip)

I'll have all the other prefectures added, check Discord for more detailed message.

**Comment by MasterAutismo** [comment]
Just wanted to leave a final comment on a journey of an issue. Thanks for finally giving me the flags. Makes me a bit sentimental to close this issue considering Kar himself worked on it. RIP Kar and may his work live on.
