### ISSUE TITLE
New Regional Flags for Iceland

### ISSUE THREAD

**Issue by Grindviking** [flaghunters/Extra-Flags-for-4chan#50]
I have some 16x11 flags for Iceland that I just made. Don't know what else to say tbh, here they are:
![kopavogur](https://cloud.githubusercontent.com/assets/14356195/9974395/a86b8740-5e52-11e5-8b12-569ae33933bf.png)
![reykjavik](https://cloud.githubusercontent.com/assets/14356195/9974396/a873a90c-5e52-11e5-80e7-2d72805c326f.png)
![akureyri](https://cloud.githubusercontent.com/assets/14356195/9974398/a8763be0-5e52-11e5-846f-07bad96d8bdb.png)
![grindavik](https://cloud.githubusercontent.com/assets/14356195/9974397/a874c256-5e52-11e5-8e63-22261a9fdf87.png)
![hafnarfjordur](https://cloud.githubusercontent.com/assets/14356195/9974399/a8777082-5e52-11e5-9033-6791ce912503.png)

Not sure if that worked, I'll resend them if it didn't

**Comment by Grindviking** [comment]
I should specify which is which:
-Kópavogur 
-Reykjavík
-Akureyri
-Grindavík
-Hafnarfjörður 
In that order

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks, added them.
There was a Reykjavik one already but I replaced it with yours for consistency with the others.

**Comment by Grindviking** [comment]
Thanks, I appreciate it.
Also the Akureyri and Grindavík flags need to be swapped, other than that it's all good.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Sorry lad, should be fixed now.
