### ISSUE TITLE
Luxembourg flags

### ISSUE THREAD

**Issue by Autist420** [flaghunters/Extra-Flags-for-4chan#503]
I've noticed that Luxembourg only has some random town flags but not the district and canton flags so I've decided to make them myself using the heraldic symbols,it would be nice if they could be added.
The first name is the luxembourgish one and the name between brackets is the french one
http://imgur.com/a/D9Egl

**Comment by MasterAutismo** [comment]
I cannot add these flags. Please remake them as .png files with gloss and a proper aspect ratio (seal or coat of arms no larger than 240 x 157 centered on a 316 x 214 canvas resized to 16 x 11 flag). 

I can't find the sources for what you made the flags with, so if I don't receive a response within 10 days I'll consider this issue abandoned and close it.

**Comment by Autist420** [comment]
[Luxembourg Extraf(l)ags.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/1028979/Luxembourg.Extraf.l.ags.zip)
This should be it boss

**Comment by MasterAutismo** [comment]
I actually went through and made the flags over the past few days (found the source material), keeping the coat of arms for their respective cities and then using the elements in the coat of arms to make full fledged flags for the cantons so there's some differentiation/lack of repetition between levels. I'll be uploading it soon and closing this issue. Thanks for your contribution!
