### ISSUE TITLE
Tazewell County, Illinois, United States

### ISSUE THREAD

**Issue by IllinoisBois** [flaghunters/Extra-Flags-for-4chan#507]
Tazewell didn't have a flag and wasn't even listed so I took the liberty of making a flag.
![tazewell county flag for ants](https://cloud.githubusercontent.com/assets/28788988/26216624/5f3d13f2-3bca-11e7-8102-4d4647f82106.png)
Smaller one above. Hard to notice.
![tazewell county flag](https://cloud.githubusercontent.com/assets/28788988/26216625/5f4c4dc2-3bca-11e7-830b-5084d1c35920.png)
The larger one.
Cheers!

**Comment by MasterAutismo** [comment]
I have a current flag made which will be added to the database (same as yours but with the gloss) when I can figure out the flag_lists. Thank you for submitting, I will attempt to add your flag as a test to see if I'm able to finally work this out.

**Comment by MasterAutismo** [comment]
Added with no errors, closing issue.

**Comment by IllinoisBois** [comment]
Coolio. Thanks dude.
