### ISSUE TITLE
Can you add a new flag for South Florida?

### ISSUE THREAD

**Issue by ave07** [flaghunters/Extra-Flags-for-4chan#52]
<3 you if its possible.

http://imgur.com/oKsOYjs

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
What kind of flag is this? Is it a meme flag or a real flag?

**Comment by ave07** [comment]
Meme

**Comment by ave07** [comment]
Meme if you cant add it can you add city flags?

https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Flag_of_Miami,_Florida.svg/1000px-Flag_of_Miami,_Florida.svg.png

https://upload.wikimedia.org/wikipedia/commons/a/a9/Flag_of_Fort_Lauderdale,_Florida.png

https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Flag_of_Palm_Beach_County,_Florida.png/100px-Flag_of_Palm_Beach_County,_Florida.png

**Comment by sapporo1** [comment]
Flag of Miami was added in the city flags .zip I uploaded.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
@ave07 if you still want the other city flags, you'll have to make them yourself as I can't do it

**Comment by ave07** [comment]
I see thanks.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
I'm sorry if I wasn't clear, but I'm not in favour of adding historic, ethnic or meme flags, if we start going down that road, I'll have to add Dixie and Nazi flag and it will be a meme fest.
There was a strawpoll on it a long time ago and the guidelines for adding flags are pretty much that if the flag is currently recognised or that the flag belongs to occupants of certain territories, like ISIL, than it's ok to add.

**Comment by ave07** [comment]
Ok then can you at least upload my city's flag then? This is not a meme flag or anything.

http://imgur.com/wNlqOYk

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
It's in

**Comment by ave07** [comment]
Thank You!
