### ISSUE TITLE
Sonoma County, California 

### ISSUE THREAD

**Issue by MarthaStewartIsANazi** [flaghunters/Extra-Flags-for-4chan#526]
![us-cacvd](https://cloud.githubusercontent.com/assets/29157413/26750979/b2c79a9a-47e3-11e7-961e-aee8fd7efd61.jpg)

**Comment by MarthaStewartIsANazi** [comment]
Note that the outer border of the Cloverdale flag is orange - it just blends in with the background.

**Comment by shadilay1996** [comment]
there were 3 other seals you posted in archived threads without flegs, so i made those too

[United States.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/1049430/United.States.zip)
Cloverdale, Healdsburg, Santa Rosa & Sebastopol

If you have any more just post them fam

**Comment by MasterAutismo** [comment]
Going to add Cloverdale, Healdsburg, Santa Rosa, and Sabastopol. Closing this issue, if Sonoma wants more added, please leave the seals in a new issue or post them in the /flag/ thread.
