### ISSUE TITLE
bunch of US city flags

### ISSUE THREAD

**Issue by sapporo1** [flaghunters/Extra-Flags-for-4chan#53]
I made a bunch of US city flags, and they're in a zip so I had to upload it to mega.co.nz

https://mega.nz/#!51cjDAgT!zjISSGR_ZEY8x4x39rMfoGbQ_uXt3x7b_0O51MXxaT4

Sample:
![screen shot 2015-09-28 at 10 07 05 am](https://cloud.githubusercontent.com/assets/14283126/10142633/b3a74ee6-65c8-11e5-982f-d846dab6b6ae.png)

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks, they're added.
