### ISSUE TITLE
add extra flags for US states

### ISSUE THREAD

**Issue by shomanjo** [flaghunters/Extra-Flags-for-4chan#54]
![sac](https://cloud.githubusercontent.com/assets/14880936/10151120/3ef0b0d4-65f9-11e5-9624-0ea5ade15fb5.png)

extra user flag for sacramento

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Can you make it 16x11 pixels?
I tried to pad it with whitespace, but it didn't turn out so well, maybe you can do it better?

**Comment by shomanjo** [comment]
hows this?
![3ef0b0d4-65f9-11e5-9624-0ea5ade15fb5](https://cloud.githubusercontent.com/assets/14880936/10209200/e31bb902-678d-11e5-8daa-4674bb85c336.png)

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
That one doesn't seem to be 16x11 either.

**Comment by shomanjo** [comment]
scrunched it up as much as possible
![images](https://cloud.githubusercontent.com/assets/14880936/10229001/a38255f6-682a-11e5-9f14-228685a9cdba.png)

**Comment by shomanjo** [comment]
still unusable?

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Sorry about that, lad. Completely forgot out it, thanks for reminding me, it's in now.
