### ISSUE TITLE
Missing flag for Winnipeg

### ISSUE THREAD

**Issue by mail135** [flaghunters/Extra-Flags-for-4chan#55]
Hey there, looking to attach a flag for Winnipeg in particular.
Attached is a 16x11 png of the flag.
![winnipeg flag](https://cloud.githubusercontent.com/assets/10202558/10157668/a6111e04-6651-11e5-99ed-4dd702e3720b.png)

**Comment by sapporo1** [comment]
I'm going to do Canadian flags now, and submit them all as one issue

**Comment by mail135** [comment]
Oh perfect! Thanks!

**Comment by mail135** [comment]
Closing this issue then
