### ISSUE TITLE
Canada

### ISSUE THREAD

**Issue by JohnSevier** [flaghunters/Extra-Flags-for-4chan#551]
[Canada.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/1168561/Canada.zip)

**Comment by MasterAutismo** [comment]
Next time you include flags for an _entire country_, please be sure to detail in the issue what the changes are so I don't have to look for myself.

**Comment by MasterAutismo** [comment]
In addition, please refrain from naming like "Teslin, Village of". Just "Teslin" is fine.
