### ISSUE TITLE
Boulder, Colorado

### ISSUE THREAD

**Issue by fxdrte** [flaghunters/Extra-Flags-for-4chan#553]
https://static1.squarespace.com/static/57d746452994ca43043dccd7/t/57d74c3b37c5816c447ce568/1473727568000/?format=1000w

**Comment by MasterAutismo** [comment]
I located the source here. http://www.boulderflag.com/

This is not an official flag, so I cannot add it (as much as I love the design) unless it is adopted - officially - by the City of Boulder.
