### ISSUE TITLE
Luxembourg

### ISSUE THREAD

**Issue by shadilay1996** [flaghunters/Extra-Flags-for-4chan#554]
Complete redo of the Luxemburgish regionals
[Luxembourg.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/1199366/Luxembourg.zip)

**Comment by Kantaiso** [comment]
where did you find the sources?

**Comment by shadilay1996** [comment]
Mostly coats of arms from the Luxembourgish wikipedia and a few other places

**Comment by Kantaiso** [comment]
not that i doubt you, but im looking at the Lëtzebuerg Canton's communes in wikipedia and i only see CoA while you have flags, where did you find those?

**Comment by shadilay1996** [comment]
I just made the coats of arms flag shaped, using the example of Veianen which was already in the repository as a [flag](https://github.com/flaghunters/Extra-Flags-for-4chan/blob/master/flags/Luxembourg/Dikrech%20Distrikter/Veianen%20kanton.png), when the wikipedia had [a coat of arms](https://upload.wikimedia.org/wikipedia/commons/6/6c/Blason_de_Vianden.svg)

**Comment by Kantaiso** [comment]
that actually cool, wasnt aware that was allowed

**Comment by MasterAutismo** [comment]
Just want to say amazing fucking work on this and thanks for the continued work on /flag/. Your flags are always top notch, easy to just pop right into the oven and run the script. For some reason I forgot who you are on /flag/ (it's late and I'm very tired) but just know that you're easily one of the best /flag/tists in terms of contribution right now. 

I had the same idea for Luxembourg, but I was going through finals at the time so I only think I expanded the CoA for the cantons and upper districts, but you did it for every flag. Seriously fantastic job, keep up the good work, and these flags will be in _very_ shortly.
