### ISSUE TITLE
Canadian City Flags

### ISSUE THREAD

**Issue by sapporo1** [flaghunters/Extra-Flags-for-4chan#56]
https://mega.nz/#!x9EjVCZY!R1ApfsU80HEbyqEbYmzzHWvjPIZj52_UPNlUjc8_OFA

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
I've renamed Cornwall, Ontario to Cornwall to be more consistent with others.
Can you expand on the flag called "cities copy 16" in there?

**Comment by mail135** [comment]
The flag for Winnipeg is wrong, this is the correct one:
![winnipeg flag](https://cloud.githubusercontent.com/assets/10202558/10206087/bde4be70-678a-11e5-863c-bad30c8b6aa0.png)

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Sorry bout that, should be fixed.

**Comment by UGHToastIU** [comment]
https://mega.nz/#!TUM0BIKL!3b8nFsJCdYJ7x-hX8fouHBUiEdAqQ474FsO3BeS9Wk4

Just my city's for now, but if it's alright I'd like to toss a few more together once I'm home from work. Main cities are already covered, but there are still quite a few of note. Not sure if the plan is to go for just the provincial capitals and such or "the more the better".

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Sudbury is in.
I'm not sure either. I'm just the facilitator.
More flags to spark interest and intellectual discussion.

**Comment by UntraceableHaze** [comment]
Would it possible to add Peterborough, Ontario? Thanks

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Please provide the flag as 16x11 png (glossed if possible)

**Comment by UntraceableHaze** [comment]
![000](https://cloud.githubusercontent.com/assets/16675960/12317903/aa901e88-ba63-11e5-8075-09c43f2fbdf3.png)

Here we go. No idea how to get the image glossed like the other flags. Hopefully you can fill the void :)

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
It's added fam

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Closed as no more reaction
