### ISSUE TITLE
Minnesota City Flags

### ISSUE THREAD

**Issue by Minnesotanon** [flaghunters/Extra-Flags-for-4chan#560]
[Minnesota Flags.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/1233377/Minnesota.Flags.zip)

Made a bunch of city flags for various MN counties. Most of them are from here: https://flagspot.net/flags/us-mnmun.html the rest were achieved through google searches or off wikipedia, so if need be, that's your best bet at finding the actual flags/seals.

**Comment by Minnesotanon** [comment]
[Minnesota Flags.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/1235043/Minnesota.Flags.zip)

Everything should be a png now

**Comment by MasterAutismo** [comment]
Will push issue by Sunday.
