### ISSUE TITLE
United States/Wisconsin/La Crosse County/La Crosse

### ISSUE THREAD

**Issue by TauntingArtist** [flaghunters/Extra-Flags-for-4chan#563]
![la crosse city flag](https://user-images.githubusercontent.com/31268104/29599812-cb9c3ad2-8797-11e7-85ca-e6434cfe0259.png)

**Comment by MasterAutismo** [comment]
Took me a few minutes to hunt around for the source on the flag [http://www.news8000.com/news/new-peoples-flag-of-la-crosse-unveiled-on-flag-day/542290554](url), please include it next time if you submit a flag. Thanks!
