### ISSUE TITLE
Missing Norwegian municipalities

### ISSUE THREAD

**Issue by MontgomeryAnon** [flaghunters/Extra-Flags-for-4chan#572]
Here are the CoA for the missing Norway munis, sorted by county

[Missing_norways.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/1285767/Missing_norways.zip)

Check existing flegs to see how kar styled them using the CoA (pls no CoA on white background ;__;)

**Comment by MasterAutismo** [comment]
Will get to these at some point. Prioritizing issues with flags already made.

**Comment by ebinBuddha** [comment]
Added, #572 on gitlab
