### ISSUE TITLE
Alberta

### ISSUE THREAD

**Issue by TheFlagLiker** [flaghunters/Extra-Flags-for-4chan#578]
New flags to replace the current ones from src
[Alberta.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/1290222/Alberta.zip)

**Comment by MontgomeryAnon** [comment]
Quick fix - Banff should be within Banff National Park, as it is, but Jasper should not be within Jasper National Park (should instead be on the same level as JNP)
