### ISSUE TITLE
Brazilian Cities Flag

### ISSUE THREAD

**Issue by bolander2000** [flaghunters/Extra-Flags-for-4chan#58]
https://mega.nz/#!4hB0gZ6J
All capitals + plus some relevant cities thanks m8!

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
It's encrypted, I can't download it.

**Comment by bolander2000** [comment]
ah sorry m8 I am travelling right now but on monday I will upload it the right way sorry m8

**Comment by bolander2000** [comment]
http://www.mediafire.com/download/75kvn1mk262n4k3/bandeiras.rar
here m8, now it's ok

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Wew, that's a lot of flags, lad.
They're in.
