### ISSUE TITLE
Flag Missing for Madison, NJ

### ISSUE THREAD

**Issue by ACertainFlagLover** [flaghunters/Extra-Flags-for-4chan#593]
Flag for Madison in Morris County, NJ, USA is missing.

![us-njmad](https://user-images.githubusercontent.com/32102661/30599700-514299c6-9d2b-11e7-87dc-61844ac1017b.gif)

**Comment by ACertainFlagLover** [comment]
I tried my hand at designing the flag in the 16x11 format, as well.
![madison](https://user-images.githubusercontent.com/32102661/30646184-2762e4b0-9de6-11e7-96f5-46e6ed1385b2.png)

**Comment by MontgomeryAnon** [comment]
![madison](https://user-images.githubusercontent.com/25111782/30785134-9e30aef0-a12f-11e7-8c22-40b727454ba2.png)

glossed :^)
