### ISSUE TITLE
France

### ISSUE THREAD

**Issue by masterton6969** [flaghunters/Extra-Flags-for-4chan#598]
Finished the Bas Rhin department, in Grand Est. Used the official French place names with the Alsatian forms in brackets, i.e. Bellefosse (Befoss)
[Bas Rhin.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/1335685/Bas.Rhin.zip)

**Comment by masterton6969** [comment]
Haut-Rhin département
[Haut-Rhin.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/1336132/Haut-Rhin.zip)

**Comment by MasterAutismo** [comment]
I can't add some of these flags, some of the special symbols are fucked up and I don't have the patience to rename them. Further, the inclusion of the Alsatian forms of the names is unnecessary. Please resubmit the flags with French names only and make sure that the special characters can undergo compression without becoming corrupted (perhaps the .zip is the issue).

**Comment by MasterAutismo** [comment]
Dropping you a reminder, hopefully you receive this. I'm closing this issue, please re-submit again in a fresh issue when you finish.
