### ISSUE TITLE
Iroquois flag

### ISSUE THREAD

**Issue by spatev** [flaghunters/Extra-Flags-for-4chan#60]
I'd like to propose a flag for the iroquois nation, most of us are in New York State, some in Canada

Heres my attempt at a flag. Its ok

I'd also request Acadian and Mi'kmaq flags, since i'm acadian/mi'kmaq from NB, but my ~~wife~~ squaw is Iroquois and I'm in iroquois country these days so that seems more appropriate for now.

Thanks!

![iroquois](https://cloud.githubusercontent.com/assets/15637008/10917080/dd534fa8-822c-11e5-9999-cf56ed9ca68e.png)

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
You convinced me in the thread, it's in for Canada and the US.

**Comment by spatev** [comment]
Thanks anon that actually means a lot. If Mrs anon understood 4chan at all
I think she'd be psyched.

I'll have to go make some posts from actual Iroquois Clay to make it
official.

Cheers
