### ISSUE TITLE
Israel

### ISSUE THREAD

**Issue by TheFlagLiker** [flaghunters/Extra-Flags-for-4chan#601]
All districts, cities, and local/regional councils
[il.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/1345992/il.zip)

Current flags should be organized within districts as:

Northern District:
Karmiel, Netanya

Haifa District:
Haifa

Central District:
Kfar Saba, Rishon LeZion

Jerusalem District:
Jerusalem

Southern District:
Ashdod, Ashkelon, Beersheeba, Eilat, Kiryat Gat

Tel Aviv District:
Tel Aviv, Bat Yam, Bnei Brak, Givatayim, Herzliya, Holon, Or Yehuda, Ramat Gan, Ramat HaSharon

Delete: Yokneam

**Comment by MontgomeryAnon** [comment]
>delete yokneam

t. hamas
