### ISSUE TITLE
Bel Air, Harford County, Maryland

### ISSUE THREAD

**Issue by TheFlagLiker** [flaghunters/Extra-Flags-for-4chan#608]
County seat of Harford County
![image](https://user-images.githubusercontent.com/29443007/31304859-2c3a9d04-aafa-11e7-8416-e21818f3910b.png)

**Comment by MasterAutismo** [comment]
My heart skipped a beat when I saw Bel Air, but then I realized this isn't the Bel Air the Fresh Prince lived in. Sad!
