### ISSUE TITLE
More Br city flegs m8

### ISSUE THREAD

**Issue by bolander2000** [flaghunters/Extra-Flags-for-4chan#61]
Some guys at /luso/ are asking for me to add these city flags m8, here it goes m8
https://www.mediafire.com/?ajd78cre9ndb51z

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks lad, added these: https://github.com/flaghunters/Extra-Flags-for-4chan/commit/36e73fa73f3ee8f14f76f073a1b621f6c29742ee

Have not added the others, they are historical flags and belong in /his/ :^)
