### ISSUE TITLE
Scotland overhaul

### ISSUE THREAD

**Issue by TheFlagLiker** [flaghunters/Extra-Flags-for-4chan#615]
Largest towns and cities completed, historic regions that have been abolished have been replaced with current council areas

Regions that need to be deleted:
Ayrshire
Banffshire
Berwickshire
Dumfriesshire
Dunbartonshire
Inverness-shire
Kincardineshire
Kirkcudbrightshire
Lanarkshire
Nairnshire
Ross and Cromarty
Roxburgh, Ettrick and Lauderdale
Stirling and Falkirk
Sutherland
Tweeddale
Wigtownshire

Regions that need to be moved:
Caithness => Highland/Caithness

To be renamed:
Western Isles => Na h-Eileanan Siar

[scotland2.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/1367529/scotland2.zip)

**Comment by MasterAutismo** [comment]
We've been over the Scotland things multiple times, it's gone back and forth over and over. I'm putting this issue on hold for now and I'll review it in thread later.

**Comment by MontgomeryAnon** [comment]
Western Isles should be renamed Na h-Eileanan Siar for sure, that's the official name, they passed legislation that says so

**Comment by MasterAutismo** [comment]
Your flags weren't good enough, I'm closing this and using Minnesota's. Don't take it personal.

**Comment by TheFlagLiker** [comment]
What about the city/town flags
