### ISSUE TITLE
Adding more Dutch flags

### ISSUE THREAD

**Issue by Prontae** [flaghunters/Extra-Flags-for-4chan#62]
This would boost the amounts of discussions on the /int/ board and aswell on /sp/ especially with fellow countrymen.
My suggestion is to add the following (known and relevant) Dutch cities.

- Den Haag 
- Rotterdam
- Velsen
- Eindhoven
- Leeuwarden
- Den Bosch 
These cities have the biggest industries/most relevant or they have the biggest football clubs (for /sp/)

The flags that belong to the cities are:
DEN HAAG: 
![image](https://cloud.githubusercontent.com/assets/16295102/11792930/11b29258-a2a9-11e5-980c-cb2c870bc3ec.png)

ROTTERDAM: 

![image](https://cloud.githubusercontent.com/assets/16295102/11792938/1f431adc-a2a9-11e5-9e5c-c05b58d04739.png)

VELSEN:

![image](https://cloud.githubusercontent.com/assets/16295102/11792964/4902d36c-a2a9-11e5-9955-d9768c68e63f.png)

EINDHOVEN:

![image](https://cloud.githubusercontent.com/assets/16295102/11793026/a073bff8-a2a9-11e5-8b32-864eff54b1ec.png)

LEEUWARDEN:

![image](https://cloud.githubusercontent.com/assets/16295102/11793002/73fc2136-a2a9-11e5-979a-59946a66dd04.png)

DEN BOSCH:

![image](https://cloud.githubusercontent.com/assets/16295102/11793017/8f15bf7c-a2a9-11e5-91f8-6b126ea435e7.png)

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Good plan, but I can't make the flags.
Can you make them into 16x11 px and possibly with the glossy touch?

**Comment by Prontae** [comment]
Like this? 
![image](https://cloud.githubusercontent.com/assets/16295102/11838224/defed2d4-a3e5-11e5-8a3a-3ffa5aaa4aa7.png)

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks, they look great.
They're in.

Btw, next time, can you put multiple flags in a zip or rar?
Shillfire wanted me to sign up if I wanted to download multiple files at once so I had to download one by one...
