### ISSUE TITLE
Maryland towns

### ISSUE THREAD

**Issue by TheFlagLiker** [flaghunters/Extra-Flags-for-4chan#626]
Cumberland, Allegany County

![cumberland](https://user-images.githubusercontent.com/29443007/31370555-bd663264-ad59-11e7-8ef3-3a1742e84263.png)

Williamsport, Washington County

![williamsport](https://user-images.githubusercontent.com/29443007/31370562-c62e3f4a-ad59-11e7-921a-3e19fae81ea0.png)

**Comment by MontgomeryAnon** [comment]
>Cumberland
>White background

Here is correct Cumberland - I'm working on US cities and I already made it

![cumberland](https://user-images.githubusercontent.com/25111782/31411804-c59489d6-ade0-11e7-9548-96d6402cfd37.png)

**Comment by MontgomeryAnon** [comment]
Reference

![cumberland](https://user-images.githubusercontent.com/25111782/31411911-22173f96-ade1-11e7-88be-9a5b067b05f5.jpg)
