### ISSUE TITLE
Finland

### ISSUE THREAD

**Issue by RadicalBean** [flaghunters/Extra-Flags-for-4chan#628]
I started making all municipality flags, apparently like 40% was already done.
Just leave the existing ones, use these for the missing ones
[Finland.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/1379419/Finland.zip)

**Comment by MasterAutismo** [comment]
Probably going to take the CoA you used and make them into full fledged flags. Putting this issue on hold.
