### ISSUE TITLE
Miscellaneous South Asian flags

### ISSUE THREAD

**Issue by gondolas** [flaghunters/Extra-Flags-for-4chan#63]
https://www.mediafire.com/?labz9rmdbr1lhab
It's not much.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks lad, but most of them are off in size. Some 17x11 px and some 18x11 px.
They should all be exactly 16x11 px . Can you make em with that size?

**Comment by gondolas** [comment]
No problem m8
https://www.mediafire.com/?przopqr8z74932x

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
They're in, thanks.
