### ISSUE TITLE
Some more Russian federal divisions

### ISSUE THREAD

**Issue by TheFlagLiker** [flaghunters/Extra-Flags-for-4chan#634]
Arkhangelsk Region
[Arkhangelsk Region.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/1403631/Arkhangelsk.Region.zip)
*Move current flags:*
Kargopol => Kargopolsky District/Kargopol
Kotlas => Kotlassky District/Kotlas
Velsk => Velsky District/Velsk

Astrakhan Region
[Astrakhan Region.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/1403632/Astrakhan.Region.zip)

Bashkortostan
[Bashkortostan.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/1403634/Bashkortostan.zip)

Primorsky Territory
[Primorsky Territory.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/1403641/Primorsky.Territory.zip)

Moscow Region
[Moscow Region.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/1403685/Moscow.Region.zip)
*Move current flags:*
Aprelevka => Naro-Fominsky District/Aprelevka
Dedovsk =>  Istrinsky District/Dedovsk
Dmitrov => Dmitrovsky District/Dmitrov
Egorevsk => Yegoryevsky District/Egorevsk
Istra => Istrinsky District/Istra
Kashira => Kashirsky District/Kashira
Klin => Klinsky District/Klin
Krasnogorsk => Krasnogorsky District/Krasnogorsk
Lotoshino => Lotoshinsky District/Lotoshino
Lyubertsy => Lyuberetsky District/Lyubertsy
Mozhaysk => Mozhaysky District/Mozhaysk
Mytishchi => Mytishchinsky District/Mytishchi
Naro-Fominsk => Naro-Fominsky District/Naro-Fominsk
Noginsk => Noginsky District/Noginsk
Odintsovo => Odintsovsky District/Odintsovo
Pavlovsky Posad => Pavlovo-Posadsky District/Pavlovsky Posad
Pushkino => Pushkinsky District/Pushkino
Sergiev Posad => Sergiyevo-Posadsky District/Sergiev Posad
Shatura => Shatursky District/Shatura
Shchelkovo => Shchyolkovsky District/Schelkovo
Taldom => Taldomsky District/Taldom
Verbilki => Taldomsky District/Verbilki
Vereya => Naro-Fominsky District/Naro-Fominsk
Vidnoe => Leninsky District/Vidnoye
Volokolamsk => Volokolamsky District/Volokolamsk
Voskresensk => Voskresensky District/Voskresensk
Zaraysk => Zaraysky District/Zaraysk

*Delete:*
Yubileyny

Krasnodar Territory
[Krasnodar Territory.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/1403690/Krasnodar.Territory.zip)

Karachay-Cherkessia
[Karachay-Cherkessia.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/1403694/Karachay-Cherkessia.zip)

Sevastopol
[Sevastopol.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/1403695/Sevastopol.zip)

Sakhalin Region
[Sakhalin Region.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/1403696/Sakhalin.Region.zip)
*Move current flags:*
Aniva => Anivsky District/Aniva
Dolinsk => Dolinsky District/Dolinsk
Kholmsk => Kholmsky District/Kholmsk
Korsakov => Korsakovsky District/Korsakov
Kurilsk => Kurilsky District/Kurilsk
Makarov => Makarovsky District/Makarov
Nevelsk => Nevelsky District/Nevelsk
Okha => Okhinsky District/Okha
Nogliki => Nogliksky District/Nogliki
Poronaysk => Poronaysky Distrct/Poronaysk
Severo-Kurilsk => Severo-Kurilsky District/Severo-Kurilsk
Smirnykh => Smirnykhovsky District/Smirnykh
Tomari => Tomarinsky District/Tomari
Tymovskoe => Tymovsky District/Tymosvskoe
Yuzhno-Kurilsk => Yuzhno-Kurilsky District/Yuzhno-Kurilsk

More to come in a bit...

**Comment by TheFlagLiker** [comment]
Amur Region
[Amur Region.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/1404535/Amur.Region.zip)

Komi
[Komi.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/1404537/Komi.zip)

Zabaykalsky Territory
[Zabaykalsky Territory.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/1404541/Zabaykalsky.Territory.zip)
*Move current flags:*
Borzya => Borzinsky District/Borzya
Krasnokamensk => Krasnokamensky District/Krasnokamensk
Nerchinsk => Nerchinsky District/Nerchinsk
Shilka => Shilkinsky District/Shilka
Sretensk => Sretensky District/Sretensk

**Comment by TheFlagLiker** [comment]
Voronezh Region
[Voronezh Region.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/1416946/Voronezh.Region.zip)
*Move current flags:*
Boguchar => Bogucharsky District/Boguchar
Ostrogozhsk => Ostrogozhsky District/Ostrogozhsk
Pavlovsk => Pavlovsky District/Pavlovsk
Rossosh => Rossoshansky District/Rossosh
Liski => Liskinsky District/Lis

**Comment by TheFlagLiker** [comment]
Rostov Region
[Rostov Region.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/1416962/Rostov.Region.zip)
*Move current flags:*
Belaya Kalitva => Belokalitvinsky District /Belaya Kalitva

**Comment by TheFlagLiker** [comment]
Saint Petersburg
[Saint Petersburg.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/1416973/Saint.Petersburg.zip)
*Move current flags:*
Metallostroy => Kolpinsky District/Metallostroy
Pushkin => Pushkinsky District/Pushkin

**Comment by maluhia** [comment]
great flags! next time though, please copy the original Russian folder in the repo, and add your new flags to it. In the time it took you to list what needed to be changed, you could've done it yourself. Then I can just delete the original Russian folder from the repo and replace with yours.

**Comment by TheFlagLiker** [comment]
Ok, I'll do that when I submit the rest of the flags
