### ISSUE TITLE
Eastern Cape (South Africa)

### ISSUE THREAD

**Issue by wezkat** [flaghunters/Extra-Flags-for-4chan#64]
![eastern_cape_flag south_africa](https://cloud.githubusercontent.com/assets/16453499/12010959/5c4b0b40-acc4-11e5-8a48-9735ef4d30d9.png)
Could you add the Eastern Cape flag to South Africa?

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Could you make it into a 16x11 px png? If possible with the "glossy" effect that 4chan has?

**Comment by wezkat** [comment]
![eastern_cape_flag south_africa](https://cloud.githubusercontent.com/assets/16453499/12031227/2785e55c-ae12-11e5-80d5-c1dd29d787b9.png)

Is this fine?

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Yep, thanks, it's been added.
