### ISSUE TITLE
New team members

### ISSUE THREAD

**Issue by WhatIsThisImNotGoodWithComputers** [flaghunters/Extra-Flags-for-4chan#640]
@MasterAutismo I added maluhia and JohnSevier as team members as per your request.
Please let me know if this is not correct asap and I will correct it.

**Comment by MasterAutismo** [comment]
I never _requested_ it, they sort of pushed their way into it, but I really don't mind at this point. Allow them to be team members, because I just don't have the time to manage the repository at the pace /flag/ wants it to be managed at. 

tl;dr, it's fine
