### ISSUE TITLE
State College, Centre County, Pennsylvania

### ISSUE THREAD

**Issue by MontgomeryAnon** [flaghunters/Extra-Flags-for-4chan#642]
![state college](https://user-images.githubusercontent.com/25111782/32857415-ba6b958a-ca15-11e7-8925-ef6b5393de68.png)

**Comment by Minnesotanon** [comment]
Doesn't look like you resized it properly. Here's my take: 
![state_college](https://user-images.githubusercontent.com/31122068/32863830-727daf3a-ca22-11e7-8604-48e42e8340a4.png)

**Comment by MontgomeryAnon** [comment]
wut
