### ISSUE TITLE
Azusa, California 

### ISSUE THREAD

**Issue by camtheman113** [flaghunters/Extra-Flags-for-4chan#646]
![azusa_logo_60x60](https://user-images.githubusercontent.com/24646831/32978892-ce0c73ca-cbff-11e7-8a07-0c4a5eb5a8f7.png)
Not an actual flag but just a seal, still think it would work as a city flag

**Comment by maluhia** [comment]
There is already an Azusa flag in the repo which has the seal [https://github.com/flaghunters/Extra-Flags-for-4chan/blob/master/flags/United%20States/California/Los%20Angeles%20County/Azusa.png](url)
