### ISSUE TITLE
My flag doesn't appear

### ISSUE THREAD

**Issue by JamesMarshallHayley** [flaghunters/Extra-Flags-for-4chan#65]
Everytime as I comment in /int/ it appear as if I hadn't assigned a region or anything, but I did and in fact my state has a flag in the flaghunter package.

My flag should be Nuevo Leon from Mexico but appears as if it haven't had a flag

**Comment by JamesMarshallHayley** [comment]
m8, this is a real problem, my region doesn't show anything

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
We don't seem to have Nuevo Leon. 

https://github.com/flaghunters/Extra-Flags-for-4chan/tree/master/flegs/Mexico

**Comment by FS1NG** [comment]
Its not working at all

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Will check when I get home.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Should be back up in a couple of hours...

@JamesMarshallHayley When were back up, please check with the correct name and then we can check again.

**Comment by JamesMarshallHayley** [comment]
Did the script got down? Also sorry for the confusion, the state is called Nuevo Leon but appears as Nuevo in Mexico and nice profile pic m8

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Yes it's down for the moment.. Hope it will be up again soon...

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
It's working again, please retest.

**Comment by FS1NG** [comment]
It doesnt work

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
It's working here, gonna need more details.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Closed as no more reaction.
