### ISSUE TITLE
This doesn't work anymore

### ISSUE THREAD

**Issue by AvidFlagHunter** [flaghunters/Extra-Flags-for-4chan#66]
My flag doesn't appear anymore and neither does anyone else's.  Will this be fixed soon?

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Hopefully, I cannot give an ETA at this moment.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Should be back up. If anything breaks, let me know.
