### ISSUE TITLE
Extra flag for a municipality in Netherlands

### ISSUE THREAD

**Issue by RANDSTADANDSTAD** [flaghunters/Extra-Flags-for-4chan#67]
Katwijk
https://en.wikipedia.org/wiki/Katwijk

Flag
https://en.wikipedia.org/wiki/Katwijk#/media/File:Katwijk_vlag.svg
![image](https://cloud.githubusercontent.com/assets/16669750/12272279/ce53836e-b95f-11e5-9bb2-a50413326bc3.png)

Icon with glossy template 2
http://i.imgur.com/rJ92llM.png
![image](https://cloud.githubusercontent.com/assets/16669750/12272259/b8bf7490-b95f-11e5-85e9-ede3d15e8c52.png)

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
It's been added, thanks.
