### ISSUE TITLE
Vlaggies voor relevante steden

### ISSUE THREAD

**Issue by dd52** [flaghunters/Extra-Flags-for-4chan#68]
![alkmaar](https://cloud.githubusercontent.com/assets/10272011/12372569/9bb76726-bc5d-11e5-869c-865a39c40b96.png) Alkmaar
![breda](https://cloud.githubusercontent.com/assets/10272011/12372565/9bb5f1fc-bc5d-11e5-81d3-28c8b72a743c.png) Breda
![haarlem](https://cloud.githubusercontent.com/assets/10272011/12372564/9bb5e32e-bc5d-11e5-8fe8-7fa00738ec23.png) Haarlem
![heerlen](https://cloud.githubusercontent.com/assets/10272011/12372568/9bb68e82-bc5d-11e5-9f7d-3cf5e9c27404.png) Heerlen
![maastricht](https://cloud.githubusercontent.com/assets/10272011/12372566/9bb60a8e-bc5d-11e5-962f-18f680e4b7ba.png) Maastricht
![middelburg](https://cloud.githubusercontent.com/assets/10272011/12372567/9bb64da0-bc5d-11e5-983d-cf8a969ac51d.png) Middelburg

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Added, thanks.
