### ISSUE TITLE
New Flags for Syria and Lebanon

### ISSUE THREAD

**Issue by Noaboatx** [flaghunters/Extra-Flags-for-4chan#69]
Hello. I would like to request 2 new flags for Syria and Lebanon.

For Syria: Syrian Arab Army
![200px-syrian_arab_army_flag png](https://cloud.githubusercontent.com/assets/16789560/12438761/644a4ce2-beef-11e5-87af-1d4b90764863.png)
For Lebanon: Hezbollah
![hezbollah_flag](https://cloud.githubusercontent.com/assets/16789560/12438771/8d821c70-beef-11e5-89f6-c5877419d662.jpg)

Miniature Versions for 4chan: 16 x 11 right?

Syrian Arab Army:  ![syrian arab army 16x11](https://cloud.githubusercontent.com/assets/16789560/12438785/ad237632-beef-11e5-9e2c-00e95b2cfc38.png)
Hezbollah:  ![hezbollah_flag 16x11](https://cloud.githubusercontent.com/assets/16789560/12438790/b888a4d4-beef-11e5-8244-eeeacfe38e83.png)

**Comment by Noaboatx** [comment]
Wait NVM about Hezbollah, it seems you already have it in the Syria Folder. Could you add the SAA?

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Added Hezbollah to Lebanon and Syrian Arab Army to Syria.
Thanks.
