### ISSUE TITLE
Desktop+mobile unified script

### ISSUE THREAD

**Issue by ebinBuddha** [flaghunters/Extra-Flags-for-4chan#699]
How to:
- Install Tampermonkey extension for your mobile browser.
- Download the attachment and unzip.
- Use the utility tab of Tampermonkey to import the script for testing.

Note:
- Change version number if needed
- Once rolled out, the installation should work like the desktop version (click link, etc...)

[eflags-test.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/1810234/eflags-test.zip)

Edit: corrected instructions

**Comment by maluhia** [comment]
We must put this on hold, since it doesn't load new extraflag posts with at least Firefox + 4chanX.

Users can still try out the alpha version of the script "eflags-test.js" in the repo folder if they wish.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Moved to https://gitlab.com/flagtism/Extra-Flags-for-4chan/-/issues
