### ISSUE TITLE
Texas + Oklahoma Cities Flags

### ISSUE THREAD

**Issue by Noaboatx** [flaghunters/Extra-Flags-for-4chan#70]
Adding all City flags in Texas + Oklahoma with a population of 500,000 or more
All are 16x11
Texas:
Houston 
![houston 16x11](https://cloud.githubusercontent.com/assets/16789560/12528635/480a1e0c-c162-11e5-8270-1c348d4951d3.png)

San Antonio
![san antonio 16x11](https://cloud.githubusercontent.com/assets/16789560/12528636/4b62f628-c162-11e5-95bc-cb8a0d0c431c.png)

Fort Worth
![fort worth 16x11](https://cloud.githubusercontent.com/assets/16789560/12528637/4f1da48e-c162-11e5-9d35-3249bc157406.png)

El Paso
![el paso 16x11](https://cloud.githubusercontent.com/assets/16789560/12528640/541d1532-c162-11e5-8e90-8f3adef41034.png)

Oklahoma:
Oklahoma City
![oklahoma city 16x11](https://cloud.githubusercontent.com/assets/16789560/12528641/59386706-c162-11e5-975b-eef32b775c6e.png)

Tulsa
![tulsa 16x11](https://cloud.githubusercontent.com/assets/16789560/12528642/5d0c5504-c162-11e5-8dd6-26f4efd6251a.png)

**Comment by Noaboatx** [comment]
Almost forgot.
Texas

Austin 
![austin 16x11](https://cloud.githubusercontent.com/assets/16789560/12528659/c0053bee-c162-11e5-942d-058ec61e9557.png)

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks, they're in.
