### ISSUE TITLE
Sevastopol

### ISSUE THREAD

**Issue by Minnesotanon** [flaghunters/Extra-Flags-for-4chan#701]
A while back I proposed we made the Crimean municipalities identical between Russia and Ukraine, though it seems Sevastopol was left untouched. Just earlier I looked at this page: https://en.wikipedia.org/wiki/Administrative_and_municipal_divisions_of_Sevastopol which I think might clear it up.

From what I can understand, the first-levels (districts) are identical for both countries. After that, they're divided up into municipalities, but the Ukrainian side (seemingly) has less, and then divides them up further into settlements.

I'll leave a more skilled person to decide how to deal with the municipalities, but the big thing is that the districts are the same for both countries, and this should be reflected in the code.

**Comment by maluhia** [comment]
You can check it out. Many Ukrainian flags are needed under those districts of Sevastopol, but I could not find a resource in my quick search.
