### ISSUE TITLE
Mayotte Communes

### ISSUE THREAD

**Issue by Minnesotanon** [flaghunters/Extra-Flags-for-4chan#702]
Made according to information found on Wikipedia, and here: http://www.ngw.nl/heraldrywiki/index.php?title=Mayotte

Apparently these are technically 2nd levels. The island is first divided into 13 Cantons, but where I'd find flag material for them (or if anything like that even exists) is entirely unknown to me.

[Mayotte.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/1844034/Mayotte.zip)

**Comment by maluhia** [comment]
France's own website doesn't provide GIS files for Mayotte's Cantons. I will commit these
