### ISSUE TITLE
Italian Municipalities 3rd Batch

### ISSUE THREAD

**Issue by ebinBuddha** [flaghunters/Extra-Flags-for-4chan#704]
Contents:
Municipalities of Trentino-Alto Adige and Emilia-Romagna plus a couple fixes here and there

Actions:
    Delete:
        - Italy/Emilia-Romagna/Province of Forli-Cesena.png
    Merge the content of the zip archive replacing files with same name.

Warning:
Accented letters

Notes:
Already Glossed

[20180330 TAA-ER_glossed.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/1864114/20180330.TAA-ER_glossed.zip)

**Comment by maluhia** [comment]
@ebinBuddha thanks for the well written directions!
