### ISSUE TITLE
Illinois Cities

### ISSUE THREAD

**Issue by neatlynot2** [flaghunters/Extra-Flags-for-4chan#71]
Most cities with flags with population 75,000+ except Chicago

[Peoria](https://en.wikipedia.org/wiki/Peoria,_Illinois) | [Flag](http://www.crwflags.com/fotw/flags/us-ilpeo.html)
![peoria](https://cloud.githubusercontent.com/assets/16849316/12529214/c6de3102-c174-11e5-8a79-ae684cdcf336.png)

[Springfield](https://en.wikipedia.org/wiki/Springfield,_Illinois)
![springfield](https://cloud.githubusercontent.com/assets/16849316/12529231/3bbb6e2c-c175-11e5-8814-b9614974a177.png)

[Naperville](https://en.wikipedia.org/wiki/Naperville,_Illinois) | [Flag](http://www.crwflags.com/fotw/flags/us-ilnap.html)
![naperville](https://cloud.githubusercontent.com/assets/16849316/12529240/67863c4e-c175-11e5-90a5-1dbdf6a82b82.png)

[Joliet](https://en.wikipedia.org/wiki/Joliet,_Illinois) | [Flag](http://www.crwflags.com/fotw/flags/us-iljol.html)
![joliet](https://cloud.githubusercontent.com/assets/16849316/12529243/8eb09cd8-c175-11e5-89c4-25f283cbbc49.png)

[Schaumburg](https://en.wikipedia.org/wiki/Schaumburg,_Illinois)
![us-il-schaumburg](https://cloud.githubusercontent.com/assets/16849316/12529269/c4f6d212-c175-11e5-96d0-ad277c981994.png)

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks, they're in.
