### ISSUE TITLE
Torrington for Goshen County, WY

### ISSUE THREAD

**Issue by MarthaStewartIsANazi** [flaghunters/Extra-Flags-for-4chan#720]
Noticed an anon was flying under a flag for Goshen County, WY and decided to make a flag for the one city in the county, that being Torrington. It is attached; please notify me if there is an issue with format. It is in png form 
[Torrington.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/2321951/Torrington.zip)

**Comment by ebinBuddha** [comment]
added
