### ISSUE TITLE
New flag for Anaheim, Orange County, California 

### ISSUE THREAD

**Issue by MarthaStewartIsANazi** [flaghunters/Extra-Flags-for-4chan#721]
Anaheim officially changed their old flag two days ago, here is the new one. Pretty sure this will work, it's png 
[Anaheim.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/2341545/Anaheim.zip)

**Comment by ebinBuddha** [comment]
updated, thank (You)
