### ISSUE TITLE
3 random  new flags 

### ISSUE THREAD

**Issue by MarthaStewartIsANazi** [flaghunters/Extra-Flags-for-4chan#722]
Burns Lake, Regional District of Bulkley-Nachako, British Columbia, Canada
[Burns Lake.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/2341600/Burns.Lake.zip)

Rehoboth Beach, Sussex County, Delaware
[Rehoboth Beach.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/2341601/Rehoboth.Beach.zip)

Belen, Valencia County, New Mexico
[Belen.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/2341603/Belen.zip)

**Comment by ebinBuddha** [comment]
Added
(You)
