### ISSUE TITLE
Italian communes

### ISSUE THREAD

**Issue by MarthaStewartIsANazi** [flaghunters/Extra-Flags-for-4chan#723]
Trieste wanted me to do these; they're done. Idk If they're 3rd or 4th lvls but here they are. 
[Province di Lodi.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/2341985/Province.di.Lodi.zip)

**Comment by ebinBuddha** [comment]
Added
Thank (You)

**Comment by ebinBuddha** [comment]
decided to leave this open to let you add the next ones
