### ISSUE TITLE
0

### ISSUE THREAD

**Issue by nlgga** [flaghunters/Extra-Flags-for-4chan#727]
Chisinau
[Chisinau.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/2396930/Chisinau.zip)

**Comment by ebinBuddha** [comment]
Hi there, before I add these I need to know a few things
Why are there "Sectorul Xyz" png inside "Sectorul Xyz" folder and not only outside? Is it bcs the communes and towns do not entirely cover the single sector?
also can you make a map for all of these and post it on the chinz?

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Think closed?

**Comment by cuj** [comment]
I hope you change that username
