### ISSUE TITLE
Dutch flags

### ISSUE THREAD

**Issue by fqdb** [flaghunters/Extra-Flags-for-4chan#73]
![ooststellingwerf](https://cloud.githubusercontent.com/assets/2826336/12535975/d1962f0a-c296-11e5-8ff7-bbca5f29220d.png) Ooststellingwerf
![gorredijk](https://cloud.githubusercontent.com/assets/2826336/12535979/d196878e-c296-11e5-9970-e653e97a2d2d.png) Gorredijk
![opsterland](https://cloud.githubusercontent.com/assets/2826336/12535976/d196b934-c296-11e5-91bc-2ced00e8b977.png) Opsterland
![rijswijk zuid-holland](https://cloud.githubusercontent.com/assets/2826336/12535978/d19945a0-c296-11e5-95be-b121c333e48e.png) Rijswijk (Zuid-Holland)
![meppel](https://cloud.githubusercontent.com/assets/2826336/12535977/d1992b06-c296-11e5-8a54-d8a5202ebd08.png) Meppel
![kampen](https://cloud.githubusercontent.com/assets/2826336/12535974/d195b98a-c296-11e5-9b3c-7f3cbc51692a.png) Kampen
![zwolle](https://cloud.githubusercontent.com/assets/2826336/12535981/d1ae93ba-c296-11e5-9c9f-2942dedb3628.png) Zwolle
![harderwijk](https://cloud.githubusercontent.com/assets/2826336/12535980/d1aded70-c296-11e5-9697-51fc61d5e496.png) Harderwijk
![delft](https://cloud.githubusercontent.com/assets/2826336/12535982/d1af6614-c296-11e5-8907-34cb2e2df601.png) Delft
![oldeberkoop](https://cloud.githubusercontent.com/assets/2826336/12535983/d1b086e8-c296-11e5-8ffe-bb910cc37da2.png) Oldeberkoop
![heerenveen](https://cloud.githubusercontent.com/assets/2826336/12535984/d1b1e506-c296-11e5-9f8e-f00da0b66c81.png) Heerenveen
![stavoren](https://cloud.githubusercontent.com/assets/2826336/12535985/d1b2cbc4-c296-11e5-8d80-7fdd6ae97fda.png) Stavoren
![weststellingwerf](https://cloud.githubusercontent.com/assets/2826336/12535986/d1c5b1bc-c296-11e5-9a57-3fd4cb533275.png) Weststellingwerf

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks, they're in.
