### ISSUE TITLE
Thessaly, Epirus, Western Macedonia, Central Macedonia, Eastern Macedonia and Thrace municipalities

### ISSUE THREAD

**Issue by gkolas** [flaghunters/Extra-Flags-for-4chan#734]
I've compressed the all flags missing from these areas plus the correct flag for the Eastern Macedonia and Thrace region. 

[Epirus.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/2475871/Epirus.zip)
[Western Macedonia.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/2475872/Western.Macedonia.zip)
[Central Macedonia.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/2475873/Central.Macedonia.zip)
[Eastern Macedonia and Thrace.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/2475874/Eastern.Macedonia.and.Thrace.zip)
[Thessaly.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/2475879/Thessaly.zip)

**Comment by ebinBuddha** [comment]
Hello,
I'm sorry I have to force you to do everything again :P
- always save as png (jpg artifacts ruin the flags completely)
- there are some flags with weird sizes. 16x11 (landscape) and 11x11 are the only accepted
Fix and resubmit please

**Comment by gkolas** [comment]
Let's see now

[Central Macedonia.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/2476812/Central.Macedonia.zip)
[Eastern Macedonia and Thrace.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/2476814/Eastern.Macedonia.and.Thrace.zip)
[Epirus.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/2476815/Epirus.zip)
[Thessaly.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/2476816/Thessaly.zip)
[Western Macedonia.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/2476817/Western.Macedonia.zip)

**Comment by ebinBuddha** [comment]
Added
Thank (You)
