### ISSUE TITLE
Flags For Kansas and Nebraska

### ISSUE THREAD

**Issue by AvidFlagHunter** [flaghunters/Extra-Flags-for-4chan#74]
All of these cities have over 100,000 people at least.
KANSAS
![olathe](https://cloud.githubusercontent.com/assets/16618633/12537322/e3b7382e-c281-11e5-96e6-c19d9674f689.png)
olathe
![topeka](https://cloud.githubusercontent.com/assets/16618633/12537324/eb82645c-c281-11e5-90b5-c872634344e3.png)
topeka
![wichita](https://cloud.githubusercontent.com/assets/16618633/12537342/58524c0a-c282-11e5-9514-f7f936b38767.png)
wichita
NEBRASKA
![lincoln](https://cloud.githubusercontent.com/assets/16618633/12537347/6791fbfc-c282-11e5-9d39-22e8581b2137.png)
Lincoln
![omaha](https://cloud.githubusercontent.com/assets/16618633/12537352/7bd6d3bc-c282-11e5-8679-8155b8047376.png)
Omaha

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks, they're in.
