### ISSUE TITLE
4th lvl flegs for Josephine County, Oregon

### ISSUE THREAD

**Issue by MarthaStewartIsANazi** [flaghunters/Extra-Flags-for-4chan#744]
for the new Oregon anon 
[Josephine.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/2670458/Josephine.zip)

**Comment by MarthaStewartIsANazi** [comment]
please redo, we found a city seal for grants pass. THIS IS UPDATED AND SHOULD BE USED 
[Josephine.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/2670462/Josephine.zip)

**Comment by ebinBuddha** [comment]
Added the the second one
(You)
