### ISSUE TITLE
:^)

### ISSUE THREAD

**Issue by BERGa1** [flaghunters/Extra-Flags-for-4chan#746]
![muntanyola](https://user-images.githubusercontent.com/46005780/50299346-aeb68400-0481-11e9-9871-7f068b6922c8.png) Muntanyola, Osona, Province of Barcelona, Catalonia
![sagas](https://user-images.githubusercontent.com/46005780/50299347-af4f1a80-0481-11e9-9ce8-ecbff1666a6e.png) Sagàs, Berguedà, Province of Barcelona, Catalonia
![sant bartomeu del grau](https://user-images.githubusercontent.com/46005780/50299351-af4f1a80-0481-11e9-8368-0c91d1a2a330.png) Sant Bartomeu del Grau, Osona, Province of Barcelona, Catalonia
![santa maria de merles](https://user-images.githubusercontent.com/46005780/50299352-af4f1a80-0481-11e9-8f0b-19afeedb8f54.png) Santa Maria de Merlès,Berguedà, Province of Barcelona, Catalonia

**Comment by ebinBuddha** [comment]
Added
next time upload here please: https://gitlab.com/flagtism/Extra-Flags-for-4chan/issues
