### ISSUE TITLE
Canton of Neuchâtel

### ISSUE THREAD

**Issue by happynegro** [flaghunters/Extra-Flags-for-4chan#747]
Districts were abolished recently.
Also 6 municipalities were abolished and united into municipality of La Grande Béroche.
[Canton of Neuchâtel.zip](https://github.com/flaghunters/Extra-Flags-for-4chan/files/2914199/Canton.of.Neuchatel.zip)

**Comment by ebinBuddha** [comment]
Done
Thank (You)
