### ISSUE TITLE
Fun/Joke flags

### ISSUE THREAD

**Issue by randoomdude** [flaghunters/Extra-Flags-for-4chan#748]
Any plans to add joke flags?

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Apologies, the issue tracker has been moved to GitLab.
If this issue is still relevant please create an issue here https://gitlab.com/flagtism/Extra-Flags-for-4chan/-/issues
However the chance for joke flags is quite slim, there were a few in past but they were removed.
