### ISSUE TITLE
Florida, S. Carolina, N. Carolina Cities

### ISSUE THREAD

**Issue by Noaboatx** [flaghunters/Extra-Flags-for-4chan#75]
Florida:
Hialeah
![hialeah 16x11](https://cloud.githubusercontent.com/assets/16789560/12542390/4b520f98-c2e8-11e5-87da-68a5e327cfca.png)
St.Petersburg
![st petersburg fl 16x11](https://cloud.githubusercontent.com/assets/16789560/12542396/5ed5da36-c2e8-11e5-8592-a6e0889f370f.png)
South Carolina:
Columbia
![columbia sc 16x11](https://cloud.githubusercontent.com/assets/16789560/12542400/6efc8216-c2e8-11e5-9086-fe541bcf3195.png)
North Carolina:
Raleigh
![raleigh 16x11](https://cloud.githubusercontent.com/assets/16789560/12542409/83dc41f8-c2e8-11e5-999e-375c5b37a1c6.png)

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks again.
These are in as well.
Seems like you're on a roll, if you're planning on adding more, could you zip them up and upload to mediafire or mega?
It will be easier to add and it prevents typo's, Github renames image files to some sort of hash.
