### ISSUE TITLE
Brazil - Guanabara Flag

### ISSUE THREAD

**Issue by Brassebror** [flaghunters/Extra-Flags-for-4chan#77]
Since there's a Sul flag, I'd like to request a flag for The State of Guanabara
It's this one: https://upload.wikimedia.org/wikipedia/commons/5/59/Bandeira_do_Estado_da_Guanabara.png

Thanks, lads.
(I'm not sure if this is the right place for requests. If it isn't, I'm sorry)

**Comment by Noaboatx** [comment]
ill do it for you, you are supposed to do it yourself btw.
![guanabara 16x11](https://cloud.githubusercontent.com/assets/16789560/12601804/bb28b628-c469-11e5-90a1-26ecdb771992.png)
Also enjoy your Zeka

**Comment by Brassebror** [comment]
T-Thanks, fam. I just created this account to request this flag, so I didn't really know how to upload it to the extension/script.
Thanks again.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks, added.
