### ISSUE TITLE
Birmingham, UK city flag

### ISSUE THREAD

**Issue by westmids** [flaghunters/Extra-Flags-for-4chan#80]
Could you add the city flag for BIrmingham please?

https://en.wikipedia.org/wiki/Flag_of_Birmingham_(England)#/media/File:Birmingham_City_Flag.svg

[http://www.birmingham.gov.uk/cs/Satellite?blobcol=urldata&blobkey=id&blobnocache=false&blobtable=MungoBlobs&blobwhere=1223587809590&ssbinary=true](png)

**Comment by Noaboatx** [comment]
4 u, Mohammed.

![birmingham 16x11](https://cloud.githubusercontent.com/assets/16789560/12665152/53d7f25c-c5fb-11e5-86ed-31288e7d506e.png)

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
It's been added.
