### ISSUE TITLE
Add Phi Phi islands please

### ISSUE THREAD

**Issue by Cenaboyle** [flaghunters/Extra-Flags-for-4chan#82]
Well good morning, 
bit cold out.

Can you add Phi Phi islands, Thailand? 

Here's the flag: 
![phi phi islands](https://cloud.githubusercontent.com/assets/16974106/12696206/a804235e-c796-11e5-861a-bd01827354e2.png)

Thank you

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
What a menacing look.

**Comment by Cenaboyle** [comment]
Indeed it is. Look forward to you adding it to the collection. As are the native inhabitants of the islands. There's even talk of erecting a statue in your honour. 

_Mr. Tao, 43 (island resident):_
> When I first heard there was talk about WhatIsThisImNotGoodWithComputers adding Phi Phi islands to the extraflags 4chan extension I almost sh*t myself. What an incredible gesture towards our community and not one that shall be soon forgotten. 

Doesn't that beat all?
