### ISSUE TITLE
Salt Lake City

### ISSUE THREAD

**Issue by Noaboatx** [flaghunters/Extra-Flags-for-4chan#83]
Since i dont want to break my streak. This is all i felt like doing today.
![salt lake city 16x11](https://cloud.githubusercontent.com/assets/16789560/12700225/00dc009c-c7a0-11e5-95b5-65f49637a214.png)

**Comment by Noaboatx** [comment]
shit my streak was broken yesterday apparently.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
I'm sorry lad, Salt Lake City seems to be in there already.
Thanks though :)
