### ISSUE TITLE
Flags too far to the right

### ISSUE THREAD

**Issue by aCarbon** [flaghunters/Extra-Flags-for-4chan#84]
This started happening a couple of days ago, I know a few others have also reported the same problem.

I use Chrome on OS X, I am not sure if it is reproducible on other browsers as well.

<img width="447" alt="screen shot 2016-02-02 at 18 14 25" src="https://cloud.githubusercontent.com/assets/1278163/12759445/09eaea28-c9d9-11e5-99b3-20164e48a623.png">

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Probably the same as #18 
It's no fix but the flags should realign properly if you refresh the page.
Only happens on Chrome, not sure it will ever get fixed.

**Comment by aCarbon** [comment]
@WhatIsThisImNotGoodWithComputers It has been permanent since it started happening, and happens across all threads. Refreshing doesn't fix it unfortunately.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Which version of chrome?

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Please let me know if this fixes it.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
42d6a43

**Comment by aCarbon** [comment]
Yes, this has fixed the issue. Thanks!
