### ISSUE TITLE
Flag Request

### ISSUE THREAD

**Issue by ThisAccountIsForAFlagRequest** [flaghunters/Extra-Flags-for-4chan#87]
Savannah, Georgia, United States of America
Considering that Georgia doesn't have any city flags, I'd like to see Savannah due to its historical significance and population (400,000).
Unless you want to go for super ultra rare shiny flag, in which case I'd like to see Tybee Island, Georgia, due to its tourist popularity but extremely small population.
I'll be right back - I'm making mockups of the flags now.

**Comment by ThisAccountIsForAFlagRequest** [comment]
I've made the flags:
![savannah georgia](https://cloud.githubusercontent.com/assets/17127163/12893833/cdc0c8dc-ce93-11e5-9c78-7bdaeaa0497c.png)
![tybee island georgia](https://cloud.githubusercontent.com/assets/17127163/12893834/ce483c0e-ce93-11e5-9723-0c10f4a9edcb.png)

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks, they're in.
