### ISSUE TITLE
A Few Korean Flags

### ISSUE THREAD

**Issue by LenticCatachresis** [flaghunters/Extra-Flags-for-4chan#89]
Gyeonggi:
![gyeonggi](https://cloud.githubusercontent.com/assets/17322246/13155336/1b8ee59c-d675-11e5-84cc-db5360dd0e89.png)
Seoul:
![seoul](https://cloud.githubusercontent.com/assets/17322246/13155350/29473af4-d675-11e5-9a92-0ad86cf69a0f.png)
Jeju:
![jeju](https://cloud.githubusercontent.com/assets/17322246/13155358/303074c0-d675-11e5-8723-62f6f346c2a6.png)

**Comment by LenticCatachresis** [comment]
Busan:
![busan](https://cloud.githubusercontent.com/assets/17322246/13171482/0f5ad738-d6eb-11e5-86cb-096c21595abf.png)

Daegu:
![daegu](https://cloud.githubusercontent.com/assets/17322246/13171485/15dd0220-d6eb-11e5-8f08-0c6b79a55ceb.png)

Daejeon:
![daejeon](https://cloud.githubusercontent.com/assets/17322246/13171488/1d44d0c4-d6eb-11e5-84b7-44b2cab1fab7.png)

Gangwon:
![gangwon](https://cloud.githubusercontent.com/assets/17322246/13171513/2b6319c2-d6eb-11e5-94cb-88ef77dadce2.png)

Gwangju:
![gwangju](https://cloud.githubusercontent.com/assets/17322246/13171525/3489d482-d6eb-11e5-9c53-f2bab1dad4ac.png)

Incheon:
![incheon](https://cloud.githubusercontent.com/assets/17322246/13171534/3cfa2ce8-d6eb-11e5-845f-063d9f81278f.png)

North Chungcheong:
![north chungcheong](https://cloud.githubusercontent.com/assets/17322246/13171543/487ee23e-d6eb-11e5-8560-97c19271b968.png)

North Gyeongsang:
![north gyeongsang](https://cloud.githubusercontent.com/assets/17322246/13171556/54dd7bf8-d6eb-11e5-9df3-00c9c6ef72e7.png)

North Jeolla:
![north jeolla](https://cloud.githubusercontent.com/assets/17322246/13171565/608be89a-d6eb-11e5-8e93-efad1f01138b.png)

Sejong:
![sejong](https://cloud.githubusercontent.com/assets/17322246/13171573/6d2193ca-d6eb-11e5-94d1-7d1a2bb155c9.png)

South Chungcheong:
![south chungcheong](https://cloud.githubusercontent.com/assets/17322246/13171583/753342d4-d6eb-11e5-860a-fa949baa602b.png)

South Gyeongsang:
![south gyeongsang](https://cloud.githubusercontent.com/assets/17322246/13171589/801c21c0-d6eb-11e5-998e-aacac627a8b8.png)

South Jeolla:
![south jeolla](https://cloud.githubusercontent.com/assets/17322246/13171598/8899d45a-d6eb-11e5-8a45-ba870b5c7372.png)

Ulsan:
![ulsan](https://cloud.githubusercontent.com/assets/17322246/13171603/9003f874-d6eb-11e5-8666-97153e46c2bf.png)

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks, they're added.
Could you zip them up next time?
