### ISSUE TITLE
Some Chinese Flags

### ISSUE THREAD

**Issue by LenticCatachresis** [flaghunters/Extra-Flags-for-4chan#90]
East Turkestan:
![east turkestan](https://cloud.githubusercontent.com/assets/17322246/13161304/cc906158-d694-11e5-946d-685097c97788.png)

Harbin:
![harbin](https://cloud.githubusercontent.com/assets/17322246/13161308/d6823e20-d694-11e5-8a98-aa09e195389f.png)

Inner Mongolia:
![inner mongolia](https://cloud.githubusercontent.com/assets/17322246/13161312/de314616-d694-11e5-8c23-875a124d111e.png)

Kaifeng:
![kaifeng](https://cloud.githubusercontent.com/assets/17322246/13161321/ea735f2c-d694-11e5-81f0-8fb017952367.png)

Nanjing:
![nanjing](https://cloud.githubusercontent.com/assets/17322246/13161331/f324b71a-d694-11e5-8457-ac10cbecab1c.png)

Shangrao:
![shangrao](https://cloud.githubusercontent.com/assets/17322246/13161340/fbc27470-d694-11e5-93cb-dacc1e066906.png)

Suzhou:
![suzhou](https://cloud.githubusercontent.com/assets/17322246/13161345/04468d98-d695-11e5-8433-ba4267e10cdb.png)

Tibet:
![tibet](https://cloud.githubusercontent.com/assets/17322246/13161349/0d0d1ea6-d695-11e5-89f2-7668c83fa318.png)

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks, they've been added.
