### ISSUE TITLE
A couple of the UK flags are incorrect

### ISSUE THREAD

**Issue by qwsdc** [flaghunters/Extra-Flags-for-4chan#92]
I've noticed that a few of the UK regional flags are incorrect.
Cambridgeshire: the flag in the extension for 'Cambridgeshire' is the flag of Cambridgeshire County Council. The flag of Cambridgeshire itself is different.
Norfolk: exactly the same issue.
London: this is a little complicated. London as a city doesn't have an official flag. Greater London is the official region that most of London is in: however, this region does not have an official flag. The flag in the extension for 'Greater London' is the flag of the now non-existent Greater London Council, and has no official status. The flag in the extension for 'London' is actually the official flag of the City of London, a small county within London that is legally distinct from the rest of the city.
If someone has the time to fix these issues I'd be very grateful.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
How do you propose we fix it?

**Comment by qwsdc** [comment]
Here are the correct flags for Cambridgeshire (https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Cambridgeshire_Flag.svg/1280px-Cambridgeshire_Flag.svg.png) and Norfolk (https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Flag_of_Norfolk.svg/1280px-Flag_of_Norfolk.svg.png)
I'd potentially be up for doing them myself. Is there a formatting guide? How does one submit?

Regarding the whole London issue: I think that 'London' should be removed as a region in the extension, as it has no official status either as a city or a region, and has no official flag. 
'Greater London' should be kept, with its current unofficial flag maintained until such time as an official flag is adopted. 
I think you should also create a separate region for the City of London, because although it's part of Greater London, it's a legally distinct city with its own flag. The flag of the City of London is already in the extension (incorrectly) as the flag of London (https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Flag_of_the_City_of_London.svg/1280px-Flag_of_the_City_of_London.svg.png). I guess the simplest way of fixing this particular issue would be to just rename the London region to The City of London.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
There's no guide, you make them as nice as you can, possible with the glossy effect the normal 4chan flags have. You can attach images to comments here or upload to mediafire and post link here.

Checked Wikipedia about London vs City of London and it makes sense, Wiki also put the flag we have next to City of London and not London.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Fixed.
