### ISSUE TITLE
Brazil - Guanabara flag removed

### ISSUE THREAD

**Issue by Brassebror** [flaghunters/Extra-Flags-for-4chan#93]
Why was it removed? It says that it was a "meme flag", but "Sul" is just as much of a meme flag.
Plus, Guanabara actually existed as a state some 30 years ago. 
Sul has never existed nor recognized and never will. And Cisplatina only existed from 1821 to 1828.

I'd really appreciate it if you could re-add it. Thanks, lads.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
It was removed because someone pointed out that there were some meme flags in there.
There were a couple of Italian flags which were old colonies like Istria or old kingdoms. Also Brazil had a couple.

Guanabara doesn't exist any more, why would you want to use it as flag?

**Comment by Brassebror** [comment]
Well, there's actually a movement trying to make Guanabara a thing again, since it's completely different from the rest of the state, both socially and economically.
But, anyway, I get what you mean. You want to make this extension as realistic as possible. I understand.
In this case, I'd like to point out that "Sul" is actually the flag of a separatist movement from the southern region of Brazil and, thus, also a meme flag. You might want to remove it too.

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
I've also removed Sul.

Thanks for understanding, it's hard to draw the line somewhere.
Personally I like going with who is in power, mostly that is just flags which are officially recognised.
The most complicated example is probably Syria because there are various parties in control of certain areas.

**Comment by LenticCatachresis** [comment]
Whilst we're on this topic what are the rules for native population type flags like the Sapmi flag in Norway/Sweden/Finland/Russia and the Aboriginal flag in Australia?

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
There are no hard rules, but flags should be actual (not historic) and have a certain degree of acknowledgement (no separatist movements without any basis, stuff like that).
