### ISSUE TITLE
Peruvian Regional Flags

### ISSUE THREAD

**Issue by u01hr4** [flaghunters/Extra-Flags-for-4chan#94]
Hello there, thought I'd make up some Peruvian flags, since we're a little short. Hope they work, cheers!

Amazonas
![amazonas](https://cloud.githubusercontent.com/assets/17348704/13194148/993e4d6a-d77f-11e5-95f4-4ecfda6f2515.png)
Ancash
![ancash](https://cloud.githubusercontent.com/assets/17348704/13194149/99409a7a-d77f-11e5-9d7c-94269423de04.png)
Apurimac
![apurimac](https://cloud.githubusercontent.com/assets/17348704/13194150/9942b1d4-d77f-11e5-8970-dc57223bb229.png)
Arequipa
![arequipa](https://cloud.githubusercontent.com/assets/17348704/13194151/9944cce4-d77f-11e5-9040-a4c0affbcc0d.png)
Ayacucho
![ayacucho](https://cloud.githubusercontent.com/assets/17348704/13194152/9949350e-d77f-11e5-9b09-cb8181f36aa8.png)
Cajamarca
![cajamarca](https://cloud.githubusercontent.com/assets/17348704/13194153/994a5c18-d77f-11e5-8c05-0376ce4740a9.png)
Callao
![callao](https://cloud.githubusercontent.com/assets/17348704/13194154/9956545a-d77f-11e5-8894-bdd038a8822a.png)
Huancavelica
![huancavelica](https://cloud.githubusercontent.com/assets/17348704/13194155/995a1676-d77f-11e5-8ddb-3bb88e2e859e.png)
Huanuco
![huanuco](https://cloud.githubusercontent.com/assets/17348704/13194156/995c8820-d77f-11e5-8590-e20b35e61f99.png)
Ica
![ica](https://cloud.githubusercontent.com/assets/17348704/13194157/995e2c34-d77f-11e5-9cd4-7265c70455e1.png)
Junin
![junin](https://cloud.githubusercontent.com/assets/17348704/13194158/996301fa-d77f-11e5-8026-b42fa1dfb3a0.png)
La Libertad
![la libertad](https://cloud.githubusercontent.com/assets/17348704/13194159/9965e7e4-d77f-11e5-8ce1-2d7f5f0c4785.png)
Lambayeque
![lambayeque](https://cloud.githubusercontent.com/assets/17348704/13194160/996f7e58-d77f-11e5-8dda-d5f39cf16dcc.png)
Lima Province
![lima province](https://cloud.githubusercontent.com/assets/17348704/13194161/99732bfc-d77f-11e5-89bb-96f7605d2ab3.png)
Lima
![lima region](https://cloud.githubusercontent.com/assets/17348704/13194162/9975b9bc-d77f-11e5-8e42-73cb6562e275.png)
Loreto
![loreto](https://cloud.githubusercontent.com/assets/17348704/13194163/9977ae98-d77f-11e5-9475-a804c3b49e06.png)
Madre de Dios
![madre de dios](https://cloud.githubusercontent.com/assets/17348704/13194164/997d3e08-d77f-11e5-9b3f-e93dac61598e.png)
Moquegua
![moquegua](https://cloud.githubusercontent.com/assets/17348704/13194165/997f5d3c-d77f-11e5-99e2-f7ab339de71f.png)
Pasco
![pasco](https://cloud.githubusercontent.com/assets/17348704/13194166/9987cf9e-d77f-11e5-8b0f-768084bb32bb.png)
Piura
![piura](https://cloud.githubusercontent.com/assets/17348704/13194167/998b33c8-d77f-11e5-88b8-a92995c5580f.png)
Puno
![puno](https://cloud.githubusercontent.com/assets/17348704/13194168/998eeaae-d77f-11e5-9b11-880f3c79181f.png)
San Martin
![san martin](https://cloud.githubusercontent.com/assets/17348704/13194169/9991aa96-d77f-11e5-8a6a-52331e273fce.png)
Tacna
![tacna](https://cloud.githubusercontent.com/assets/17348704/13194170/9997c2fa-d77f-11e5-9270-2fbf22150e28.png)
Tumbes
![tumbes](https://cloud.githubusercontent.com/assets/17348704/13194171/9998b480-d77f-11e5-82ad-8b3e77cf1408.png)
Ucayali
![ucayali](https://cloud.githubusercontent.com/assets/17348704/13194172/999fb1c2-d77f-11e5-93e7-3cb07db21872.png)

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks, they;re in.
