### ISSUE TITLE
Trinidad & Tobago Flags

### ISSUE THREAD

**Issue by u01hr4** [flaghunters/Extra-Flags-for-4chan#95]
Got some Trinidad & Tobago flags done too, enjoy. For some reason tt says it doesn't support the ZIP files I'm trying to upload, so I'm afraid they're PNGs again.

Arima
![arima](https://cloud.githubusercontent.com/assets/17348704/13194587/cf6464d8-d78e-11e5-86a0-0e0dcb45402f.png)
Chaguanas
![chaguanas](https://cloud.githubusercontent.com/assets/17348704/13194589/cf6a8bba-d78e-11e5-8c26-7c3aca14da24.png)
Couva-Tabaquite-Talparo
![couva-tabaquite-talparo](https://cloud.githubusercontent.com/assets/17348704/13194588/cf6a5316-d78e-11e5-90c4-b0b6524511a8.png)
Diego Martin
![diego martin](https://cloud.githubusercontent.com/assets/17348704/13194590/cf6c01a2-d78e-11e5-94cf-3a2c8f176869.png)
Mayaro-Rio-Claro
![mayaro-rio claro](https://cloud.githubusercontent.com/assets/17348704/13194591/cf6ecef0-d78e-11e5-8ca8-b913a8a2f96b.png)
Penal-Debe
![penal-debe](https://cloud.githubusercontent.com/assets/17348704/13194592/cf7183de-d78e-11e5-9976-474682b54e5a.png)
Point Fortin
![point fortin](https://cloud.githubusercontent.com/assets/17348704/13194593/cf7eba86-d78e-11e5-88b0-9c5a6cb1b1cc.png)
Port of Spain
![port of spain](https://cloud.githubusercontent.com/assets/17348704/13194594/cf82cbc6-d78e-11e5-8b9b-4e3ed17ece77.png)
Princes Town
![princes town](https://cloud.githubusercontent.com/assets/17348704/13194595/cf869594-d78e-11e5-82b8-fb1626bd020e.png)
San Fernando
![san fernando](https://cloud.githubusercontent.com/assets/17348704/13194596/cf87eca0-d78e-11e5-84db-2868898af9ed.png)
San Juan-Laventille
![san juan-laventille](https://cloud.githubusercontent.com/assets/17348704/13194597/cf8dc5ee-d78e-11e5-8dc2-e30a6797507a.png)
Sangre Grande
![sangre grande](https://cloud.githubusercontent.com/assets/17348704/13194598/cf8efe6e-d78e-11e5-86ad-387cbd74edd9.png)
Siparia
![siparia](https://cloud.githubusercontent.com/assets/17348704/13194599/cf9a6ae2-d78e-11e5-867f-fcf1736e114e.png)
Tobago
![tobago](https://cloud.githubusercontent.com/assets/17348704/13194600/cf9b7ca2-d78e-11e5-8806-b5a3584d88a7.png)
Tunapuna-Piarco
![tunapuna-piarco](https://cloud.githubusercontent.com/assets/17348704/13194601/cf9f7e6a-d78e-11e5-9493-d5446fd67bf8.png)

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks they're in.
