### ISSUE TITLE
Various Asian Flags

### ISSUE THREAD

**Issue by LenticCatachresis** [flaghunters/Extra-Flags-for-4chan#96]
China, Weihai:
![weihai](https://cloud.githubusercontent.com/assets/17322246/13196578/a87708c2-d7c9-11e5-925a-f047181caa25.png)

Indonesia, Aceh:
![aceh](https://cloud.githubusercontent.com/assets/17322246/13196582/baa27c2a-d7c9-11e5-9c5c-27b490a0986b.png)

Japan, Ryukyu Islands:
![ryukyu islands](https://cloud.githubusercontent.com/assets/17322246/13196584/c98152f2-d7c9-11e5-830c-712892a4ca0a.png)

Thailand, Chiang Rai:
![chiang rai](https://cloud.githubusercontent.com/assets/17322246/13196594/e49763ba-d7c9-11e5-91af-09d35903257d.png)

Thailand, Kamphaeng Phet:
![kamphaeng phet](https://cloud.githubusercontent.com/assets/17322246/13196598/f2bef0b6-d7c9-11e5-9838-1af15f80fbe1.png)

Thailand, Pattani:
![pattani](https://cloud.githubusercontent.com/assets/17322246/13196600/ffa1a17a-d7c9-11e5-91de-acc73b6a706d.png)

Vietnam, South Vietnam
![south vietnam](https://cloud.githubusercontent.com/assets/17322246/13196601/1175cbce-d7ca-11e5-8fb7-18ad6dbb546e.png)

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks, they're in.
Except for South Vietnam, which no longer exists as a region.
