### ISSUE TITLE
Some Miscellaneous Flags

### ISSUE THREAD

**Issue by LenticCatachresis** [flaghunters/Extra-Flags-for-4chan#97]
Andorra, Andorra la Vella:
![andorra la vella](https://cloud.githubusercontent.com/assets/17322246/13199345/df07be3a-d81a-11e5-8c71-937adb9878e7.png)

Israel, Haifa:
![haifa](https://cloud.githubusercontent.com/assets/17322246/13199347/ece3735a-d81a-11e5-8ba5-d04eb97b0336.png)

Israel, Holon:
![holon](https://cloud.githubusercontent.com/assets/17322246/13199349/f6b49b98-d81a-11e5-8e4a-a74f3c5af6b7.png)

Mexico, Queretaro:
![queretaro](https://cloud.githubusercontent.com/assets/17322246/13199352/0301e0ae-d81b-11e5-8d91-ace585b973fb.png)

New Zealand, Chatham Islands:
![chatham islands](https://cloud.githubusercontent.com/assets/17322246/13199356/117eb422-d81b-11e5-9b53-14185d48d9b0.png)

Norway+Sweden+Finland+Russia, Sapmi:
![sapmi](https://cloud.githubusercontent.com/assets/17322246/13199359/3be283ce-d81b-11e5-99d5-77956fdd93a7.png)

United Kingdom, Berkshire:
![berkshire](https://cloud.githubusercontent.com/assets/17322246/13199360/470537f6-d81b-11e5-80b2-8e5c594dfcd6.png)

**Comment by LenticCatachresis** [comment]
Faroe Islands, Torshavn:
![torshavn](https://cloud.githubusercontent.com/assets/17322246/13204444/14a38198-d8c8-11e5-9399-32058e530384.png)

Greece, Crete:
![crete](https://cloud.githubusercontent.com/assets/17322246/13204446/205ec79a-d8c8-11e5-90c1-07a96c65180b.png)

Malta, Valletta:
![valletta](https://cloud.githubusercontent.com/assets/17322246/13204449/2cf777c2-d8c8-11e5-9874-a476b0779ebd.png)

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks, added these.
