### ISSUE TITLE
Portugal Flags

### ISSUE THREAD

**Issue by LenticCatachresis** [flaghunters/Extra-Flags-for-4chan#98]
Aveiro:
![aveiro](https://cloud.githubusercontent.com/assets/17322246/13300309/7171c5c6-db37-11e5-891e-2877254d757e.png)

Castelo Branco:
![castelo branco](https://cloud.githubusercontent.com/assets/17322246/13300314/77141894-db37-11e5-9f40-8743849186e9.png)

Coimbra:
![coimbra](https://cloud.githubusercontent.com/assets/17322246/13300328/8003916e-db37-11e5-9328-b231bbc213a1.png)

Evora:
![evora](https://cloud.githubusercontent.com/assets/17322246/13300333/89b3bf4a-db37-11e5-98a4-ad1163b7e5a1.png)

Guarda:
![guarda](https://cloud.githubusercontent.com/assets/17322246/13300348/94891082-db37-11e5-999e-f167fe5bb418.png)

Leiria:
![leiria](https://cloud.githubusercontent.com/assets/17322246/13300361/9d152e3e-db37-11e5-921e-90dfc67dd9c9.png)

Portalegre:
![portalegre](https://cloud.githubusercontent.com/assets/17322246/13300367/a5cc269a-db37-11e5-815d-4cca7dcb87ad.png)

Viseu:
![viseu](https://cloud.githubusercontent.com/assets/17322246/13300378/afb6f5b8-db37-11e5-9727-55174aa5babf.png)

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Please zip and upload to mediafire or mega.
Getting a lot of new flags lately and it's a pain to save them and rename them individually.

**Comment by LenticCatachresis** [comment]
https://mega.nz/#!DcNgRZKQ!EEQRVBZwNgbiaI-h8Zh79mV0uor8wQN6-t9XMvBZM2U

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks fam, appreciate it.
They're added.
