### ISSUE TITLE
Bahrain Governorates

### ISSUE THREAD

**Issue by LenticCatachresis** [flaghunters/Extra-Flags-for-4chan#99]
Capital Governorate:
![capital governorate](https://cloud.githubusercontent.com/assets/17322246/13336907/91141b5c-dc10-11e5-8924-c4a18923fda9.png)

Muharraq Governorate:
![muharraq governorate](https://cloud.githubusercontent.com/assets/17322246/13336914/9bc446da-dc10-11e5-9ba9-b3c0d9b2288b.png)

Northern Governorate:
![northern governorate](https://cloud.githubusercontent.com/assets/17322246/13336920/a4ea1212-dc10-11e5-8850-cc32e57bd089.png)

Southern Governorate:
![southern governorate](https://cloud.githubusercontent.com/assets/17322246/13336934/b55485ec-dc10-11e5-8166-7cdc3f892e3c.png)

**Comment by WhatIsThisImNotGoodWithComputers** [comment]
Thanks, they're in.
